package com.elitecore.aaa.mibs.radius.dynauth.server.autogen;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling RADIUS-DYNAUTH-SERVER-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpOidRecord;

// jdmk imports
//
import com.sun.management.snmp.SnmpOidTableSupport;

/**
 * The class contains metadata definitions for "RADIUS-DYNAUTH-SERVER-MIB".
 * Call SnmpOid.setSnmpOidTable(new RADIUS_DYNAUTH_SERVER_MIBOidTable()) to load the metadata in the SnmpOidTable.
 */
public class RADIUS_DYNAUTH_SERVER_MIBOidTable extends SnmpOidTableSupport implements Serializable {

    /**
     * Default constructor. Initialize the Mib tree.
     */
    public RADIUS_DYNAUTH_SERVER_MIBOidTable() {
        super("RADIUS_DYNAUTH_SERVER_MIB");
        loadMib(varList);
    }

    static SnmpOidRecord varList [] = {
        new SnmpOidRecord("radiusDynAuthClientTable", "1.3.6.1.2.1.146.1.2", "TA"),
        new SnmpOidRecord("radiusDynAuthClientEntry", "1.3.6.1.2.1.146.1.2.1", "EN"),
        new SnmpOidRecord("radiusDynAuthServCoANaks", "1.3.6.1.2.1.146.1.2.1.19", "C"),
        new SnmpOidRecord("radiusDynAuthServCoAAcks", "1.3.6.1.2.1.146.1.2.1.18", "C"),
        new SnmpOidRecord("radiusDynAuthServDupCoARequests", "1.3.6.1.2.1.146.1.2.1.17", "C"),
        new SnmpOidRecord("radiusDynAuthServCoAAuthOnlyRequests", "1.3.6.1.2.1.146.1.2.1.16", "C"),
        new SnmpOidRecord("radiusDynAuthServCoARequests", "1.3.6.1.2.1.146.1.2.1.15", "C"),
        new SnmpOidRecord("radiusDynAuthServDisconPacketsDropped", "1.3.6.1.2.1.146.1.2.1.14", "C"),
        new SnmpOidRecord("radiusDynAuthServDisconBadAuthenticators", "1.3.6.1.2.1.146.1.2.1.13", "C"),
        new SnmpOidRecord("radiusDynAuthServMalformedDisconRequests", "1.3.6.1.2.1.146.1.2.1.12", "C"),
        new SnmpOidRecord("radiusDynAuthServDisconUserSessRemoved", "1.3.6.1.2.1.146.1.2.1.11", "C"),
        new SnmpOidRecord("radiusDynAuthServDisconNakSessNoContext", "1.3.6.1.2.1.146.1.2.1.10", "C"),
        new SnmpOidRecord("radiusDynAuthServDisconNakAuthOnlyRequests", "1.3.6.1.2.1.146.1.2.1.9", "C"),
        new SnmpOidRecord("radiusDynAuthServDisconNaks", "1.3.6.1.2.1.146.1.2.1.8", "C"),
        new SnmpOidRecord("radiusDynAuthServDisconAcks", "1.3.6.1.2.1.146.1.2.1.7", "C"),
        new SnmpOidRecord("radiusDynAuthServerCounterDiscontinuity", "1.3.6.1.2.1.146.1.2.1.27", "T"),
        new SnmpOidRecord("radiusDynAuthServDupDisconRequests", "1.3.6.1.2.1.146.1.2.1.6", "C"),
        new SnmpOidRecord("radiusDynAuthServDisconAuthOnlyRequests", "1.3.6.1.2.1.146.1.2.1.5", "C"),
        new SnmpOidRecord("radiusDynAuthServUnknownTypes", "1.3.6.1.2.1.146.1.2.1.26", "C"),
        new SnmpOidRecord("radiusDynAuthServDisconRequests", "1.3.6.1.2.1.146.1.2.1.4", "C"),
        new SnmpOidRecord("radiusDynAuthServCoAPacketsDropped", "1.3.6.1.2.1.146.1.2.1.25", "C"),
        new SnmpOidRecord("radiusDynAuthServCoABadAuthenticators", "1.3.6.1.2.1.146.1.2.1.24", "C"),
        new SnmpOidRecord("radiusDynAuthClientAddress", "1.3.6.1.2.1.146.1.2.1.3", "S"),
        new SnmpOidRecord("radiusDynAuthClientAddressType", "1.3.6.1.2.1.146.1.2.1.2", "I"),
        new SnmpOidRecord("radiusDynAuthServMalformedCoARequests", "1.3.6.1.2.1.146.1.2.1.23", "C"),
        new SnmpOidRecord("radiusDynAuthServCoAUserSessChanged", "1.3.6.1.2.1.146.1.2.1.22", "C"),
        new SnmpOidRecord("radiusDynAuthClientIndex", "1.3.6.1.2.1.146.1.2.1.1", "I"),
        new SnmpOidRecord("radiusDynAuthServCoANakSessNoContext", "1.3.6.1.2.1.146.1.2.1.21", "C"),
        new SnmpOidRecord("radiusDynAuthServCoANakAuthOnlyRequests", "1.3.6.1.2.1.146.1.2.1.20", "C"),
        new SnmpOidRecord("radiusDynAuthServerIdentifier", "1.3.6.1.2.1.146.1.1.3", "S"),
        new SnmpOidRecord("radiusDynAuthServerCoAInvalidClientAddresses", "1.3.6.1.2.1.146.1.1.2", "C"),
        new SnmpOidRecord("radiusDynAuthServerDisconInvalidClientAddresses", "1.3.6.1.2.1.146.1.1.1", "C"),
        new SnmpOidRecord("radiusDynAuthServerAuthOnlyGroup", "1.3.6.1.2.1.146.2.2.2", "OBG"),
        new SnmpOidRecord("radiusDynAuthServerMIBGroup", "1.3.6.1.2.1.146.2.2.1", "OBG"),
        new SnmpOidRecord("radiusDynAuthServerNoSessGroup", "1.3.6.1.2.1.146.2.2.3", "OBG")    };
}
