package com.elitecore.diameterapi.mibs.cc.autogen;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling DIAMETER-CC-APPLICATION-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "DccaHostIpAddrEntry" MBean.
 */
public interface DccaHostIpAddrEntryMBean {

    /**
     * Getter for the "DccaHostIpAddress" variable.
     */
    public Byte[] getDccaHostIpAddress() throws SnmpStatusException;

    /**
     * Getter for the "DccaHostIpAddrType" variable.
     */
    public EnumDccaHostIpAddrType getDccaHostIpAddrType() throws SnmpStatusException;

    /**
     * Getter for the "DccaHostIpAddrIndex" variable.
     */
    public Long getDccaHostIpAddrIndex() throws SnmpStatusException;

}
