package com.elitecore.diameterapi.mibs.cc.autogen;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling DIAMETER-CC-APPLICATION-MIB.
//

// java imports
//
import java.io.Serializable;

import com.sun.management.snmp.SnmpStatusException;
import com.sun.management.snmp.agent.SnmpMib;
// jmx imports
//
// jdmk imports
//

/**
 * The class is used for implementing the "DccaHostIpAddrEntry" group.
 * The group is defined with the following oid: 1.3.6.1.2.1.4006.2.1.1.2.1.
 */
public class DccaHostIpAddrEntry implements DccaHostIpAddrEntryMBean, Serializable {

	public DccaHostIpAddrEntry() {
	}
	
    /**
     * Variable for storing the value of "DccaHostIpAddress".
     * The variable is identified by: "1.3.6.1.2.1.4006.2.1.1.2.1.3".
     *
     * "The IP-Address of the host, which is of the
     * type specified in dccaHostIpAddrType."
     *
     */
    protected Byte[] DccaHostIpAddress = { new Byte("74"), new Byte("68"), new Byte("77"), new Byte("75")};

    /**
     * Variable for storing the value of "DccaHostIpAddrType".
     * The variable is identified by: "1.3.6.1.2.1.4006.2.1.1.2.1.2".
     *
     * "The type of internet address stored
     * in dccaHostIpAddress."
     *
     */
    protected EnumDccaHostIpAddrType DccaHostIpAddrType = new EnumDccaHostIpAddrType();

    /**
     * Variable for storing the value of "DccaHostIpAddrIndex".
     * The variable is identified by: "1.3.6.1.2.1.4006.2.1.1.2.1.1".
     *
     * "A number uniquely identifying the number
     * of IP Addresses supported by this Diameter
     * Credit Control host."
     *
     */
    protected Long DccaHostIpAddrIndex = new Long(1);


    /**
     * Constructor for the "DccaHostIpAddrEntry" group.
     */
    public DccaHostIpAddrEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "DccaHostIpAddress" variable.
     */
    public Byte[] getDccaHostIpAddress() throws SnmpStatusException {
        return DccaHostIpAddress;
    }

    /**
     * Getter for the "DccaHostIpAddrType" variable.
     */
    public EnumDccaHostIpAddrType getDccaHostIpAddrType() throws SnmpStatusException {
        return DccaHostIpAddrType;
    }

    /**
     * Getter for the "DccaHostIpAddrIndex" variable.
     */
    public Long getDccaHostIpAddrIndex() throws SnmpStatusException {
        return DccaHostIpAddrIndex;
    }

}
