package com.elitecore.diameterapi.mibs.cc.autogen;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling DIAMETER-CC-APPLICATION-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "DccaHostCfgs" MBean.
 */
public interface DccaHostCfgsMBean {

    /**
     * Access the "DccaHostIpAddrTable" variable.
     */
    public TableDccaHostIpAddrTable accessDccaHostIpAddrTable() throws SnmpStatusException;

    /**
     * Getter for the "DccaHostID" variable.
     */
    public String getDccaHostID() throws SnmpStatusException;

}
