package com.elitecore.commons.kpi.mib.autogen;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling TEST-MIB.
//

// java imports
//
import java.io.Serializable;

import com.sun.management.snmp.SnmpOidRecord;
import com.sun.management.snmp.SnmpOidTableSupport;

/**
 * The class contains metadata definitions for "TEST-MIB".
 * Call SnmpOid.setSnmpOidTable(new TEST_MIBOidTable()) to load the metadata in the SnmpOidTable.
 */
@SuppressWarnings("serial")
public class TEST_MIBOidTable extends SnmpOidTableSupport implements Serializable {

    /**
     * Default constructor. Initialize the Mib tree.
     */
    public TEST_MIBOidTable() {
        super("TEST_MIB");
        loadMib(varList);
    }

    static SnmpOidRecord varList [] = {
        new SnmpOidRecord("kpiTestingTable", "1.3.6.1.4.1.21067.1.3", "TA"),
        new SnmpOidRecord("kpiCounterEntry", "1.3.6.1.4.1.21067.1.3.1", "EN"),
        new SnmpOidRecord("testCounter2", "1.3.6.1.4.1.21067.1.3.1.3", "C"),
        new SnmpOidRecord("testCounter1", "1.3.6.1.4.1.21067.1.3.1.2", "C"),
        new SnmpOidRecord("kpiCounterIndex", "1.3.6.1.4.1.21067.1.3.1.1", "I"),
        new SnmpOidRecord("totalTestCounter2", "1.3.6.1.4.1.21067.1.2", "C"),
        new SnmpOidRecord("totalTestCounter1", "1.3.6.1.4.1.21067.1.1", "C")    };
}
