package com.elitecore.elitesm.web.dashboard.widget.constants;

public enum WidgetTypeConstants {
	ESI,
	PEER,
	MEMUSAGE,
	RAD_AUTH_ESI_STATISTICS,
	REPLYMESSAGESTATSUMMARY,
	RAD_AUTH_CLIENT,
	RAD_AUTH_SERV,
	RAD_ACCT_CLIENT,
	RAD_ACCT_SERV,
	JVM_DETAIL_MEMUSAGE,
	CPU_USAGE,
	RAD_DYNA_AUTH_CLIENT,
	RAD_DYNA_AUTH_SERVER,
	RAD_ACCT_ESI_STATISTICS,
	NAS_ESI_STATISTICS
	;
}
