package com.elitecore.core.serverx.snmp.mib.os.autogen;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling UCD-SNMP-MIB.
//

// java imports
//
import java.io.Serializable;
import java.util.Hashtable;

// RI imports
//
import com.sun.jdmk.Enumerated;

/**
 * The class is used for representing "DskErrorFlag".
 */
public class EnumDskErrorFlag extends Enumerated implements Serializable {

    protected static Hashtable intTable = new Hashtable();
    protected static Hashtable stringTable = new Hashtable();
    static  {
        intTable.put(new Integer(0), "noError");
        intTable.put(new Integer(1), "error");
        stringTable.put("noError", new Integer(0));
        stringTable.put("error", new Integer(1));
    }

    public EnumDskErrorFlag(int valueIndex) throws IllegalArgumentException {
        super(valueIndex);
    }

    public EnumDskErrorFlag(Integer valueIndex) throws IllegalArgumentException {
        super(valueIndex);
    }

    public EnumDskErrorFlag() throws IllegalArgumentException {
        super();
    }

    public EnumDskErrorFlag(String x) throws IllegalArgumentException {
        super(x);
    }

    protected Hashtable getIntTable() {
        return intTable ;
    }

    protected Hashtable getStringTable() {
        return stringTable ;
    }

}
