package com.elitecore.core.serverx.snmp.mib.os.autogen;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling UCD-SNMP-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "ExtEntry" MBean.
 */
public interface ExtEntryMBean {

    /**
     * Getter for the "ExtErrFixCmd" variable.
     */
    public String getExtErrFixCmd() throws SnmpStatusException;

    /**
     * Getter for the "ExtCommand" variable.
     */
    public String getExtCommand() throws SnmpStatusException;

    /**
     * Getter for the "ExtErrFix" variable.
     */
    public EnumExtErrFix getExtErrFix() throws SnmpStatusException;

    /**
     * Setter for the "ExtErrFix" variable.
     */
    public void setExtErrFix(EnumExtErrFix x) throws SnmpStatusException;

    /**
     * Checker for the "ExtErrFix" variable.
     */
    public void checkExtErrFix(EnumExtErrFix x) throws SnmpStatusException;

    /**
     * Getter for the "ExtOutput" variable.
     */
    public String getExtOutput() throws SnmpStatusException;

    /**
     * Getter for the "ExtNames" variable.
     */
    public String getExtNames() throws SnmpStatusException;

    /**
     * Getter for the "ExtIndex" variable.
     */
    public Integer getExtIndex() throws SnmpStatusException;

    /**
     * Getter for the "ExtResult" variable.
     */
    public Integer getExtResult() throws SnmpStatusException;

}
