CREATE TABLESPACE eliteaaa DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/eliteaaa.dbf' size 100M AUTOEXTEND ON;

CREATE USER eliteaaa IDENTIFIED BY eliteaaa DEFAULT TABLESPACE eliteaaa TEMPORARY TABLESPACE temp QUOTA UNLIMITED ON eliteaaa;

GRANT CONNECT,RESOURCE, CREATE ANY VIEW TO eliteaaa;

GRANT CREATE JOB TO eliteaaa; 

--12c Compatibility

GRANT UNLIMITED TABLESPACE TO eliteaaa;