
-- EliteKPI Prerequisites for Database Package Module --
	 
CREATE TABLE TBL_KPI_M3_QFLTR
   (	INSTANCEID VARCHAR2(50 BYTE), 
	P_COLUMN_NAME1 VARCHAR2(50 BYTE), 
	P_COLUMN_NAME2 NUMBER, 
	P_COLUMN_NAME2_MINVAL NUMBER, 
	P_COLUMN_NAME2_MAXVAL NUMBER, 
	CREATETIME TIMESTAMP (6)
   )NOLOGGING;

CREATE INDEX INX_TBL_KPI_M3_QFLTR ON TBL_KPI_M3_QFLTR (INSTANCEID, P_COLUMN_NAME1, CREATETIME); 

CREATE TABLE TBL_KPI_M4_QFLTR
   (	INSTANCEID VARCHAR2(50 BYTE), 
	P_COLUMN_NAME1 NUMBER, 
	P_COLUMN_NAME1_MINVAL NUMBER, 
	P_COLUMN_NAME1_MAXVAL NUMBER, 
	P_COLUMN_NAME2 NUMBER, 
	P_COLUMN_NAME2_MINVAL NUMBER, 
	P_COLUMN_NAME2_MAXVAL NUMBER, 
	CREATETIME TIMESTAMP (6)
   )NOLOGGING;
   
CREATE INDEX INX_TBL_KPI_M4_QFLTR ON TBL_KPI_M4_QFLTR (INSTANCEID,CREATETIME); 
   

    
-- EliteKPI Package -- PKG_ELITECSM_KPI_HIST_TRN --

create or replace PACKAGE PKG_ELITECSM_KPI_HIST_TRN
AS
  /*  ELITECSM KPI DATA PROCESSING MODULE
  ELITECORE TECHNOLOGIES PVT. LTD. */

  PROCEDURE PROC_KPI_DATA_PROCESS_METHOD1 (P_TABLE_NAME USER_TABLES.TABLE_NAME%TYPE);
  PROCEDURE PROC_KPI_DATA_PROCESS_METHOD2 (P_TABLE_NAME USER_TABLES.TABLE_NAME%TYPE,P_COLUMN_NAME VARCHAR2);
  PROCEDURE PROC_KPI_DATA_PROCESS_METHOD3 (P_TABLE_NAME USER_TABLES.TABLE_NAME%TYPE,P_COLUMN_NAME1 VARCHAR2,P_COLUMN_NAME2 VARCHAR2);
  PROCEDURE PROC_KPI_DATA_PROCESS_METHOD4 (P_TABLE_NAME USER_TABLES.TABLE_NAME%TYPE,P_COLUMN_NAME1 VARCHAR2,P_COLUMN_NAME2 VARCHAR2);
  PROCEDURE PROC_KPI_DATA_PROCESS_MAIN;
  
END PKG_ELITECSM_KPI_HIST_TRN;
/

-- EliteKPI Package Body -- PKG_ELITECSM_KPI_HIST_TRN -

create or replace PACKAGE BODY PKG_ELITECSM_KPI_HIST_TRN
AS
  /*  ELITECSM KPI DATA PROCESSING MODULE
  ELITECORE TECHNOLOGIES PVT. LTD. */

	PROCEDURE PROC_KPI_DATA_PROCESS_METHOD1(P_TABLE_NAME USER_TABLES.TABLE_NAME%TYPE)
	AS
    V_TAB_NM VARCHAR2(255);
	BEGIN


     DBMS_OUTPUT.PUT_LINE(P_TABLE_NAME ||' Data processing Start...');

					--1.) 2 days fixed records - Aprox 1440 Rec/Day
					--2.) Current Months Left days e.g. Last 28 days records - Captured Hourly 1 records , Aprox. 24 Rec/Day
					--3.) Last Months Jan to Current month-1 Aprox. 1 rec/day

          EXECUTE IMMEDIATE ('DELETE
          FROM '||P_TABLE_NAME ||' M
          WHERE NOT EXISTS
            (SELECT *
            FROM
              (SELECT *
              FROM '||P_TABLE_NAME ||'
              WHERE CREATETIME BETWEEN CURRENT_TIMESTAMP - 1 AND CURRENT_TIMESTAMP
              UNION ALL
              SELECT *
              FROM '||P_TABLE_NAME ||'
              WHERE (INSTANCEID,CREATETIME) IN
                (SELECT INSTANCEID,MAX(CREATETIME)
                FROM
                  (SELECT *
                  FROM '||P_TABLE_NAME ||'
                  WHERE TO_CHAR(CREATETIME,''MM'') = TO_CHAR(sysdate,''MM'')
                  )
                GROUP BY INSTANCEID,TO_CHAR(CREATETIME,''DD-MON-RRRR HH24'')
                )
              UNION ALL
              SELECT *
              FROM '||P_TABLE_NAME ||'
              WHERE (INSTANCEID,CREATETIME) IN
                (SELECT INSTANCEID,MAX(CREATETIME)
                FROM '||P_TABLE_NAME ||'
                WHERE TO_CHAR(CREATETIME,''MM'') BETWEEN 1 AND TO_CHAR(ADD_MONTHS(LAST_DAY(SYSDATE),-1),''MM'')
                GROUP BY INSTANCEID,TO_CHAR(CREATETIME,''DD-MON-RRRR'')
                )
              ) I
            WHERE I.CREATETIME = M.CREATETIME
            )');

          --code debug
		  /*
          DBMS_OUTPUT.PUT_LINE('DELETE
          FROM '||P_TABLE_NAME ||' M
          WHERE NOT EXISTS
            (SELECT *
            FROM
              (SELECT *
              FROM '||P_TABLE_NAME ||'
              WHERE CREATETIME BETWEEN CURRENT_TIMESTAMP - 1 AND CURRENT_TIMESTAMP
              UNION ALL
              SELECT *
              FROM '||P_TABLE_NAME ||'
              WHERE (INSTANCEID,CREATETIME) IN
                (SELECT INSTANCEID,MAX(CREATETIME)
                FROM
                  (SELECT *
                  FROM '||P_TABLE_NAME ||'
                  WHERE TO_CHAR(CREATETIME,''MM'') = TO_CHAR(sysdate,''MM'')
                  )
                GROUP BY INSTANCEID,TO_CHAR(CREATETIME,''DD-MON-RRRR HH24'')
                )
              UNION ALL
              SELECT *
              FROM '||P_TABLE_NAME ||'
              WHERE (INSTANCEID,CREATETIME) IN
                (SELECT INSTANCEID,MAX(CREATETIME)
                FROM '||P_TABLE_NAME ||'
                WHERE TO_CHAR(CREATETIME,''MM'') BETWEEN 1 AND TO_CHAR(ADD_MONTHS(LAST_DAY(SYSDATE),-1),''MM'')
                GROUP BY INSTANCEID,TO_CHAR(CREATETIME,''DD-MON-RRRR'')
                )
              ) I
            WHERE I.CREATETIME = M.CREATETIME
            )');
          */

       COMMIT;

        EXECUTE IMMEDIATE 'ALTER TABLE '||P_TABLE_NAME|| ' ENABLE ROW MOVEMENT';

        EXECUTE IMMEDIATE 'ALTER TABLE '||P_TABLE_NAME|| ' SHRINK SPACE CASCADE';

        EXECUTE IMMEDIATE 'ALTER TABLE '||P_TABLE_NAME|| ' DISABLE ROW MOVEMENT';

        DBMS_OUTPUT.PUT_LINE(P_TABLE_NAME ||' Data processing End.');

    END;

  PROCEDURE PROC_KPI_DATA_PROCESS_METHOD2 (P_TABLE_NAME USER_TABLES.TABLE_NAME%TYPE,P_COLUMN_NAME VARCHAR2)
    AS
      V_TAB_NM VARCHAR2(255);

    BEGIN

       DBMS_OUTPUT.PUT_LINE(P_TABLE_NAME ||' Data processing Start...');

	   				--1.) 2 days fixed records - Aprox 1440 Rec/Day
					--2.) Current Months Left days e.g. Last 28 days records - Captured Hourly 1 records per thread wise
					--3.) Last Months Jan to Current month-1 Aprox. 1 rec per thread each day basis

     EXECUTE IMMEDIATE ('DELETE FROM '|| P_TABLE_NAME ||' M
       WHERE NOT EXISTS (SELECT * FROM (
              SELECT * FROM '||P_TABLE_NAME ||'
              WHERE CREATETIME BETWEEN CURRENT_TIMESTAMP - 1 AND CURRENT_TIMESTAMP
              UNION ALL
              SELECT *
              FROM '||P_TABLE_NAME||'
              WHERE ( INSTANCEID,'||P_COLUMN_NAME||',CREATETIME) IN
                (SELECT INSTANCEID,'||P_COLUMN_NAME||',MAX(CREATETIME)
                FROM
                  (SELECT *
                  FROM ' ||P_TABLE_NAME|| '
                  WHERE TO_CHAR(CREATETIME,''MM'') = TO_CHAR(sysdate,''MM'')
                  )
                GROUP BY INSTANCEID,'||P_COLUMN_NAME||',TO_CHAR(CREATETIME,''DD-MON-RRRR HH24'')
                )
              UNION ALL
              SELECT *
              FROM ' ||P_TABLE_NAME|| '
              WHERE (INSTANCEID,'||P_COLUMN_NAME||',CREATETIME) IN
                (SELECT INSTANCEID,'||P_COLUMN_NAME||',MAX(CREATETIME)
                FROM ' ||P_TABLE_NAME|| '
                WHERE TO_CHAR(CREATETIME,''MM'') BETWEEN 1 AND TO_CHAR(ADD_MONTHS(LAST_DAY(SYSDATE),-1),''MM'')
                GROUP BY INSTANCEID,' ||P_COLUMN_NAME|| ',TO_CHAR(CREATETIME,''DD-MON-RRRR'')
                ))I
                WHERE I.' ||P_COLUMN_NAME|| ' = M.' ||P_COLUMN_NAME|| '
                AND I.CREATETIME = M.CREATETIME)');

       --code debug
	   /*
       DBMS_OUTPUT.PUT_LINE('DELETE FROM '|| P_TABLE_NAME ||' M
       WHERE NOT EXISTS (SELECT * FROM (
              SELECT * FROM '||P_TABLE_NAME ||'
              WHERE CREATETIME BETWEEN CURRENT_TIMESTAMP - 1 AND CURRENT_TIMESTAMP
              UNION ALL
              SELECT *
              FROM '||P_TABLE_NAME||'
              WHERE ( INSTANCEID,'||P_COLUMN_NAME||',CREATETIME) IN
                (SELECT INSTANCEID,'||P_COLUMN_NAME||',MAX(CREATETIME)
                FROM
                  (SELECT *
                  FROM ' ||P_TABLE_NAME|| '
                  WHERE TO_CHAR(CREATETIME,''MM'') = TO_CHAR(sysdate,''MM'')
                  )
                GROUP BY INSTANCEID,'||P_COLUMN_NAME||',TO_CHAR(CREATETIME,''DD-MON-RRRR HH24'')
                )
              UNION ALL
              SELECT *
              FROM ' ||P_TABLE_NAME|| '
              WHERE (INSTANCEID,'||P_COLUMN_NAME||',CREATETIME) IN
                (SELECT INSTANCEID,'||P_COLUMN_NAME||',MAX(CREATETIME)
                FROM ' ||P_TABLE_NAME|| '
                WHERE TO_CHAR(CREATETIME,''MM'') BETWEEN 1 AND TO_CHAR(ADD_MONTHS(LAST_DAY(SYSDATE),-1),''MM'')
                GROUP BY INSTANCEID,' ||P_COLUMN_NAME|| ',TO_CHAR(CREATETIME,''DD-MON-RRRR'')
                ))I
                WHERE I.' ||P_COLUMN_NAME|| ' = M.' ||P_COLUMN_NAME|| '
                AND I.CREATETIME = M.CREATETIME)');
           */



           COMMIT;

        EXECUTE IMMEDIATE 'ALTER TABLE '||P_TABLE_NAME|| ' ENABLE ROW MOVEMENT';

        EXECUTE IMMEDIATE 'ALTER TABLE '||P_TABLE_NAME|| ' SHRINK SPACE CASCADE';

        EXECUTE IMMEDIATE 'ALTER TABLE '||P_TABLE_NAME|| ' DISABLE ROW MOVEMENT';

        DBMS_OUTPUT.PUT_LINE(P_TABLE_NAME ||' Data processing End.');

    END;


	PROCEDURE PROC_KPI_DATA_PROCESS_METHOD3 (P_TABLE_NAME USER_TABLES.TABLE_NAME%TYPE,P_COLUMN_NAME1 VARCHAR2,P_COLUMN_NAME2 VARCHAR2)
	AS
	V_TAB_NM VARCHAR2(255);
	BEGIN

    IF P_TABLE_NAME = 'JVMTHREADINSTANCETABLE' THEN

     	EXECUTE IMMEDIATE 'TRUNCATE TABLE JVMTHREADINSTANCETABLE REUSE STORAGE';

	END IF;
	
	
	DBMS_OUTPUT.PUT_LINE(P_TABLE_NAME ||' Data processing Start...');

	EXECUTE IMMEDIATE ('truncate table tbl_kpi_m3_qfltr reuse storage');


        EXECUTE IMMEDIATE  ('INSERT INTO tbl_kpi_m3_qfltr
        SELECT *
        FROM
          (SELECT INSTANCEID,
            '||P_COLUMN_NAME1||',
            AVG('||P_COLUMN_NAME2||') '||P_COLUMN_NAME2||',
            MIN('||P_COLUMN_NAME2||') '||P_COLUMN_NAME2||'_MINVAL,
            MAX('||P_COLUMN_NAME2||') '||P_COLUMN_NAME2||'_MAXVAL,
            CREATETIME
          FROM '|| P_TABLE_NAME ||'
          WHERE CREATETIME BETWEEN CURRENT_TIMESTAMP - 1 AND CURRENT_TIMESTAMP
          GROUP BY INSTANCEID,'||P_COLUMN_NAME1||',CREATETIME)
        UNION ALL
        SELECT INSTANCEID,
          '||P_COLUMN_NAME1||',
          AVG('||P_COLUMN_NAME2||') '||P_COLUMN_NAME2||',
          MIN('||P_COLUMN_NAME2||') '||P_COLUMN_NAME2||'_MINVAL,
          MAX('||P_COLUMN_NAME2||') '||P_COLUMN_NAME2||'_MAXVAL,
          MAX(CREATETIME) CREATETIME
        FROM
          (SELECT *
          FROM '|| P_TABLE_NAME ||'
          WHERE TO_CHAR(CREATETIME,''MM'') = TO_CHAR(sysdate,''MM'')
          AND CREATETIME NOT BETWEEN CURRENT_TIMESTAMP - 1 AND CURRENT_TIMESTAMP)
        GROUP BY INSTANCEID,'||P_COLUMN_NAME1||'
        UNION ALL
        SELECT INSTANCEID,
          '||P_COLUMN_NAME1||',
          AVG('||P_COLUMN_NAME2||') '||P_COLUMN_NAME2||',
          MIN('||P_COLUMN_NAME2||') '||P_COLUMN_NAME2||'_MINVAL,
          MAX('||P_COLUMN_NAME2||') '||P_COLUMN_NAME2||'_MAXVAL,
          MAX(CREATETIME) CREATETIME
        FROM '|| P_TABLE_NAME ||'
        WHERE TO_CHAR(CREATETIME,''MM'') BETWEEN 1 AND TO_CHAR(ADD_MONTHS(LAST_DAY(SYSDATE),-1),''MM'')
        GROUP BY INSTANCEID,'||P_COLUMN_NAME1||'');

       --EXECUTE IMMEDIATE ('create index inx_tbl_kpi_m3_qfltr on  tbl_kpi_m3_qfltr(INSTANCEID,'||P_COLUMN_NAME1||',CREATETIME)');

	    COMMIT;
	   
		 EXECUTE IMMEDIATE ('DELETE FROM tbl_kpi_m3_qfltr M
		WHERE m.ROWID NOT IN
		(SELECT MIN(ROWID) MIN_ROWID FROM tbl_kpi_m3_qfltr I
		 WHERE I.INSTANCEID = M.INSTANCEID
		 AND I.P_COLUMN_NAME1 = M.P_COLUMN_NAME1
		 AND I.CREATETIME = M.CREATETIME
		 GROUP BY I.INSTANCEID,I.P_COLUMN_NAME1,I.CREATETIME)');

		 COMMIT;
		 
         EXECUTE IMMEDIATE ('UPDATE '|| P_TABLE_NAME ||' K
        SET K.'||P_COLUMN_NAME2||' = (SELECT I.P_COLUMN_NAME2
        FROM tbl_kpi_m3_qfltr I
        WHERE I.INSTANCEID = K.INSTANCEID
        AND I.P_COLUMN_NAME1 = K.'||P_COLUMN_NAME1||'
        AND I.CREATETIME = K.CREATETIME),
        K.'||P_COLUMN_NAME2||'_MINVAL = (SELECT I.P_COLUMN_NAME2_MINVAL
        FROM tbl_kpi_m3_qfltr I
        WHERE I.INSTANCEID = K.INSTANCEID
        AND I.P_COLUMN_NAME1 = K.'||P_COLUMN_NAME1||'
        AND I.CREATETIME = K.CREATETIME),
        K.'||P_COLUMN_NAME2||'_MAXVAL = (SELECT I.P_COLUMN_NAME2_MAXVAL
        FROM tbl_kpi_m3_qfltr I
        WHERE I.INSTANCEID = K.INSTANCEID
        AND I.P_COLUMN_NAME1 = K.'||P_COLUMN_NAME1||'
        AND I.CREATETIME = K.CREATETIME)
        WHERE EXISTS
        (SELECT * FROM tbl_kpi_m3_qfltr I
         WHERE I.INSTANCEID = K.INSTANCEID
         AND I.P_COLUMN_NAME1 = K.'||P_COLUMN_NAME1||'
         AND I.CREATETIME = K.CREATETIME
        )');

		COMMIT;
		
        EXECUTE IMMEDIATE ('DELETE FROM '|| P_TABLE_NAME ||' K
        WHERE NOT EXISTS
        (SELECT * FROM tbl_kpi_m3_qfltr I
        WHERE I.INSTANCEID = K.INSTANCEID
        AND I.P_COLUMN_NAME1 = K.'||P_COLUMN_NAME1||'
        AND I.CREATETIME = K.CREATETIME)');

        COMMIT;

        EXECUTE IMMEDIATE 'ALTER TABLE '||P_TABLE_NAME|| ' ENABLE ROW MOVEMENT';

        EXECUTE IMMEDIATE 'ALTER TABLE '||P_TABLE_NAME|| ' SHRINK SPACE CASCADE';

        EXECUTE IMMEDIATE 'ALTER TABLE '||P_TABLE_NAME|| ' DISABLE ROW MOVEMENT';

        DBMS_OUTPUT.PUT_LINE(P_TABLE_NAME ||' Data processing End.');

  END;
  PROCEDURE PROC_KPI_DATA_PROCESS_METHOD4(P_TABLE_NAME USER_TABLES.TABLE_NAME%TYPE,P_COLUMN_NAME1 VARCHAR2,P_COLUMN_NAME2 VARCHAR2)
	AS
    V_TAB_NM VARCHAR2(255);
	BEGIN
	
	    IF P_TABLE_NAME = 'JVMMEMORY' THEN

     	 EXECUTE IMMEDIATE 'TRUNCATE TABLE JVMMEMORY REUSE STORAGE';

	    END IF;

	DBMS_OUTPUT.PUT_LINE(P_TABLE_NAME ||' Data processing Start...');

    EXECUTE IMMEDIATE ('truncate table tbl_kpi_m4_qfltr reuse storage');


        EXECUTE IMMEDIATE  ('INSERT INTO tbl_kpi_m4_qfltr
        SELECT *
        FROM
          (SELECT INSTANCEID,
            AVG('||P_COLUMN_NAME1||') '||P_COLUMN_NAME1||',
            MIN('||P_COLUMN_NAME1||') '||P_COLUMN_NAME1||'_MINVAL,
            MAX('||P_COLUMN_NAME1||') '||P_COLUMN_NAME1||'_MAXVAL,
            AVG('||P_COLUMN_NAME2||') '||P_COLUMN_NAME2||',
            MIN('||P_COLUMN_NAME2||') '||P_COLUMN_NAME2||'_MINVAL,
            MAX('||P_COLUMN_NAME2||') '||P_COLUMN_NAME2||'_MAXVAL,
            CREATETIME
          FROM '|| P_TABLE_NAME ||'
          WHERE CREATETIME BETWEEN CURRENT_TIMESTAMP - 1 AND CURRENT_TIMESTAMP
          GROUP BY INSTANCEID,CREATETIME)
        UNION ALL
        SELECT INSTANCEID,
          AVG('||P_COLUMN_NAME1||') '||P_COLUMN_NAME1||',
          MIN('||P_COLUMN_NAME1||') '||P_COLUMN_NAME1||'_MINVAL,
          MAX('||P_COLUMN_NAME1||') '||P_COLUMN_NAME1||'_MAXVAL,
          AVG('||P_COLUMN_NAME2||') '||P_COLUMN_NAME2||',
          MIN('||P_COLUMN_NAME2||') '||P_COLUMN_NAME2||'_MINVAL,
          MAX('||P_COLUMN_NAME2||') '||P_COLUMN_NAME2||'_MAXVAL,
          MAX(CREATETIME) CREATETIME
        FROM
          (SELECT *
          FROM '|| P_TABLE_NAME ||'
          WHERE TO_CHAR(CREATETIME,''MM'') = TO_CHAR(sysdate,''MM'')
          AND CREATETIME NOT BETWEEN CURRENT_TIMESTAMP - 1 AND CURRENT_TIMESTAMP)
        GROUP BY INSTANCEID,CREATETIME
        UNION ALL
        SELECT INSTANCEID,
          AVG('||P_COLUMN_NAME1||') '||P_COLUMN_NAME1||',
          MIN('||P_COLUMN_NAME1||') '||P_COLUMN_NAME1||'_MINVAL,
          MAX('||P_COLUMN_NAME1||') '||P_COLUMN_NAME1||'_MAXVAL,
          AVG('||P_COLUMN_NAME2||') '||P_COLUMN_NAME2||',
          MIN('||P_COLUMN_NAME2||') '||P_COLUMN_NAME2||'_MINVAL,
          MAX('||P_COLUMN_NAME2||') '||P_COLUMN_NAME2||'_MAXVAL,
          MAX(CREATETIME) CREATETIME
        FROM '|| P_TABLE_NAME ||'
        WHERE TO_CHAR(CREATETIME,''MM'') BETWEEN 1 AND TO_CHAR(ADD_MONTHS(LAST_DAY(SYSDATE),-1),''MM'')
        GROUP BY INSTANCEID,CREATETIME');
       
       COMMIT;

         EXECUTE IMMEDIATE ('UPDATE '|| P_TABLE_NAME ||' K
        SET K.'||P_COLUMN_NAME1||' = (SELECT I.P_COLUMN_NAME1
        FROM tbl_kpi_m4_qfltr I
        WHERE I.INSTANCEID = K.INSTANCEID
        AND I.CREATETIME = K.CREATETIME),
        K.'||P_COLUMN_NAME1||'_MINVAL = (SELECT I.P_COLUMN_NAME1_MINVAL
        FROM tbl_kpi_m4_qfltr I
        WHERE I.INSTANCEID = K.INSTANCEID
        AND I.CREATETIME = K.CREATETIME),
        K.'||P_COLUMN_NAME1||'_MAXVAL = (SELECT I.P_COLUMN_NAME1_MAXVAL
        FROM tbl_kpi_m4_qfltr I
        WHERE I.INSTANCEID = K.INSTANCEID
        AND I.CREATETIME = K.CREATETIME),
        K.'||P_COLUMN_NAME2||' = (SELECT I.P_COLUMN_NAME2
        FROM tbl_kpi_m4_qfltr I
        WHERE I.INSTANCEID = K.INSTANCEID
        AND I.CREATETIME = K.CREATETIME),
        K.'||P_COLUMN_NAME2||'_MINVAL = (SELECT I.P_COLUMN_NAME2_MINVAL
        FROM tbl_kpi_m4_qfltr I
        WHERE I.INSTANCEID = K.INSTANCEID
        AND I.CREATETIME = K.CREATETIME),
        K.'||P_COLUMN_NAME2||'_MAXVAL = (SELECT I.P_COLUMN_NAME2_MAXVAL
        FROM tbl_kpi_m4_qfltr I
        WHERE I.INSTANCEID = K.INSTANCEID
        AND I.CREATETIME = K.CREATETIME)
        WHERE EXISTS
        (SELECT * FROM tbl_kpi_m4_qfltr I
         WHERE I.INSTANCEID = K.INSTANCEID
         AND I.CREATETIME = K.CREATETIME
        )');
       
       COMMIT;
       
        EXECUTE IMMEDIATE ('DELETE FROM '|| P_TABLE_NAME ||' K
        WHERE NOT EXISTS
        (SELECT * FROM tbl_kpi_m4_qfltr I
        WHERE I.INSTANCEID = K.INSTANCEID
         AND I.CREATETIME = K.CREATETIME)');

        COMMIT;

        EXECUTE IMMEDIATE 'ALTER TABLE '||P_TABLE_NAME|| ' ENABLE ROW MOVEMENT';

        EXECUTE IMMEDIATE 'ALTER TABLE '||P_TABLE_NAME|| ' SHRINK SPACE CASCADE';

        EXECUTE IMMEDIATE 'ALTER TABLE '||P_TABLE_NAME|| ' DISABLE ROW MOVEMENT';

        DBMS_OUTPUT.PUT_LINE(P_TABLE_NAME ||' Data processing End.');


  END;
      PROCEDURE PROC_KPI_DATA_PROCESS_MAIN
        AS
        BEGIN

          /*  WRAPPER */

      BEGIN
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD1('JVMTHREADING');

      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD1('RADIUSACCCLIENT');

      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD1('RADIUSACCSERV');

      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD2('RADIUSACCCLIENTTABLE','RADIUSACCCLIENTINDEX');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD2('RADIUSACCSERVERTABLE','RADIUSACCSERVERINDEX');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD2('JVMMEMMANAGERTABLE','JVMMEMMANAGERINDEX');

      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD3('JVMMEMPOOLTABLE','JVMMEMPOOLNAME','JVMSYSTEMLOADAVERAGE');
      
      --PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD3('JVMTHREADINSTANCETABLE','JVMTHREADINSTID','JVMTHREADINSTCPUTIMENS');

      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD4('JVMMEMORY','JVMMEMORYHEAPUSED','JVMMEMORYNONHEAPUSED');


      --Others
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD1('CHARGINGSERVMIBOBJECTS');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD1('DBPLOCALSTATS');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD1('DBPPERPEERINFOTABLE');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD1('DCCAPERPEERSTATSTABLE');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD1('IPPOOLCLIENTMIBOBJECTS');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD1('IPPOOLSERVMIBOBJECTS');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD1('MEMORY');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD1('RADIUSAUTHCLIENT');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD1('RADIUSAUTHSERV');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD1('RADIUSDYNAUTHCLIENTSCALARS');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD1('RADIUSDYNAUTHSERVERSCALARS');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD1('SYSTEMSTATS');


      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD2('RADIUSAUTHCLIENTTABLE','RADIUSAUTHCLIENTINDEX');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD2('RADIUSAUTHSERVERTABLE','RADIUSAUTHSERVERINDEX');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD2('RADIUSDYNAUTHCLIENTTABLE','RADIUSDYNAUTHCLIENTINDEX');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD2('RADIUSDYNAUTHSERVERTABLE','RADIUSDYNAUTHSERVERINDEX');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD2('CHARGINGCLIENTSTATSTABLE','CHARGINGCLIENTINDEX');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD2('CHARGINGSERVERSTATISTICSTABLE','CHARGINGSERVERINDEX');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD2('DBPREALMMESSAGEROUTETABLES','DBPREALMMESSAGEROUTEINDEX');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD2('IPPOOLAAACLIENTSTATISTICSTABLE','IPPOOLAAACLIENTINDEX');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD2('IPPOOLNASCLIENTSTATISTICSTABLE','IPPOOLNASCLIENTINDEX');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD2('IPPOOLSERVERSTATISTICSTABLE','IPPOOLSERVERINDEX');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD2('LOCALSESSIONMANAGERSTATSTABLE','SMINDEX');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD2('LATABLE','LAINDEX');
      PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_METHOD2('DSKTABLE','DSKINDEX');

    Exception
           when OTHERS then
           dbms_output.put_line(SQLCODE||SQLERRM);
           null;
    END;

    END;

END PKG_ELITECSM_KPI_HIST_TRN;
/
-- EliteKPI Database Maintainance Schedule Job --

BEGIN
DBMS_SCHEDULER.CREATE_JOB (
   JOB_NAME           =>  'JOB_PKG_ELITECSM_KPI_HIST_TRN',
   JOB_TYPE           =>  'STORED_PROCEDURE',
   JOB_ACTION         =>  'PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_MAIN',
   START_DATE         =>  SYSTIMESTAMP,
   REPEAT_INTERVAL    =>  'FREQ=DAILY; BYHOUR=03; BYMINUTE=1;',   
   END_DATE           =>   NULL,
    ENABLED           =>   TRUE,
   COMMENTS           =>  'JOB_PKG_ELITECSM_KPI_HIST_TRN....');
END;
/

-- EliteKPI Database OAM Commands

---#Manual Execution of EliteKPI Database Maintainance Job
prompt 'SET SERVEROUTPUT ON';

prompt  'EXEC PKG_ELITECSM_KPI_HIST_TRN.PROC_KPI_DATA_PROCESS_MAIN';

---#Check the Next execution time and Run count and Failure count
prompt 'SELECT JOB_NAME,NEXT_RUN_DATE,LAST_RUN_DURATION,MAX_RUN_DURATION,RUN_COUNT,FAILURE_COUNT,JOB_ACTION FROM  USER_SCHEDULER_JOBS';
