-- =====================
-- TABLE  - PACKAGEDEFINITION
-- =====================


CREATE TABLE PACKAGEDEFINITION
(
		PACKAGEID 	NUMBER(6)	PRIMARY KEY,
		PACKAGENAME 	VARCHAR2(50) 	NOT NULL,
		PACKAGETYPE 	VARCHAR2(50) 	NOT NULL,
		UNITTYPE 	VARCHAR2(10) 	NOT NULL,
		MINCAP 		NUMBER(15,2),
		MAXCAP 		NUMBER(15,2)
);

-- =====================
-- TABLE :  PREFIXGROUPDEFINITION
-- =====================

CREATE TABLE PREFIXGROUPDEFINITION
(
		PREFIXGROUPNAME 	VARCHAR2(50) 		NOT NULL,
		PREFIXGROUPNUMBER 	NUMBER(25) 		PRIMARY KEY
);

-- =====================
-- TABLE: SLABDEFINITION
-- =====================

CREATE TABLE SLABDEFINITION
(
         PACKAGEID           		NUMBER(6) 	REFERENCES 	PACKAGEDEFINITION(PACKAGEID) 	PRIMARY KEY,
         UNIT1                		NUMBER(6),
         UNIT2                 		NUMBER(6),
         UNIT3                		NUMBER(6)
);

-- =====================
--TABLE :  RATEDEFINITION
-- =====================

 CREATE TABLE RATEDEFINITION
 (
       RATEDEFINITIONID   NUMBER(6) PRIMARY KEY,
       PACKAGEID  NUMBER(6)    NOT NULL,
       SERVICETYPE  VARCHAR2(50)  NOT NULL,
       PREFIXGROUP  VARCHAR2(50)  NOT NULL,
       CUSTOMERTYPE VARCHAR2(50)  NOT NULL,
       EVENTTYPE     VARCHAR2(50) NOT NULL,
       VERSION   VARCHAR2(50)  NOT NULL,
       RATE  NUMBER(20,2)    NOT NULL
  );


-- =====================
--TABLE: CUSTOMERACCOUNT
-- =====================

CREATE TABLE CUSTOMERACCOUNT
( 
		CUSTOMERNAME  		VARCHAR2(100)   	NOT NULL,
		CUSTOMERIDENTIFIER    	VARCHAR2(100)    PRIMARY KEY,
		SERVICETYPE   		VARCHAR2(50)    	NOT NULL,
		PACKAGEID    		NUMBER(6)  	NOT NULL 	REFERENCES PACKAGEDEFINITION(PACKAGEID),
		CUSTOMERTYPE  		VARCHAR2(50)    	NOT NULL,
		CUSTOMERSUBTYPE	VARCHAR2(50) 	NOT NULL,
		TOTALUSAGE     		NUMBER,
		VERSION        		VARCHAR2(50),
		PASSWORD		VARCHAR2(50)	NOT NULL,
		KEYQUESTION		VARCHAR2(256),
		KEYANSWER		VARCHAR2(256),
		EMAILADDRESS		VARCHAR2(50),
		MOBILEPHONE		VARCHAR2(20),
		ADDRESSLINE1		VARCHAR2(100)	NOT NULL,
		ADDRESSLINE2		VARCHAR2(100),		
		POSTALCODE		VARCHAR2(10),
		HOMEPHONE		VARCHAR2(20),
		CITY			VARCHAR2(100),
		STATE			VARCHAR2(100),
		COUNTRY		VARCHAR2(100),
		CREATEDDATE		DATE,
		ACCOUNTSTATUS		VARCHAR2(20),
		ENCRYPTIONTYPE         NUMBER(1),
		CUSTOMERREJECTITEM     VARCHAR2(4000 BYTE),
		CUSTOMERCHECKITEM      VARCHAR2(4000 BYTE),
		CUSTOMERREPLYITEM      VARCHAR2(4000 BYTE),
		CONCURRENTLOGINPOLICY  VARCHAR2(50 BYTE),
		ACCESSPOLICY           VARCHAR2(50 BYTE),
		RADIUSPOLICY           VARCHAR2(50 BYTE),
		CUSTOMERSERVICES       VARCHAR2(1000 BYTE)
);



-- =====================
-- TABLE: CUSTOMERBALANCE
-- =====================

CREATE TABLE CUSTOMERBALANCE
(
		CUSTOMERNAME 	             VARCHAR2(100),
		CUSTOMERIDENTIFIER 	VARCHAR2(50) 	REFERENCES CUSTOMERACCOUNT(CUSTOMERIDENTIFIER),
		BALANCE			NUMBER(24,6) 	NOT NULL
);



CREATE TABLE CDRCHARGETABLE 
(
		CDRID 			NUMBER	PRIMARY KEY,
		CHARGE 			NUMBER	NOT NULL,
		CHARGEDDATE 		DATE,
		CUSTOMERNAME 		VARCHAR2(100),
		CUSTOMERIDENTIFIER 	VARCHAR2(100) 	NOT NULL REFERENCES CUSTOMERACCOUNT(CUSTOMERIDENTIFIER),
		SESSIONTIME 		NUMBER ,
		ACCTINPUTOCTETS 	NUMBER,
		ACCTOUTPUTOCTETS 	NUMBER,
		CALLEDSTATIONID 	NUMBER,
		VOLUME  		NUMBER,		
		CALLSTART 		TIMESTAMP(0),
		CALLEND 		TIMESTAMP(0),
		EVENTTYPE 		VARCHAR2(50),
		SESSIONID 		VARCHAR2(100)		NOT NULL,
		SERVICETYPE 		VARCHAR2(25) 		NOT NULL
);



CREATE OR REPLACE VIEW VW_CUSTOMERACCOUNT AS 
SELECT CUSTOMERIDENTIFIER AS USER_IDENTITY,
PASSWORD AS PASSWORD,
ACCOUNTSTATUS AS ACCOUNTSTATUS,
CUSTOMERNAME AS USERNAME,
CUSTOMERTYPE AS CUSTOMERTYPE,
ENCRYPTIONTYPE AS ENCRYPTIONTYPE,
CUSTOMERREJECTITEM AS CUSTOMERREJECTITEM,    
CUSTOMERCHECKITEM AS CUSTOMERCHECKITEM,  
CUSTOMERREPLYITEM AS CUSTOMERREPLYITEM,   
CONCURRENTLOGINPOLICY AS CONCURRENTLOGINPOLICY, 
ACCESSPOLICY AS ACCESSPOLICY,
RADIUSPOLICY AS RADIUSPOLICY,       
CUSTOMERSERVICES AS CUSTOMERSERVICES      
FROM CUSTOMERACCOUNT;

-- =====================
-- Constraints
-- =====================

ALTER TABLE RATEDEFINITION ADD CONSTRAINT UNQ_RATE_DEF UNIQUE (PACKAGEID, SERVICETYPE, PREFIXGROUP, CUSTOMERTYPE, EVENTTYPE, VERSION);

ALTER TABLE PACKAGEDEFINITION ADD CONSTRAINT UNQ_PACKAGE_NAME UNIQUE(PACKAGENAME);

-- =====================
-- Sequences
-- ======================


-- PACKAGEDEFINITION

CREATE SEQUENCE SEQ_PACKAGEDEFINITION
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;


CREATE SEQUENCE SEQ_CDRCHARGETABLE
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE SEQ_RATEDEFINITION
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

 
 -- ================
 --  Commit
 -- ================
 
 commit;