spool ELITEAAA_DBC_PARTITION_TBLRADIUSCUSTOMER.log

prompt -------Product Team DBC Enhanacement----------------------

prompt -------create tablespaces for TBLRADIUSCUSTOMER---------

prompt Enter the datafile location for tablespace of ELITEAAA - TABLE PARTITIONING OF TBLRADIUSCUSTOMER ===>

DEFINE db_datafile="&&dbf_storage_directory"
prompt &db_datafile
                                                                                    
CREATE TABLESPACE TBS_TBLRADIUSCUSTOMER01 DATAFILE '&&db_datafile/TBS_TBLRADIUSCUSTOMER01.dbf' size 100M AUTOEXTEND ON NEXT 25M;
CREATE TABLESPACE TBS_TBLRADIUSCUSTOMER02 DATAFILE '&&db_datafile/TBS_TBLRADIUSCUSTOMER02.dbf' size 100M AUTOEXTEND ON NEXT 25M;
CREATE TABLESPACE TBS_TBLRADIUSCUSTOMER03 DATAFILE '&&db_datafile/TBS_TBLRADIUSCUSTOMER03.dbf' size 100M AUTOEXTEND ON NEXT 25M;
CREATE TABLESPACE TBS_TBLRADIUSCUSTOMER04 DATAFILE '&&db_datafile/TBS_TBLRADIUSCUSTOMER04.dbf' size 100M AUTOEXTEND ON NEXT 25M;
CREATE TABLESPACE TBS_TBLRADIUSCUSTOMER05 DATAFILE '&&db_datafile/TBS_TBLRADIUSCUSTOMER05.dbf' size 100M AUTOEXTEND ON NEXT 25M;
CREATE TABLESPACE TBS_TBLRADIUSCUSTOMER06 DATAFILE '&&db_datafile/TBS_TBLRADIUSCUSTOMER06.dbf' size 100M AUTOEXTEND ON NEXT 25M;
CREATE TABLESPACE TBS_TBLRADIUSCUSTOMER07 DATAFILE '&&db_datafile/TBS_TBLRADIUSCUSTOMER07.dbf' size 100M AUTOEXTEND ON NEXT 25M;
CREATE TABLESPACE TBS_TBLRADIUSCUSTOMER08 DATAFILE '&&db_datafile/TBS_TBLRADIUSCUSTOMER08.dbf' size 100M AUTOEXTEND ON NEXT 25M;

--Create tablespaces for TBLRADIUSCUSTOMER Indexes                                                                                    
                                                                                                                                         
create tablespace TBS_IDXRADIUSCUSTOMER01 datafile '&&db_datafile/TBS_IDXRADIUSCUSTOMER01.dbf' size 100M AUTOEXTEND ON NEXT 25M; 
create tablespace TBS_IDXRADIUSCUSTOMER02 datafile '&&db_datafile/TBS_IDXRADIUSCUSTOMER02.dbf' size 100M AUTOEXTEND ON NEXT 25M; 
create tablespace TBS_IDXRADIUSCUSTOMER03 datafile '&&db_datafile/TBS_IDXRADIUSCUSTOMER03.dbf' size 100M AUTOEXTEND ON NEXT 25M; 
create tablespace TBS_IDXRADIUSCUSTOMER04 datafile '&&db_datafile/TBS_IDXRADIUSCUSTOMER04.dbf' size 100M AUTOEXTEND ON NEXT 25M; 
create tablespace TBS_IDXRADIUSCUSTOMER05 datafile '&&db_datafile/TBS_IDXRADIUSCUSTOMER05.dbf' size 100M AUTOEXTEND ON NEXT 25M; 
create tablespace TBS_IDXRADIUSCUSTOMER06 datafile '&&db_datafile/TBS_IDXRADIUSCUSTOMER06.dbf' size 100M AUTOEXTEND ON NEXT 25M; 
create tablespace TBS_IDXRADIUSCUSTOMER07 datafile '&&db_datafile/TBS_IDXRADIUSCUSTOMER07.dbf' size 100M AUTOEXTEND ON NEXT 25M; 
create tablespace TBS_IDXRADIUSCUSTOMER08 datafile '&&db_datafile/TBS_IDXRADIUSCUSTOMER08.dbf' size 100M AUTOEXTEND ON NEXT 25M; 

prompt Enter the username of ELITEAAA ===>
connect &&username/&&password@&&NET_STR

set long 10000
set pagesize 0
select dbms_metadata.get_dependent_ddl('INDEX','TBLRADIUSCUSTOMER') from duAL;

SELECT DBMS_METADATA.GET_DDL('TABLE','TBLRADIUSCUSTOMER') FROM DUAL;

RENAME TBLRADIUSCUSTOMER TO OLD_TBLRADIUSCUSTOMER;

CREATE TABLE TBLRADIUSCUSTOMER
( ID                     NUMERIC,
  USERNAME               VARCHAR(255),
  PASSWORD               VARCHAR(255),
  ENCRYPTIONTYPE         NUMERIC(3),
  CUSTOMERSTATUS         VARCHAR(10),
  EXPIRYDATE            TIMESTAMP,
  CUSTOMERREJECTITEM     VARCHAR(4000),
  CUSTOMERCHECKITEM      VARCHAR(4000),
  CUSTOMERREPLYITEM      VARCHAR(4000),
  CREDITLIMIT            NUMERIC,
  CONCURRENTLOGINPOLICY  VARCHAR(50),
  ACCESSPOLICY           VARCHAR(50),
  RADIUSPOLICY		 VARCHAR(1000),
  DIAMETERPOLICY	 VARCHAR(1000),
  ADDITIONALPOLICY	    VARCHAR(1000), 
  IPPOOLNAME             VARCHAR(50),
  PARAM1                 VARCHAR(255),
  PARAM2                 VARCHAR(255),
  PARAM3                 VARCHAR(255),
  PARAM4                 VARCHAR(255),
  PARAM5                 VARCHAR(255),
  GROUPNAME              VARCHAR(60),
  CUSTOMERALTEMAILID     VARCHAR(50),
  CUSTOMERSERVICES       VARCHAR(1000),
  CUSTOMERTYPE           VARCHAR(50),
  PASSWORDCHECK          VARCHAR(50),
  CALLEDSTATIONID        VARCHAR(100),
  CALLINGSTATIONID       VARCHAR(100),
  USER_IDENTITY          VARCHAR(255) NOT NULL,
  CUI		         VARCHAR(50),
  HOTLINEPOLICY          VARCHAR(1000),
  GRACEPERIOD            VARCHAR(1000),
  CALLBACKID             VARCHAR(100),
  BANDWIDTH              NUMERIC(20),
  DYNAMICCHECKITEM       VARCHAR(4000),
  MACVALIDATION		 	VARCHAR(50),
  IMSI 					VARCHAR(100),
  MEID  				VARCHAR(100),
  MSISDN  				VARCHAR(100),
  MDN  					VARCHAR(100),
  IMEI 					VARCHAR(100),
  DEVICEVENDOR          VARCHAR(255),
  DEVICENAME            VARCHAR(255),
  DEVICEPORT            VARCHAR(255),
  GEOLOCATION           VARCHAR(255),
  DEVICEVLAN            VARCHAR(255),
  FRAMEDIPV4ADDRESS 	VARCHAR(255),
  FRAMEDIPV6PREFIX      VARCHAR(255),
  FRAMEDPOOL            VARCHAR(255),
  RADIUSPOLICYGROUP     VARCHAR(255),
  DIAMETERPOLICYGROUP   VARCHAR(255),
  CREATEDATE 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LASTMODIFIEDDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PKPRT_RADIUSCUSTOMER_U01 PRIMARY KEY (USER_IDENTITY)
)                                                        
PARTITION BY HASH(USER_IDENTITY)                                         
( PARTITION PART_TBLRADIUSCUSTOMER01   TABLESPACE TBS_TBLRADIUSCUSTOMER01,   
  PARTITION PART_TBLRADIUSCUSTOMER02   TABLESPACE TBS_TBLRADIUSCUSTOMER02,
  PARTITION PART_TBLRADIUSCUSTOMER03   TABLESPACE TBS_TBLRADIUSCUSTOMER03,
  PARTITION PART_TBLRADIUSCUSTOMER04   TABLESPACE TBS_TBLRADIUSCUSTOMER04, 
  PARTITION PART_TBLRADIUSCUSTOMER05   TABLESPACE TBS_TBLRADIUSCUSTOMER05,
  PARTITION PART_TBLRADIUSCUSTOMER06   TABLESPACE TBS_TBLRADIUSCUSTOMER06,   
  PARTITION PART_TBLRADIUSCUSTOMER07   TABLESPACE TBS_TBLRADIUSCUSTOMER07,
  PARTITION PART_TBLRADIUSCUSTOMER08   TABLESPACE TBS_TBLRADIUSCUSTOMER08   
)NOLOGGING;   

--Disable Primary Key

ALTER TABLE TBLRADIUSCUSTOMER DISABLE PRIMARY KEY;

CREATE UNIQUE INDEX PKPRT_RADIUSCUSTOMER_U01 ON TBLRADIUSCUSTOMER(USER_IDENTITY)   
  GLOBAL PARTITION BY HASH (USER_IDENTITY)                                               
(PARTITION PRT_IDXRADIUSCUSTOMER01    TABLESPACE TBS_IDXRADIUSCUSTOMER01 ,                 
 PARTITION PRT_IDXRADIUSCUSTOMER02    TABLESPACE TBS_IDXRADIUSCUSTOMER02 ,                 
 PARTITION PRT_IDXRADIUSCUSTOMER03    TABLESPACE TBS_IDXRADIUSCUSTOMER03 ,                 
 PARTITION PRT_IDXRADIUSCUSTOMER04    TABLESPACE TBS_IDXRADIUSCUSTOMER04 ,                 
 PARTITION PRT_IDXRADIUSCUSTOMER05    TABLESPACE TBS_IDXRADIUSCUSTOMER05 ,                 
 PARTITION PRT_IDXRADIUSCUSTOMER06    TABLESPACE TBS_IDXRADIUSCUSTOMER06 ,                 
 PARTITION PRT_IDXRADIUSCUSTOMER07    TABLESPACE TBS_IDXRADIUSCUSTOMER07 ,                 
 PARTITION PRT_IDXRADIUSCUSTOMER08    TABLESPACE TBS_IDXRADIUSCUSTOMER08 )                 
 NOLOGGING;                                                                      

 ALTER TABLE TBLRADIUSCUSTOMER ENABLE PRIMARY KEY;
 
 ALTER TABLE TBLRADIUSCUSTOMER INITRANS 169;

 ALTER INDEX PKPRT_RADIUSCUSTOMER_U01 INITRANS 169;

 ALTER SEQUENCE SEQ_RADIUSCUSTOMER CACHE 4000;
                                                        
set long 10000
set pagesize 0
select dbms_metadata.get_dependent_ddl('INDEX','TBLRADIUSCUSTOMER') from duAL;

SELECT DBMS_METADATA.GET_DDL('TABLE','TBLRADIUSCUSTOMER') FROM DUAL;


spool off;
exit;
