package com.elitecore.netvertexsm.util.constants;

public enum CrestelKeyRequestConstants {
		
	SERVICE_NAME("SERVICE-NAME"),
	USERNAME("USERNAME"),
	REQUEST_TYPE("REQUEST-TYPE"),
	REQUESTED_ACTION("REQUESTED-ACTION"),
	AMOUNT("AMOUNT"),	
	SESSION_TIME("SESSION-TIME"),
	ACCT_SESSION_ID("ACCT-SESSION-ID"),
	SESSION_CONNECT_TIME("SESSION-CONNECT-TIME"),
	SESSION_DISCONNECT_TIME("SESSION-DISCONNECT-TIME"),
	RESERVATIONID("RESERVATIONID"),
	SESSION_DOWNLOAD_GIGA_WORDS("SESSION-DOWNLOAD-GIGA-WORDS"),
	SESSION_UPLOAD_GIGA_WORDS("SESSION-UPLOAD-GIGA-WORDS"),
	SESSION_DOWNLOAD_DATA_TRANSFER("SESSION-DOWNLOAD-DATA-TRANSFER"),
	SESSION_UPLOAD_DATA_TRANSFER("SESSION-UPLOAD-DATA-TRANSFER"),
	OPERATION_TYPE("OPERATION-TYPE"),
	CALLED_STATION_ID("CALLED-STATION-ID"),
	CALLING_STATION_ID("CALLING-STATION-ID"),
	CALL_DIRECTION("CALL-DIRECTION"),
	CONTENT_ID("CONTENT-ID"),
	CONTENT_CATEGORY("CONTENT-CATEGORY"),
	CONTENT_NAME("CONTENT-NAME"),
	EGRESS_TRUNK_GROUP_NAME("EGRESS-TRUNK-GROUP-NAME"),
	SUBSERVICE_NAME("SUBSERVICE-NAME"),
	SOURCEUNITNAME("SOURCEUNITNAME"),
	CLIENT_IP_ADDRESS("CLIENT-IP-ADDRESS");
	
	
	public final String val;
	
	private CrestelKeyRequestConstants(String val) {
		this.val = val;
	}
		
	public String getVal() {
		return val;
	}

}
