/*
 * Open API Goibibo API Program
 * Open API Spec of Goibibo APIs. You can find more about Open API Spec here (https://openapis.org/)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@goibibo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.brs.searchservice.models.model;

import java.util.Objects;
import com.brs.searchservice.models.model.Ratings;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * UgcReview
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-25T08:25:14.822+05:30")
public class UgcReview {
  @JsonProperty("ratings")
  private Ratings ratings = null;

  @JsonProperty("reviewCount")
  private BigDecimal reviewCount = null;

  @JsonProperty("posReviewCount")
  private BigDecimal posReviewCount = null;

  @JsonProperty("criReviewCount")
  private BigDecimal criReviewCount = null;

  @JsonProperty("imgReviewCount")
  private BigDecimal imgReviewCount = null;

  @JsonProperty("totalRating")
  private BigDecimal totalRating = null;

  @JsonProperty("approvedImageCount")
  private BigDecimal approvedImageCount = null;

  @JsonProperty("id")
  private String id = null;

  public UgcReview ratings(Ratings ratings) {
    this.ratings = ratings;
    return this;
  }

   /**
   * Get ratings
   * @return ratings
  **/
  @ApiModelProperty(required = true, value = "")
  public Ratings getRatings() {
    return ratings;
  }

  public void setRatings(Ratings ratings) {
    this.ratings = ratings;
  }

  public UgcReview reviewCount(BigDecimal reviewCount) {
    this.reviewCount = reviewCount;
    return this;
  }

   /**
   * Get reviewCount
   * @return reviewCount
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getReviewCount() {
    return reviewCount;
  }

  public void setReviewCount(BigDecimal reviewCount) {
    this.reviewCount = reviewCount;
  }

  public UgcReview posReviewCount(BigDecimal posReviewCount) {
    this.posReviewCount = posReviewCount;
    return this;
  }

   /**
   * Get posReviewCount
   * @return posReviewCount
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getPosReviewCount() {
    return posReviewCount;
  }

  public void setPosReviewCount(BigDecimal posReviewCount) {
    this.posReviewCount = posReviewCount;
  }

  public UgcReview criReviewCount(BigDecimal criReviewCount) {
    this.criReviewCount = criReviewCount;
    return this;
  }

   /**
   * Get criReviewCount
   * @return criReviewCount
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getCriReviewCount() {
    return criReviewCount;
  }

  public void setCriReviewCount(BigDecimal criReviewCount) {
    this.criReviewCount = criReviewCount;
  }

  public UgcReview imgReviewCount(BigDecimal imgReviewCount) {
    this.imgReviewCount = imgReviewCount;
    return this;
  }

   /**
   * Get imgReviewCount
   * @return imgReviewCount
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getImgReviewCount() {
    return imgReviewCount;
  }

  public void setImgReviewCount(BigDecimal imgReviewCount) {
    this.imgReviewCount = imgReviewCount;
  }

  public UgcReview totalRating(BigDecimal totalRating) {
    this.totalRating = totalRating;
    return this;
  }

   /**
   * Get totalRating
   * @return totalRating
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getTotalRating() {
    return totalRating;
  }

  public void setTotalRating(BigDecimal totalRating) {
    this.totalRating = totalRating;
  }

  public UgcReview approvedImageCount(BigDecimal approvedImageCount) {
    this.approvedImageCount = approvedImageCount;
    return this;
  }

   /**
   * Get approvedImageCount
   * @return approvedImageCount
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getApprovedImageCount() {
    return approvedImageCount;
  }

  public void setApprovedImageCount(BigDecimal approvedImageCount) {
    this.approvedImageCount = approvedImageCount;
  }

  public UgcReview id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UgcReview ugcReview = (UgcReview) o;
    return Objects.equals(this.ratings, ugcReview.ratings) &&
        Objects.equals(this.reviewCount, ugcReview.reviewCount) &&
        Objects.equals(this.posReviewCount, ugcReview.posReviewCount) &&
        Objects.equals(this.criReviewCount, ugcReview.criReviewCount) &&
        Objects.equals(this.imgReviewCount, ugcReview.imgReviewCount) &&
        Objects.equals(this.totalRating, ugcReview.totalRating) &&
        Objects.equals(this.approvedImageCount, ugcReview.approvedImageCount) &&
        Objects.equals(this.id, ugcReview.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ratings, reviewCount, posReviewCount, criReviewCount, imgReviewCount, totalRating, approvedImageCount, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UgcReview {\n");
    
    sb.append("    ratings: ").append(toIndentedString(ratings)).append("\n");
    sb.append("    reviewCount: ").append(toIndentedString(reviewCount)).append("\n");
    sb.append("    posReviewCount: ").append(toIndentedString(posReviewCount)).append("\n");
    sb.append("    criReviewCount: ").append(toIndentedString(criReviewCount)).append("\n");
    sb.append("    imgReviewCount: ").append(toIndentedString(imgReviewCount)).append("\n");
    sb.append("    totalRating: ").append(toIndentedString(totalRating)).append("\n");
    sb.append("    approvedImageCount: ").append(toIndentedString(approvedImageCount)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

