package com.elitecore.diameterapi.mibs.base.autogen;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling DIAMETER-BASE-PROTOCOL-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "DbpAppAdvToPeerEntry" MBean.
 */
public interface DbpAppAdvToPeerEntryMBean {

    /**
     * Getter for the "DbpAppAdvToPeerRowStatus" variable.
     */
    public EnumDbpAppAdvToPeerRowStatus getDbpAppAdvToPeerRowStatus() throws SnmpStatusException;

    /**
     * Setter for the "DbpAppAdvToPeerRowStatus" variable.
     * NB: There is no check method generated for RowStatus.
     *      Override checkRowStatusChange on SnmpMibTable if needed.
     */
    public void setDbpAppAdvToPeerRowStatus(EnumDbpAppAdvToPeerRowStatus x) throws SnmpStatusException;

    /**
     * Getter for the "DbpAppAdvToPeerStorageType" variable.
     */
    public EnumDbpAppAdvToPeerStorageType getDbpAppAdvToPeerStorageType() throws SnmpStatusException;

    /**
     * Setter for the "DbpAppAdvToPeerStorageType" variable.
     */
    public void setDbpAppAdvToPeerStorageType(EnumDbpAppAdvToPeerStorageType x) throws SnmpStatusException;

    /**
     * Checker for the "DbpAppAdvToPeerStorageType" variable.
     */
    public void checkDbpAppAdvToPeerStorageType(EnumDbpAppAdvToPeerStorageType x) throws SnmpStatusException;

    /**
     * Getter for the "DbpAppAdvToPeerServices" variable.
     */
    public EnumDbpAppAdvToPeerServices getDbpAppAdvToPeerServices() throws SnmpStatusException;

    /**
     * Getter for the "DbpAppAdvToPeerIndex" variable.
     */
    public Long getDbpAppAdvToPeerIndex() throws SnmpStatusException;

    /**
     * Getter for the "DbpAppAdvToPeerVendorId" variable.
     */
    public Long getDbpAppAdvToPeerVendorId() throws SnmpStatusException;

    /**
     * Getter for the "DbpPeerIndex" variable.
     */
    public Long getDbpPeerIndex() throws SnmpStatusException;

}
