package com.elitecore.diameterapi.mibs.base.autogen;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling DIAMETER-BASE-PROTOCOL-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "DbpLocalCfgs" MBean.
 */
public interface DbpLocalCfgsMBean {

    /**
     * Getter for the "DbpLocalRealm" variable.
     */
    public String getDbpLocalRealm() throws SnmpStatusException;

    /**
     * Setter for the "DbpLocalRealm" variable.
     */
    public void setDbpLocalRealm(String x) throws SnmpStatusException;

    /**
     * Checker for the "DbpLocalRealm" variable.
     */
    public void checkDbpLocalRealm(String x) throws SnmpStatusException;

    /**
     * Getter for the "DbpLocalOriginHost" variable.
     */
    public String getDbpLocalOriginHost() throws SnmpStatusException;

    /**
     * Setter for the "DbpLocalOriginHost" variable.
     */
    public void setDbpLocalOriginHost(String x) throws SnmpStatusException;

    /**
     * Checker for the "DbpLocalOriginHost" variable.
     */
    public void checkDbpLocalOriginHost(String x) throws SnmpStatusException;

    /**
     * Getter for the "DbpLocalSctpListenPort" variable.
     */
    public Long getDbpLocalSctpListenPort() throws SnmpStatusException;

    /**
     * Getter for the "DbpLocalTcpListenPort" variable.
     */
    public Long getDbpLocalTcpListenPort() throws SnmpStatusException;

    /**
     * Getter for the "DbpLocalId" variable.
     */
    public String getDbpLocalId() throws SnmpStatusException;

    /**
     * Access the "DbpAppAdvToPeerTable" variable.
     */
    public TableDbpAppAdvToPeerTable accessDbpAppAdvToPeerTable() throws SnmpStatusException;

    /**
     * Access the "DbpLocalApplTable" variable.
     */
    public TableDbpLocalApplTable accessDbpLocalApplTable() throws SnmpStatusException;

}
