package com.elitecore.diameterapi.mibs.base.autogen;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling DIAMETER-BASE-PROTOCOL-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "DbpPeerCfgs" MBean.
 */
public interface DbpPeerCfgsMBean {

    /**
     * Access the "DbpPeerVendorTable" variable.
     */
    public TableDbpPeerVendorTable accessDbpPeerVendorTable() throws SnmpStatusException;

    /**
     * Access the "DbpAppAdvFromPeerTable" variable.
     */
    public TableDbpAppAdvFromPeerTable accessDbpAppAdvFromPeerTable() throws SnmpStatusException;

    /**
     * Access the "DbpPeerIpAddrTable" variable.
     */
    public TableDbpPeerIpAddrTable accessDbpPeerIpAddrTable() throws SnmpStatusException;

    /**
     * Access the "DbpPeerTable" variable.
     */
    public TableDbpPeerTable accessDbpPeerTable() throws SnmpStatusException;

}
