package com.elitecore.diameterapi.mibs.base.autogen;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling DIAMETER-BASE-PROTOCOL-MIB.
//

// java imports
//
import java.io.Serializable;
import java.util.Hashtable;

// RI imports
//
import com.sun.jdmk.Enumerated;

/**
 * The class is used for representing "DbpRealmKnownPeersChosen".
 */
public class EnumDbpRealmKnownPeersChosen extends Enumerated implements Serializable {

    protected static Hashtable intTable = new Hashtable();
    protected static Hashtable stringTable = new Hashtable();
    static  {
        intTable.put(new Integer(1), "other");
        intTable.put(new Integer(5), "mostRecentFirst");
        intTable.put(new Integer(4), "firstPreferred");
        intTable.put(new Integer(2), "roundRobin");
        intTable.put(new Integer(3), "loadBalance");
        stringTable.put("other", new Integer(1));
        stringTable.put("mostRecentFirst", new Integer(5));
        stringTable.put("firstPreferred", new Integer(4));
        stringTable.put("roundRobin", new Integer(2));
        stringTable.put("loadBalance", new Integer(3));
    }

    public EnumDbpRealmKnownPeersChosen(int valueIndex) throws IllegalArgumentException {
        super(valueIndex);
    }

    public EnumDbpRealmKnownPeersChosen(Integer valueIndex) throws IllegalArgumentException {
        super(valueIndex);
    }

    public EnumDbpRealmKnownPeersChosen() throws IllegalArgumentException {
        super();
    }

    public EnumDbpRealmKnownPeersChosen(String x) throws IllegalArgumentException {
        super(x);
    }

    protected Hashtable getIntTable() {
        return intTable ;
    }

    protected Hashtable getStringTable() {
        return stringTable ;
    }

}
