package com.elitecore.core.imdg.autogen;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling IMDG-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpOidRecord;

// jdmk imports
//
import com.sun.management.snmp.SnmpOidTableSupport;

/**
 * The class contains metadata definitions for "IMDG-MIB".
 * Call SnmpOid.setSnmpOidTable(new IMDG_MIBOidTable()) to load the metadata in the SnmpOidTable.
 */
public class IMDG_MIBOidTable extends SnmpOidTableSupport implements Serializable {

    /**
     * Default constructor. Initialize the Mib tree.
     */
    public IMDG_MIBOidTable() {
        super("IMDG_MIB");
        loadMib(varList);
    }

    static SnmpOidRecord varList [] = {
        new SnmpOidRecord("ownState", "1.3.6.1.4.1.21067.6.9", "S"),
        new SnmpOidRecord("ownPort", "1.3.6.1.4.1.21067.6.8", "I"),
        new SnmpOidRecord("ownIpAddress", "1.3.6.1.4.1.21067.6.7", "S"),
        new SnmpOidRecord("clusterState", "1.3.6.1.4.1.21067.6.6", "S"),
        new SnmpOidRecord("clusterMembersCount", "1.3.6.1.4.1.21067.6.5", "C"),
        new SnmpOidRecord("clusterName", "1.3.6.1.4.1.21067.6.4", "S"),
        new SnmpOidRecord("clusterVersion", "1.3.6.1.4.1.21067.6.3", "S"),
        new SnmpOidRecord("migrationStatus", "1.3.6.1.4.1.21067.6.2.4", "I"),
        new SnmpOidRecord("memberStatus", "1.3.6.1.4.1.21067.6.2.3", "I"),
        new SnmpOidRecord("member", "1.3.6.1.4.1.21067.6.2.2", "S"),
        new SnmpOidRecord("instanceStatus", "1.3.6.1.4.1.21067.6.2.1", "I"),
        new SnmpOidRecord("membersDetailTable", "1.3.6.1.4.1.21067.6.11.1", "TA"),
        new SnmpOidRecord("membersDetailEntry", "1.3.6.1.4.1.21067.6.11.1.1", "EN"),
        new SnmpOidRecord("status", "1.3.6.1.4.1.21067.6.11.1.1.5", "I"),
        new SnmpOidRecord("port", "1.3.6.1.4.1.21067.6.11.1.1.4", "I"),
        new SnmpOidRecord("ipAddress", "1.3.6.1.4.1.21067.6.11.1.1.3", "S"),
        new SnmpOidRecord("memberName", "1.3.6.1.4.1.21067.6.11.1.1.2", "S"),
        new SnmpOidRecord("memberID", "1.3.6.1.4.1.21067.6.11.1.1.1", "G"),
        new SnmpOidRecord("mapStatisticsTable", "1.3.6.1.4.1.21067.6.10.1", "TA"),
        new SnmpOidRecord("mapDetailEntry", "1.3.6.1.4.1.21067.6.10.1.1", "EN"),
        new SnmpOidRecord("totalGetOperations", "1.3.6.1.4.1.21067.6.10.1.1.9", "C64"),
        new SnmpOidRecord("totalPutOperations", "1.3.6.1.4.1.21067.6.10.1.1.8", "C64"),
        new SnmpOidRecord("noOfLockedSessions", "1.3.6.1.4.1.21067.6.10.1.1.7", "C64"),
        new SnmpOidRecord("memoryUsedForBackUp", "1.3.6.1.4.1.21067.6.10.1.1.6", "C64"),
        new SnmpOidRecord("memoryUsedbyMap", "1.3.6.1.4.1.21067.6.10.1.1.5", "C64"),
        new SnmpOidRecord("avgRemoveLatency", "1.3.6.1.4.1.21067.6.10.1.1.13", "C64"),
        new SnmpOidRecord("backupSessions", "1.3.6.1.4.1.21067.6.10.1.1.4", "C64"),
        new SnmpOidRecord("avgGetLatency", "1.3.6.1.4.1.21067.6.10.1.1.12", "C64"),
        new SnmpOidRecord("activeSessions", "1.3.6.1.4.1.21067.6.10.1.1.3", "C64"),
        new SnmpOidRecord("avgPutLatency", "1.3.6.1.4.1.21067.6.10.1.1.11", "C64"),
        new SnmpOidRecord("mapName", "1.3.6.1.4.1.21067.6.10.1.1.2", "S"),
        new SnmpOidRecord("totalRemoveOperations", "1.3.6.1.4.1.21067.6.10.1.1.10", "C64"),
        new SnmpOidRecord("mapIndex", "1.3.6.1.4.1.21067.6.10.1.1.1", "G"),
        new SnmpOidRecord("alertMigrationHealth", "1.3.6.1.4.1.21067.6.1.3", "NT"),
        new SnmpOidRecord("alertInstanceStatus", "1.3.6.1.4.1.21067.6.1.1", "NT"),
        new SnmpOidRecord("alertMemberStatus", "1.3.6.1.4.1.21067.6.1.2", "NT")    };
}
