Insert into TBLMPLUGINVERSION values(seq_tblmversion.nextval,'6.0.0.0-r${eliteaaa.svn.rev}','FULLSETUP','Proxy Decision Plugin',CURRENT_TIMESTAMP);

Insert into TBLMPLUGINTYPE
	(PLUGINTYPEID,NETSERVERTYPEID,NAME,ALIAS,DESCRIPTION,SYSTEMGENERATED,ENABLED,PROCESSINGTYPE,PLUGINVERSION)
Values
	('PGT0004','SRV0001','Proxy Decision Plugin','PROXY_DECISION_PLUGIN','Proxy Decision Plugin','N','Y',1,'${plugin.version}');

Insert into TBLMNETCONFIGURATION
	(NETCONFIGID, SERIALNO, NAME, DISPLAYNAME, FILENAME,
	ALIAS, CONFIGVERSION)
Values
	('PGC0004', 4 ,'Proxy Decision Plugin' , 'Proxy Decision Plugin' , 'proxy-decision-plugin' ,
	'PROXY_DECISION_PLUGIN' , '1.0');

Insert into TBLMPLUGINCONFIGMAP (PLUGINTYPEID,NETCONFIGID) values ('PGT0004','PGC0004');

Commit;

-- Proxy Decision Plugin Configuration --

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000016' , 'PGC0004' , 1 , 'Proxy Decision Plugin' , 'Proxy Decision Plugin' ,
	'proxy-decision-plugin' , 'Proxy Decision Plugin' , 'P' , 'regexp' , 1 , 'N' ,
	NULL , NULL , 0 , 'N' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000017' , 'PGC0004' , 1 , 'Datasource Name' , 'Datasource Name' ,
	'datasource-name' , 'Datasource Name' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000016' , NULL , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000018' , 'PGC0004' , 2 , 'Table Name' , 'Table Name' ,
	'table-name' , 'Table Name' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000016' , NULL , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000019' , 'PGC0004' , 3 , 'User Identity' , 'User Identity' ,
	'user-identity' , 'User Identity' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000016' , NULL , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

Commit;
