
Insert into TBLMPLUGINVERSION values(seq_tblmversion.nextval,'6.0.0.0-r${eliteaaa.svn.rev}','FULLSETUP','Quota Management Plugin',CURRENT_TIMESTAMP);


Insert into TBLMPLUGINTYPE
	(PLUGINTYPEID,NETSERVERTYPEID,NAME,ALIAS,DESCRIPTION,SYSTEMGENERATED,ENABLED,PROCESSINGTYPE,PLUGINVERSION)
Values
	('PGT0002','SRV0001','Quota Management Plugin','QUOTA_MANAGEMENT_PLUGIN','Quota Management Plugin','N','Y',1,'${plugin.version}');

Insert into TBLMNETCONFIGURATION
	(NETCONFIGID, SERIALNO, NAME, DISPLAYNAME, FILENAME,
	ALIAS, CONFIGVERSION)
Values
	('PGC0002', 2 ,'Quota Management Plugin' , 'Quota Management Plugin' , 'quota-management-plugin' ,
	'QUOTA_MANAGEMENT_PLUGIN' , '1.0');

Commit;


Insert into TBLMPLUGINCONFIGMAP (PLUGINTYPEID,NETCONFIGID) values ('PGT0002','PGC0002');


-- Quota Management Plugin Configuration --

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000008' , 'PGC0002' , 1 , 'Prepaid Quota Manager' , 'Prepaid Quota Manager' ,
	'prepaid-quota-manager' , 'Prepaid Quota Manager' , 'P' , 'regexp' , 1 , 'N' ,
	NULL , NULL , 0 , 'N' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000009' , 'PGC0002' , 1 , 'Prepaid Quota Type' , 'Prepaid Quota Type' ,
	'prepaid-quota-type' , 'Prepaid Quota Type' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000008' , NULL , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000010' , 'PGC0002' , 2 , 'Continue Further Processing' , 'Continue Further Processing' ,
	'continue-further-processing' , 'Continue Further Processing' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000008' , NULL , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000011' , 'PGC0002' , 3 , 'Action' , 'Action' ,
	'action' , 'Action' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000008' , NULL , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000012' , 'PGC0002' , 4 , 'Type Of Packet' , 'Type Of Packet' ,
	'type-of-packet' , 'Type Of Packet' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000008' , NULL , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000013' , 'PGC0002' , 5 , 'Class Attribute Key For Volume' , 'Class Attribute Key For Volume' ,
	'class-attribute-key-for-volume' , 'Class Attribute Key For Volume' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000008' , 'MAX_SESSION_VOLUME' , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000014' , 'PGC0002' , 6 , 'Class Attribute Key For Time' , 'Class Attribute Key For Time' ,
	'class-attribute-key-for-time' , 'Class Attribute Key For Time' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000008' , 'MAX_SESSION_TIME' , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000015' , 'PGC0002' , 7 , 'List Of Attributes' , 'List Of Attributes' ,
	'list-of-attributes' , 'List Of Attributes' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000008' , '0:1; 0:4;0:31 ; 24757:44=0:50 ;24757:60=0;0:89' , 500 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

Commit;


Insert into TBLMNETCONFIGPARAMVALUEPOOL
   (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
 Values
   ('PGV000000001', 'PGP000009', 'TIME', 'TIME', 'PGC0002');
Insert into TBLMNETCONFIGPARAMVALUEPOOL
   (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
 Values
   ('PGV000000002', 'PGP000009', 'VOLUME', 'VOLUME', 'PGC0002');
Insert into TBLMNETCONFIGPARAMVALUEPOOL
   (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
 Values
   ('PGV000000003', 'PGP000009', 'BOTH', 'BOTH', 'PGC0002');
Insert into TBLMNETCONFIGPARAMVALUEPOOL
   (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
 Values
   ('PGV000000004', 'PGP000010', 'True', 'true', 'PGC0002');

Insert into TBLMNETCONFIGPARAMVALUEPOOL
   (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
 Values
   ('PGV000000005', 'PGP000010', 'False', 'false', 'PGC0002');
Insert into TBLMNETCONFIGPARAMVALUEPOOL
   (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
 Values
   ('PGV000000006', 'PGP000011', 'ACCEPT', 'ACCEPT', 'PGC0002');
Insert into TBLMNETCONFIGPARAMVALUEPOOL
   (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
 Values
   ('PGV000000007', 'PGP000011', 'DROP', 'DROP', 'PGC0002');
Insert into TBLMNETCONFIGPARAMVALUEPOOL
   (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
 Values
   ('PGV000000008', 'PGP000012', 'CoA', 'CoA', 'PGC0002');
Insert into TBLMNETCONFIGPARAMVALUEPOOL
   (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
 Values
   ('PGV000000009', 'PGP000012', 'DM', 'DM', 'PGC0002');

commit;
