
Insert into TBLMPLUGINVERSION values(seq_tblmversion.nextval,'6.0.0.0-r${eliteaaa.svn.rev}','FULLSETUP','String Operation Plugin',CURRENT_TIMESTAMP);


Insert into TBLMPLUGINTYPE
	(PLUGINTYPEID,NETSERVERTYPEID,NAME,ALIAS,DESCRIPTION,SYSTEMGENERATED,ENABLED,PROCESSINGTYPE,PLUGINVERSION)
Values
	('PGT0001','SRV0001','String Operation Plugin','STRING_OPERATION_PLUGIN','String Operation Plugin','N','Y',3,'${plugin.version}');

Insert into TBLMNETCONFIGURATION
	(NETCONFIGID, SERIALNO, NAME, DISPLAYNAME, FILENAME,
	ALIAS, CONFIGVERSION)
Values
	('PGC0001', 1 ,'String Operation Plugin' , 'String Operation Plugin' , 'string-operation-plugin' ,
	'STRING_OPERATION_PLUGIN' , '1.0');

Insert into TBLMPLUGINCONFIGMAP (PLUGINTYPEID,NETCONFIGID) values ('PGT0001','PGC0001');


Commit;


-- String Operation Plugin Configuration --

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000001' , 'PGC0001' , 1 , 'String Operation Plugin' , 'String Operation Plugin' ,
	'string-operation-plugin' , 'String Operation Plugin' , 'P' , 'regexp' , 1 , 'N' ,
	NULL , NULL , 0 , 'N' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000002' , 'PGC0001' , 1 , 'String Operation List' , 'String Operation List' ,
	'string-operation-list' , 'String Operation List' , 'P' , 'regexp' , 1 , 'N' ,
	'PGP000001' , NULL , 0 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000003' , 'PGC0001' , 1 , 'String Operation' , 'String Operation' ,
	'string-operation' , 'String Operation' , 'P' , 'regexp' , 100 , 'Y' ,
	'PGP000002' , NULL , 0 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000004' , 'PGC0001' , 1 , 'Attribute Id' , 'Attribute Id' ,
	'attribute-id' , 'Attribute Id' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000003' , NULL , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000005' , 'PGC0001' , 2 , 'Conditions' , 'Conditions' ,
	'conditions' , 'Specifies the condition for applying operation. For example, startsWith(111). ' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000003' , NULL , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000006' , 'PGC0001' , 3 , 'First Only' , 'First Only' ,
	'first-only' , 'First Only' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000003' , NULL , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000007' , 'PGC0001' , 4 , 'Operation' , 'Operation' ,
	'operation' , 'Specifies the string operation. operations are concat,replaceAll,subString,toLowerCase,toUpperCase,trim,stripPrefix,stripSuffix. <br/> Examples, concat(aaa),replaceAll(aaa,bbb),subString(5),subString(5,10),tolowercase(),touppercase(),trim(),stripPrefix(identString,includeIdentString),stripSuffix(identString,includeIdentString) ' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000003' , NULL , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

Commit;
