
Insert into TBLMPLUGINVERSION values(seq_tblmversion.nextval,'6.0.0.0-r${eliteaaa.svn.rev}','FULLSETUP','User Statistic Post Auth Plugin',CURRENT_TIMESTAMP);


Insert into TBLMPLUGINTYPE
	(PLUGINTYPEID,NETSERVERTYPEID,NAME,ALIAS,DESCRIPTION,SYSTEMGENERATED,ENABLED,PROCESSINGTYPE,PLUGINVERSION)
Values
	('PGT0005','SRV0001','User Statistic Post Auth Plugin','USER_STATISTIC_POST_AUTH_PLUGIN','User Statistic Post Auth Plugin','N','Y',2,'${plugin.version}');



Insert into TBLMNETCONFIGURATION
	(NETCONFIGID, SERIALNO, NAME, DISPLAYNAME, FILENAME,
	ALIAS, CONFIGVERSION)
Values
	('PGC0005', 5 ,'User Statistic Post Auth Plugin' , 'User Statistic Post Auth Plugin' , 'user-statistic-post-auth-plugin' ,
	'USER_STATISTIC_POST_AUTH_PLUGIN' , '1.0');


Insert into TBLMPLUGINCONFIGMAP (PLUGINTYPEID,NETCONFIGID) values ('PGT0005','PGC0005');


Commit;


-- User Statistic Post Auth Plugin Configuration --

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000020' , 'PGC0005' , 1 , 'User Statistic Post Auth Plugin' , 'User Statistic Post Auth Plugin' ,
	'user-statistic-post-auth-plugin' , 'User Statistic Post Auth Plugin' , 'P' , 'regexp' , 1 , 'N' ,
	NULL , NULL , 0 , 'N' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000021' , 'PGC0005' , 1 , 'Datasource Name' , 'Datasource Name' ,
	'datasource-name' , 'Datasource Name' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000020' , 'USER_STATISTICS_DS' , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000022' , 'PGC0005' , 2 , 'Datasource Type' , 'Datasource Type' ,
	'datasource-type' , 'Datasource Type' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000020' , 'oracle' , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000023' , 'PGC0005' , 3 , 'Table Name' , 'Table Name' ,
	'tablename' , 'Table Name' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000020' , 'tbluserstatistics' , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000024' , 'PGC0005' , 4 , 'Datasource Scantime' , 'Datasource Scantime' ,
	'datasource-scantime' , 'Datasource Scantime' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000020' , '1', 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000025' , 'PGC0005' , 5 , 'DB Query Timeout' , 'DB Query Timeout' ,
	'db-query-timeout' , 'DB Query Timeout' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000020' , '0' , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000026' , 'PGC0005' , 6 , 'Max Query Timeout Count' , 'Max Query Timeout Count' ,
	'max-query-timeout-count' , 'Max Query Timeout Count' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000020' , '200' , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000027' , 'PGC0005' , 7 , 'Batch Update Interval' , 'Batch Update Interval' ,
	'batch-update-interval' , 'Batch Update Interval' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000020' , '10000' , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000028' , 'PGC0005' , 8 , 'DB Field Mapping' , 'DB Field Mapping' ,
	'db-field-mapping' , 'DB Field Mapping' , 'P' , 'regexp' , 1 , 'N' ,
	'PGP000020' , NULL , 0 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000029' , 'PGC0005' , 1 , 'Attribute' , 'Attribute' ,
	'attribute' , 'Attribute' , 'P' , 'regexp' , 100 , 'Y' ,
	'PGP000028' , NULL , 0 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000030' , 'PGC0005' , 1 , 'Attribute Ids' , 'Attribute Ids' ,
	'attribute-ids' , 'Attribute Ids' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000029' , NULL , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000031' , 'PGC0005' , 2 , 'Packet Type' , 'Packet Type' ,
	'packet-type' , 'Packet Type' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000029' , NULL , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000032' , 'PGC0005' , 3 , 'DB Field' , 'DB Field' ,
	'db-field' , 'DB Field' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000029' , NULL , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000033' , 'PGC0005' , 4 , 'Data Type' , 'Data Type' ,
	'data-type' , 'Data Type' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000029' , NULL , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000034' , 'PGC0005' , 5 , 'Default Value' , 'Default Value' ,
	'default-value' , 'Default Value' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000029' , NULL , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('PGP000035' , 'PGC0005' , 6 , 'Use Dictionary Value' , 'Use Dictionary Value' ,
	'use-dictionary-value' , 'Use Dictionary Value' , 'L' , 'regexp' , 1 , 'N' ,
	'PGP000029' , 'false' , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

Commit;

Insert into TBLMNETCONFIGPARAMVALUEPOOL
   (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
 Values
   ('PGV000000010', 'PGP000031', 'Request Packet', '0', 'PGC0005');

Insert into TBLMNETCONFIGPARAMVALUEPOOL
   (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
 Values
   ('PGV000000011', 'PGP000031', 'Response Packet', '1', 'PGC0005');

Insert into TBLMNETCONFIGPARAMVALUEPOOL
   (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
 Values
   ('PGV000000012', 'PGP000035', 'True', 'true', 'PGC0005');

Insert into TBLMNETCONFIGPARAMVALUEPOOL
   (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
 Values
   ('PGV000000013', 'PGP000035', 'False', 'false', 'PGC0005');


Commit;

CREATE SEQUENCE SEQ_USERSTATISTICS 
    INCREMENT BY 1
    START WITH 20
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    CACHE 20
    NOORDER;

CREATE TABLE TBLUSERSTATISTICS
(
  USERSTATISTICSID          NUMERIC,
  CREATE_DATE               TIMESTAMP,
  USER_NAME                 VARCHAR(253),
  REPLY_MESSAGE             VARCHAR(253),
  NAS_IP_ADDRESS            VARCHAR(20),
  NAS_PORT                  NUMERIC(10),
  SERVICE_TYPE              VARCHAR(50),
  FRAMED_PROTOCOL           VARCHAR(50),
  FRAMED_IP_ADDRESS         VARCHAR(20),
  FRAMED_IP_NETMASK         VARCHAR(20),
  FRAMED_ROUTING            VARCHAR(50),
  FILTER_ID                 VARCHAR(50),
  FRAMED_MTU                NUMERIC(10),
  CALLBACK_NUMBER           VARCHAR(50),
  CALLBACK_ID               VARCHAR(50),
  FRAMED_ROUTE              VARCHAR(50),
  SESSION_TIMEOUT           NUMERIC(10),
  IDLE_TIMEOUT              NUMERIC(10),
  TERMINATION_ACTION        VARCHAR(50),
  CALLED_STATION_ID         VARCHAR(253),
  CALLING_STATION_ID        VARCHAR(253),
  NAS_IDENTIFIER            VARCHAR(50),
  PROXY_STATE               NUMERIC(10),
  NAS_PORT_TYPE             VARCHAR(50),
  PORT_LIMIT                NUMERIC(10),
  EVENT_TIMESTAMP           NUMERIC(14),
  NAS_PORT_ID               VARCHAR(50),
  CONNECT_INFO              VARCHAR(253),
  PARAM_STR0                VARCHAR(253),
  PARAM_STR1                VARCHAR(253),
  PARAM_STR2                VARCHAR(253),
  PARAM_STR3                VARCHAR(253),
  PARAM_STR4                VARCHAR(253),
  PARAM_STR5                VARCHAR(253),
  PARAM_STR6                VARCHAR(253),
  PARAM_STR7                VARCHAR(253),
  PARAM_STR8                VARCHAR(253),
  PARAM_STR9                VARCHAR(253),
  PARAM_INT0                NUMERIC,
  PARAM_INT1                NUMERIC,
  PARAM_INT2                NUMERIC,
  PARAM_INT3                NUMERIC,
  PARAM_INT4                NUMERIC,
  PARAM_DATE0              TIMESTAMP,
  PARAM_DATE1              TIMESTAMP,
  PARAM_DATE2              TIMESTAMP,
  GROUPNAME                 VARCHAR(60),
  USER_IDENTITY             VARCHAR(100),
  ESN_MEID 				  	VARCHAR(16),
  CUI 	 				  	VARCHAR(64),
  HA_IP					  	VARCHAR(64),
  BS_ID					  	VARCHAR(64),
  PCF_SGSN_AGW 				VARCHAR(64),
  NAP_OPERATOR_CARRIER 		VARCHAR(64),
  LOCATION			        VARCHAR(255)
);


commit;