-- upgrade dbc for rest api
-- Rev 20985

-- CPM000446 is for http port
UPDATE TBLMNETCONFIGURATIONPARAMETER SET STATUS = 'N' WHERE PARAMETERID IN ('CPM000446');

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME,
 ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES,
 PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
 STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('CPM000451' , 'CNF0001' , 6 , 'Rest API Listener Address' , 'Rest API Listener Address',
	 'rest-api-listener-address' , 'Rest API Listener Address' , 'L' , 'regexp' , 1 , 'N' ,
	 'CPM000001' , '0.0.0.0:9000' , 60 , 'Y' ,
	 'SMS0164' , 'Y' , 'N');
COMMIT;


--- REV 21017
ALTER TABLE TBLMRADIUSGATEWAYPROFILE ADD INTERIM_INTERVAL NUMERIC(5);

--REV 21078
ALTER TABLE TBLM_SUBSCRIBER ADD (CREATED_DATE TIMESTAMP,MODIFIED_DATE TIMESTAMP);

-- REV 21129
ALTER TABLE TBLM_PCC_RULE ADD GROUPS VARCHAR(400);

UPDATE TBLM_PCC_RULE SET GROUPS = '1' WHERE SCOPE = 'GLOBAL';
COMMIT;

-- 21175
UPDATE TBLMRADIUSGATEWAYPROFILE SET INTERIM_INTERVAL = 60 WHERE INTERIM_INTERVAL is NULL ;
COMMIT;