--rev 20401


-- for GLOBAL PCC RULE (JIRA 1784)

ALTER TABLE TBLM_PCC_RULE ADD SCOPE VARCHAR(8) DEFAULT 'LOCAL';

 CREATE TABLE TBLM_QOS_PROFILE_PCC_RELATION(
   QOS_PROFILE_DETAIL_ID VARCHAR(36),
   PCC_RULE_ID           VARCHAR(36),
   CONSTRAINT FK1_QOS_PROFILE_PCC_RELATION FOREIGN  KEY (QOS_PROFILE_DETAIL_ID) REFERENCES TBLM_QOS_PROFILE_DETAIL(ID),
   CONSTRAINT FK2_QOS_PROFILE_PCC_RELATION FOREIGN  KEY (PCC_RULE_ID) REFERENCES TBLM_PCC_RULE(ID),
   CONSTRAINT UK_QOS_PROFILE_PCC_RELATION  UNIQUE (QOS_PROFILE_DETAIL_ID,PCC_RULE_ID)
  );


INSERT INTO TBLM_QOS_PROFILE_PCC_RELATION(QOS_PROFILE_DETAIL_ID, PCC_RULE_ID) SELECT QOS_PROFILE_DETAIL_ID,ID FROM TBLM_PCC_RULE;

COMMIT ;

-- FOR JIRA 1783
DELETE FROM  TBLMSYSTEMPARAMETERVALUEPOOL WHERE PARAMETERID = 21;

COMMIT;

UPDATE
		TBLMSYSTEMPARAMETER
	SET
		NAME = 'Update Action For WS',
		VALUE = '0',
		ALIAS = 'UPDATE_ACTION',
		DESCRIPTION = 'Update Action on Subscription or Subscriber policy change. Possible options: 0(No_Action), 1(ReAuth_Session), 2(Disconnect Session)'
	WHERE
		PARAMETERID = '21';
COMMIT;

INSERT INTO TBLMSYSTEMPARAMETERVALUEPOOL VALUES('1',21,'No_Action(0)','0');
INSERT INTO TBLMSYSTEMPARAMETERVALUEPOOL VALUES('2',21,'ReAuth_Session(1)','1');
INSERT INTO TBLMSYSTEMPARAMETERVALUEPOOL VALUES('3',21,'Disconnect_Session(2)','2');
COMMIT;
