UPDATE TBLMVERSION SET VERSION = '6.8.0' ;
UPDATE TBLMNETSERVERTYPE SET VERSION = '6.8.0' ;
UPDATE TBLMNETSERVERINSTANCE SET VERSION = '6.8.0' ;
UPDATE TBLNETSERVERCONFIGVERSION SET NETSERVERVERSION = '6.8.0';
COMMIT;

--REV 20306
ALTER TABLE TBLM_SUBSCRIBER MODIFY country VARCHAR(55);
COMMIT;



-- REV 20343
ALTER TABLE TBLMCORESESSIONS ADD PACKAGE_USAGE VARCHAR(2000);

-- REV 20349

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('CPM000449' , 'CNF0001' , 3 , 'Session DB Datasource' , 'Session DB Datasource' ,
	'session-db-datasource' , 'Session DB Datasource' , 'P' , 'regexp' , 1 , 'N' ,
	'CPM000001' , NULL , 0 , 'N' ,
	'SMS0164' , 'Y' , 'N');
	
INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('CPM000450' , 'CNF0001' , 1 , 'Data Source' , 'Data Source' ,
	'data-source-id' , 'Data Source' , 'L' , 'regexp' , 1 , 'N' ,
	'CPM000449' , NULL , 100 , 'Y' ,
	'SMS0164' , 'Y' , 'N');		

	
	
DELETE FROM TBLMNETCONFIGURATIONPARAMETER WHERE PARAMETERID = 'CPM000268' AND CONFIGID = 'CNF0001';
DELETE FROM TBLMNETCONFIGURATIONPARAMETER WHERE PARAMETERID = 'CPM000267' AND CONFIGID = 'CNF0001';
DELETE FROM TBLMNETCONFIGURATIONPARAMETER WHERE PARAMETERID = 'CPM000266' AND CONFIGID = 'CNF0001';
COMMIT;

UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO= '4' WHERE PARAMETERID ='CPM000010';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO= '5' WHERE PARAMETERID ='CPM000266';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO= '6' WHERE PARAMETERID ='CPM000445';
COMMIT;

--REV 20411
DELETE FROM  TBLMSYSTEMPARAMETERVALUEPOOL WHERE PARAMETERID = 21;

COMMIT;

UPDATE
		TBLMSYSTEMPARAMETER
	SET
		NAME = 'Update Action For WS',
		VALUE = '0',
		ALIAS = 'UPDATE_ACTION',
		DESCRIPTION = 'Update Action on Subscription or Subscriber policy change. Possible options: 0(No_Action), 1(ReAuth_Session), 2(Disconnect Session)'
	WHERE
		PARAMETERID = '21';
COMMIT;

INSERT INTO TBLMSYSTEMPARAMETERVALUEPOOL VALUES('1',21,'No_Action(0)','0');
INSERT INTO TBLMSYSTEMPARAMETERVALUEPOOL VALUES('2',21,'ReAuth_Session(1)','1');
INSERT INTO TBLMSYSTEMPARAMETERVALUEPOOL VALUES('3',21,'Disconnect_Session(2)','2');
COMMIT;

--REV 20457
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (1,'SERVICETYPE','CREATE,DELETE,UPDATE,');
UPDATE TBLM_ROLE_MODULE_ACTIONS_REL SET ACTIONS ='CREATE,DELETE,UPDATE,UPDATE_BASIC_DETAIL,' WHERE ROLEID ='1' AND MODULE_NAME ='IMSPKG';
UPDATE TBLM_ROLE_MODULE_ACTIONS_REL SET ACTIONS ='CREATE,DELETE,UPDATE,UPDATE_BASIC_DETAIL,' WHERE ROLEID ='1' AND MODULE_NAME ='DATAPKG';
COMMIT;

CREATE TABLE TBLM_SERVER_INSTANCE_GROUP(
ID                   VARCHAR(36),
NAME                 VARCHAR(100) NOT NULL,
ACCESS_GROUPS        VARCHAR(400),
ORDER_NO NUMERIC(3)  DEFAULT 0,
CREATED_DATE         TIMESTAMP,
CREATED_BY_STAFF_ID  NUMERIC(20),
MODIFIED_DATE        TIMESTAMP,
MODIFIED_BY_STAFF_ID NUMERIC(20),
CONSTRAINT PK_SERVER_INSTANCE_GROUP PRIMARY KEY (ID),
CONSTRAINT UK_SERVER_INSTANCE_GROUP UNIQUE  (NAME),
CONSTRAINT FK_SERVER_INSTANCE_GROUP FOREIGN KEY (CREATED_BY_STAFF_ID) REFERENCES TBLMSTAFF (STAFFID),
CONSTRAINT FK1_SERVER_INSTANCE_GROUP FOREIGN KEY (MODIFIED_BY_STAFF_ID) REFERENCES TBLMSTAFF (STAFFID)
);

CREATE TABLE TBLM_NET_SERVER_GROUP_REL(
ID                        VARCHAR(36),
SERVER_INSTANCE_GROUP_ID  VARCHAR(36),
NETSERVER_INSTANCE_ID     NUMERIC(20),
SERVER_WEIGHTAGE          NUMERIC(2),
CONSTRAINT PK_NET_SERVER_GROUP_REL PRIMARY KEY (SERVER_INSTANCE_GROUP_ID, NETSERVER_INSTANCE_ID),
CONSTRAINT FK1_NET_SERVER_GROUP_REL FOREIGN KEY (SERVER_INSTANCE_GROUP_ID) REFERENCES TBLM_SERVER_INSTANCE_GROUP(ID),
CONSTRAINT FK2_NET_SERVER_GROUP_REL FOREIGN KEY (NETSERVER_INSTANCE_ID) REFERENCES TBLMNETSERVERINSTANCE(NETSERVERID)
);

INSERT INTO TBLM_SERVER_INSTANCE_GROUP(ID,NAME,ACCESS_GROUPS,ORDER_NO,CREATED_DATE,CREATED_BY_STAFF_ID)values('1','DefaultGroup','1',1,CURRENT_TIMESTAMP,1);
COMMIT;

DECLARE
counter NUMBER;
BEGIN
  FOR REC IN
  (SELECT * FROM TBLMNETSERVERINSTANCE)
  LOOP
     select MAX(ORDER_NO) into counter from TBLM_SERVER_INSTANCE_GROUP;
     INSERT INTO TBLM_SERVER_INSTANCE_GROUP(ID,NAME,ACCESS_GROUPS,CREATED_DATE,CREATED_BY_STAFF_ID,ORDER_NO)VALUES('SERVER-INSTANCE-GROUP'||REC.NETSERVERID,'SERVERGROUP_'||REC.NAME,'1',CURRENT_TIMESTAMP,1,counter+1);
     INSERT INTO TBLM_NET_SERVER_GROUP_REL(ID,SERVER_INSTANCE_GROUP_ID,NETSERVER_INSTANCE_ID,SERVER_WEIGHTAGE)VALUES('NET-SERVER-GROUP-REL'||REC.NETSERVERID,'SERVER-INSTANCE-GROUP'||REC.NETSERVERID,REC.NETSERVERID,1);
     COMMIT;
 END LOOP;
END;
/


-- REV 20528
ALTER TABLE TBLM_QUOTA_PROFILE ADD BALANCE_LEVEL   VARCHAR(5) DEFAULT 'HSQ';
-- REV 20879
INSERT INTO TBLMSYSTEMPARAMETER (PARAMETERID,NAME,ALIAS,SYSTEMGENERATED,DESCRIPTION) VALUES('30','Param 1 Field Label','PARAM_1','N','This will be used to set dynamic label of package param1 attribute. Default Param 1 if no label is configured.');
INSERT INTO TBLMSYSTEMPARAMETER (PARAMETERID,NAME,ALIAS,SYSTEMGENERATED,DESCRIPTION) VALUES('31','Param 2 Field Label','PARAM_2','N','This will be used to set dynamic label of package param2 attribute. Default Param 2 if no label is configured.');
COMMIT;

ALTER TABLE TBLM_PACKAGE
ADD
(PARAM_1 VARCHAR2(100),
PARAM_2 VARCHAR2(100)
);

ALTER TABLE TBLM_QOS_PROFILE_DETAIL
ADD REDIRECT_URL VARCHAR(4000);