--rev 21433
UPDATE TBLMVERSION SET VERSION = '6.8.2';
UPDATE TBLMNETSERVERTYPE SET VERSION = '6.8.2';
UPDATE TBLMNETSERVERINSTANCE SET VERSION = '6.8.2';
UPDATE TBLNETSERVERCONFIGVERSION SET NETSERVERVERSION = '6.8.2';
COMMIT;

UPDATE TBLMSTAFF SET PASSWORDCHANGEDATE = null ,RECENTPASSWORDS = null;
COMMIT;

--rev 21689
CREATE TABLE TBLM_PASSWORD_ENCRYPT_STATUS
(
  MODULE VARCHAR(4000),
  STATUS VARCHAR(20) DEFAULT 'PENDING',
  SM_INSTANCE_ID VARCHAR (36),
  MODIFIED_DATE TIMESTAMP
);
INSERT INTO TBLM_PASSWORD_ENCRYPT_STATUS(MODULE)VALUES ('TBLMNETCONFIGURATIONVALUES');
INSERT INTO TBLM_PASSWORD_ENCRYPT_STATUS(MODULE)VALUES ('TBLMDATABASEDS');
INSERT INTO TBLM_PASSWORD_ENCRYPT_STATUS(MODULE)VALUES ('TBLMLDAPDS');
INSERT INTO TBLM_PASSWORD_ENCRYPT_STATUS(MODULE)VALUES ('TBLMCSVDRIVER');
COMMIT;

--rev 21542
ALTER TABLE TBLM_PACKAGE ADD PREFER_PROMOTIONAL_QOS NUMERIC(1) DEFAULT 0;

--rev 21964
CREATE TABLE TBLM_PKG_GROUP_ORDER(
  ID                 VARCHAR(36),
  PKG_ID        VARCHAR(36),
  GROUP_ID   VARCHAR(36),
  ORDER_NO  NUMERIC(6) DEFAULT 0,
  TYPE           VARCHAR(32),
  CONSTRAINT PK_PKG_GROUP_ORDER PRIMARY KEY (ID),
  CONSTRAINT FK_PKG_GROUP_ORDER FOREIGN KEY (PKG_ID) REFERENCES TBLM_PACKAGE(ID)
);


INSERT INTO TBLM_PKG_GROUP_ORDER
SELECT ROWNUM,
  a.ID,
  a."group_id",
  a.ORDER_NO,
  a.TYPE
FROM
  ( SELECT DISTINCT ID,
    TRIM(REGEXP_SUBSTR(GROUPS, '[^,]+', 1,LEVEL)) AS "group_id" ,
    ORDER_NO,
    TYPE
  FROM
    (SELECT ID,GROUPS,ORDER_NO,TYPE FROM TBLM_PACKAGE WHERE TYPE='EMERGENGY' AND STATUS !='DELETED'
    ) T
    CONNECT BY TRIM(REGEXP_SUBSTR(GROUPS, '[^,]+', 1,LEVEL)) IS NOT NULL
  ORDER BY ID
  ) a;

/


COMMIT;

--rev 21965
CREATE TABLE TBLM_CHARGING_RULE_BASE_NAME (
  ID            VARCHAR(36),
  NAME          VARCHAR(100) NOT NULL,
  DESCRIPTION   VARCHAR(2000),
  STATUS                  VARCHAR(12) DEFAULT 'ACTIVE',
  GROUPS                  VARCHAR(400),
  CREATED_DATE            TIMESTAMP,
  CREATED_BY_STAFF_ID     NUMERIC(20),
  MODIFIED_DATE           TIMESTAMP,
  MODIFIED_BY_STAFF_ID    NUMERIC(20),
  CONSTRAINT PK_CHARGING_RULE_BASE_NAME PRIMARY KEY (ID)
);

CREATE TABLE TBLM_CHARGING_RULE_SERVICETYPE (
  ID                VARCHAR(36),
  SERVICE_TYPE_ID   VARCHAR(36) NOT NULL,
  MONITORING_KEY    VARCHAR(100) NOT NULL,
  CHARGING_RULE_BASE_NAME_ID VARCHAR(36) NOT NULL,
  SLICE_TOTAL       NUMERIC(18),
  SLICE_TOTAL_UNIT  VARCHAR(10),
  SLICE_UPLOAD      NUMERIC(18),
  SLICE_UPLOAD_UNIT VARCHAR(10),
  SLICE_DOWNLOAD          NUMERIC(18),
  SLICE_DOWNLOAD_UNIT     VARCHAR(10),
  SLICE_TIME              NUMERIC(18),
  SLICE_TIME_UNIT         VARCHAR(10),
  CONSTRAINT PK_CHARGING_RULE_SERVICETYPE PRIMARY KEY (ID),
  CONSTRAINT FK1_CHARGING_RULE_SERVICETYPE FOREIGN KEY (SERVICE_TYPE_ID) REFERENCES TBLM_SERVICE_TYPE(ID),
  CONSTRAINT FK2_CHARGING_RULE_SERVICETYPE FOREIGN KEY (CHARGING_RULE_BASE_NAME_ID) REFERENCES TBLM_CHARGING_RULE_BASE_NAME(ID)
);


CREATE TABLE TBLM_QOS_PROFILE_CRBN_REL(
  QOS_PROFILE_DETAIL_ID VARCHAR(36),
  CHARGING_RULE_BASE_NAME_ID           VARCHAR(36),
  CONSTRAINT FK1_QOS_PROFILE_CRBN_REL FOREIGN  KEY (QOS_PROFILE_DETAIL_ID) REFERENCES TBLM_QOS_PROFILE_DETAIL(ID),
  CONSTRAINT FK2_QOS_PROFILE_CRBN_REL FOREIGN  KEY (CHARGING_RULE_BASE_NAME_ID) REFERENCES TBLM_CHARGING_RULE_BASE_NAME(ID),
  CONSTRAINT UK_QOS_PROFILE_CRBN_REL  UNIQUE (QOS_PROFILE_DETAIL_ID,CHARGING_RULE_BASE_NAME_ID)
);


INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (3,'CHARGINGRULEBASENAME','UPDATE,');
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (1,'CHARGINGRULEBASENAME','CREATE,DELETE,EXPORT,IMPORT,UPDATE,');


ALTER TABLE TBLMCORESESSIONS ADD CHARGINGRULEBASENAMES VARCHAR(1000);
COMMIT;

--rev 22388
ALTER TABLE TBLM_RATING_GROUP ADD GROUPS VARCHAR(400);

--rev 22399
UPDATE TBLM_RATING_GROUP SET GROUPS = '1' WHERE ID = 'RATING_GROUP_1';

--rev 22490
ALTER TABLE TBLM_SERVER_INSTANCE_GROUP ADD SESSION_SYNCHRONIZATION NUMBER(1) DEFAULT 0;

--rev 22491
ALTER TABLE TBLMSESSIONRULE ADD ADDITIONAL_PARAMETER VARCHAR(4000);

--rev 22492
--for admin role
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (1,'EMERGENCYPKG','CREATE,DELETE,MANAGEORDER,UPDATE,EXPORT,IMPORT,UPDATE_BASIC_DETAIL,');
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (1,'EMERGENCYQOSPROFILE','CREATE,DELETE,MANAGEORDER,UPDATE,UPDATE_BASIC_DETAIL,');
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (1,'EMERGENCYPCCRULE','CREATE,DELETE,UPDATE,');

-- for support role 
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (2,'EMERGENCYPKG','CREATE,DELETE,MANAGEORDER,UPDATE,EXPORT,IMPORT,UPDATE_BASIC_DETAIL,');
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (2,'EMERGENCYQOSPROFILE','CREATE,DELETE,MANAGEORDER,UPDATE,UPDATE_BASIC_DETAIL,');
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (2,'EMERGENCYPCCRULE','CREATE,DELETE,UPDATE,');

-- for operator role
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (3,'EMERGENCYPKG','CREATE,DELETE,MANAGEORDER,UPDATE,EXPORT,IMPORT,UPDATE_BASIC_DETAIL,');
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (3,'EMERGENCYQOSPROFILE','CREATE,DELETE,MANAGEORDER,UPDATE,UPDATE_BASIC_DETAIL,');
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (3,'EMERGENCYPCCRULE','CREATE,DELETE,UPDATE,');

--rev 22493
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES(1,'RATINGGROUP','CREATE,DELETE,EXPORT,IMPORT,UPDATE,');
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (3,'RATINGGROUP','UPDATE,');

--rev 22501
UPDATE TBLM_ROLE_MODULE_ACTIONS_REL SET ACTIONS = ACTIONS||'IMPORT,EXPORT,' WHERE ROLEID = 1 AND MODULE_NAME = 'GLOBLEPCCRULE';
COMMIT;

--rev 22546
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (1,'PROMOTIONALPKG','CREATE,DELETE,MANAGEORDER,UPDATE,IMPORT,EXPORT,UPDATE_BASIC_DETAIL,');
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (1,'PROMOTIONALQOSPROFILE','CREATE,DELETE,MANAGEORDER,UPDATE,UPDATE_BASIC_DETAIL,');
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (1,'PROMOTIONALQUOTAPROFILE','CREATE,DELETE,UPDATE,');
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (1,'PROMOTIONALPCCRULE','CREATE,DELETE,UPDATE,');

INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (3,'PROMOTIONALPKG','UPDATE,UPDATE_BASIC_DETAIL,');
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (3,'PROMOTIONALQOSPROFILE','UPDATE,UPDATE_BASIC_DETAIL,');
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (3,'PROMOTIONALQUOTAPROFILE','UPDATE,');
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (3,'PROMOTIONALPCCRULE','UPDATE,');



--rev 22589
CREATE TABLE TBLM_PD_CONTEXT_INFORMATION(
  id VARCHAR(36),
  HOST_NAME VARCHAR(50),
  IP_ADDRESSES varchar(200),
  PORT VARCHAR(5),
  CONTEXT_PATH VARCHAR(20),
  DEPLOYMENT_PATH VARCHAR(200),
  LAST_UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  STATUS VARCHAR(10) DEFAULT 'SHUTDOWN',
  CONSTRAINT PK_PD_CONTEXT_INFORMATION PRIMARY KEY (id)
  );

--rev 22697
UPDATE TBLM_ROLE_MODULE_ACTIONS_REL SET MODULE_NAME ='GLOBALPCCRULE' WHERE MODULE_NAME='GLOBLEPCCRULE';
COMMIT;

--rev 22724
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (1,'SUBSCRIBERSESSION','REAUTH,DELETE,DISCONNECT,SEARCH,'); 
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (2,'SUBSCRIBERSESSION','REAUTH,DELETE,DISCONNECT,SEARCH,');
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (3,'SUBSCRIBERSESSION','REAUTH,DELETE,DISCONNECT,SEARCH,');
COMMIT;

--rev 22738
ALTER TABLE TBLM_SUBSCRIBER ADD (
CALLING_STATION_ID    VARCHAR(253),
FRAMED_IP             VARCHAR(20),
NAS_PORT_ID           VARCHAR(50));

--rev 23271
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES  (1,'PROMOTIONALNOTIFICATION','CREATE,DELETE,UPDATE,');
INSERT INTO TBLM_ROLE_MODULE_ACTIONS_REL (ROLEID,MODULE_NAME,ACTIONS) VALUES (3,'PROMOTIONALNOTIFICATION','UPDATE,')

COMMIT;