package com.elitecore.aaa.mibs.radius.dynauth.client.autogen;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling RADIUS-DYNAUTH-CLIENT-MIB in standard metadata mode.
//

// java imports
//
import java.io.Serializable;
import java.util.Hashtable;

// jmx imports
//
import javax.management.MBeanServer;
import javax.management.ObjectName;
import javax.management.InstanceAlreadyExistsException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;
import com.sun.management.snmp.agent.SnmpMibNode;
import com.sun.management.snmp.agent.SnmpMibTable;
import com.sun.management.snmp.agent.SnmpStandardObjectServer;

/**
 * The class is used for representing "RADIUS-DYNAUTH-CLIENT-MIB".
 * You can edit the file if you want to modify the behavior of the MIB.
 */
public class RADIUS_DYNAUTH_CLIENT_MIB extends SnmpMib implements Serializable {

    /**
     * Default constructor. Initialize the Mib tree.
     */
    public RADIUS_DYNAUTH_CLIENT_MIB() {
        mibName = "RADIUS_DYNAUTH_CLIENT_MIB";
    }

    /**
     * Initialization of the MIB with no registration in Java DMK.
     */
    public void init() throws IllegalAccessException {
        // Allow only one initialization of the MIB.
        //
        if (isInitialized == true) {
            return ;
        }

        try  {
            populate(null, null);
        } catch(IllegalAccessException x)  {
            throw x;
        } catch(RuntimeException x)  {
            throw x;
        } catch(Exception x)  {
            throw new Error(x.getMessage());
        }

        isInitialized = true;
    }

    /**
     * Initialization of the MIB with AUTOMATIC REGISTRATION in Java DMK.
     */
    public ObjectName preRegister(MBeanServer server, ObjectName name)
            throws Exception {
        // Allow only one initialization of the MIB.
        //
        if (isInitialized == true) {
            throw new InstanceAlreadyExistsException();
        }

        // Initialize MBeanServer information.
        //
        this.server = server;

        populate(server, name);

        isInitialized = true;
        return name;
    }

    /**
     * Initialization of the MIB with no registration in Java DMK.
     */
    public void populate(MBeanServer server, ObjectName name) 
        throws Exception {
        // Allow only one initialization of the MIB.
        //
        if (isInitialized == true) {
            return ;
        }

        if (objectserver == null) 
            objectserver = new SnmpStandardObjectServer();

        // Initialization of the "RadiusDynAuthClientMIBObjects" group.
        // To disable support of this group, redefine the 
        // "createRadiusDynAuthClientMIBObjectsMetaNode()" factory method, and make it return "null"
        //
        initRadiusDynAuthClientMIBObjects(server);

        // Initialization of the "RadiusDynAuthClientScalars" group.
        // To disable support of this group, redefine the 
        // "createRadiusDynAuthClientScalarsMetaNode()" factory method, and make it return "null"
        //
        initRadiusDynAuthClientScalars(server);

        isInitialized = true;
    }


    // ------------------------------------------------------------
    // 
    // Initialization of the "RadiusDynAuthClientMIBObjects" group.
    // 
    // ------------------------------------------------------------


    /**
     * Initialization of the "RadiusDynAuthClientMIBObjects" group.
     * 
     * To disable support of this group, redefine the 
     * "createRadiusDynAuthClientMIBObjectsMetaNode()" factory method, and make it return "null"
     * 
     * @param server    MBeanServer for this group (may be null)
     * 
     **/
    protected void initRadiusDynAuthClientMIBObjects(MBeanServer server) 
        throws Exception {
        final String oid = getGroupOid("RadiusDynAuthClientMIBObjects", "1.3.6.1.2.1.145.1");
        ObjectName objname = null;
        if (server != null) {
            objname = getGroupObjectName("RadiusDynAuthClientMIBObjects", oid, mibName + ":name=com.elitecore.aaa.mibs.radius.dynauth.client.autogen.RadiusDynAuthClientMIBObjects");
        }
        final RadiusDynAuthClientMIBObjectsMeta meta = createRadiusDynAuthClientMIBObjectsMetaNode("RadiusDynAuthClientMIBObjects", oid, objname, server);
        if (meta != null) {
            meta.registerTableNodes( this, server );

            // Note that when using standard metadata,
            // the returned object must implement the "RadiusDynAuthClientMIBObjectsMBean"
            // interface.
            //
            final RadiusDynAuthClientMIBObjectsMBean group = (RadiusDynAuthClientMIBObjectsMBean) createRadiusDynAuthClientMIBObjectsMBean("RadiusDynAuthClientMIBObjects", oid, objname, server);
            meta.setInstance( group );
            registerGroupNode("RadiusDynAuthClientMIBObjects", oid, objname, meta, group, server);
        }
    }


    /**
     * Factory method for "RadiusDynAuthClientMIBObjects" group metadata class.
     * 
     * You can redefine this method if you need to replace the default
     * generated metadata class with your own customized class.
     * 
     * @param groupName Name of the group ("RadiusDynAuthClientMIBObjects")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the metadata class generated for the
     *         "RadiusDynAuthClientMIBObjects" group (RadiusDynAuthClientMIBObjectsMeta)
     * 
     **/
    protected RadiusDynAuthClientMIBObjectsMeta createRadiusDynAuthClientMIBObjectsMetaNode(String groupName,
                String groupOid, ObjectName groupObjname, MBeanServer server)  {
        return new RadiusDynAuthClientMIBObjectsMeta(this, objectserver);
    }


    /**
     * Factory method for "RadiusDynAuthClientMIBObjects" group MBean.
     * 
     * You can redefine this method if you need to replace the default
     * generated MBean class with your own customized class.
     * 
     * @param groupName Name of the group ("RadiusDynAuthClientMIBObjects")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the MBean class generated for the
     *         "RadiusDynAuthClientMIBObjects" group (RadiusDynAuthClientMIBObjects)
     * 
     * Note that when using standard metadata,
     * the returned object must implement the "RadiusDynAuthClientMIBObjectsMBean"
     * interface.
     **/
    protected Object createRadiusDynAuthClientMIBObjectsMBean(String groupName,
                String groupOid,  ObjectName groupObjname, MBeanServer server)  {

        // Note that when using standard metadata,
        // the returned object must implement the "RadiusDynAuthClientMIBObjectsMBean"
        // interface.
        //
        if (server != null) 
            return new RadiusDynAuthClientMIBObjects(this,server);
        else 
            return new RadiusDynAuthClientMIBObjects(this);
    }


    // ------------------------------------------------------------
    // 
    // Initialization of the "RadiusDynAuthClientScalars" group.
    // 
    // ------------------------------------------------------------


    /**
     * Initialization of the "RadiusDynAuthClientScalars" group.
     * 
     * To disable support of this group, redefine the 
     * "createRadiusDynAuthClientScalarsMetaNode()" factory method, and make it return "null"
     * 
     * @param server    MBeanServer for this group (may be null)
     * 
     **/
    protected void initRadiusDynAuthClientScalars(MBeanServer server) 
        throws Exception {
        final String oid = getGroupOid("RadiusDynAuthClientScalars", "1.3.6.1.2.1.145.1.1");
        ObjectName objname = null;
        if (server != null) {
            objname = getGroupObjectName("RadiusDynAuthClientScalars", oid, mibName + "_RadiusDynAuthClientMIBObjects:name=com.elitecore.aaa.mibs.radius.dynauth.client.autogen.RadiusDynAuthClientScalars");
        }
        final RadiusDynAuthClientScalarsMeta meta = createRadiusDynAuthClientScalarsMetaNode("RadiusDynAuthClientScalars", oid, objname, server);
        if (meta != null) {
            meta.registerTableNodes( this, server );

            // Note that when using standard metadata,
            // the returned object must implement the "RadiusDynAuthClientScalarsMBean"
            // interface.
            //
            final RadiusDynAuthClientScalarsMBean group = (RadiusDynAuthClientScalarsMBean) createRadiusDynAuthClientScalarsMBean("RadiusDynAuthClientScalars", oid, objname, server);
            meta.setInstance( group );
            registerGroupNode("RadiusDynAuthClientScalars", oid, objname, meta, group, server);
        }
    }


    /**
     * Factory method for "RadiusDynAuthClientScalars" group metadata class.
     * 
     * You can redefine this method if you need to replace the default
     * generated metadata class with your own customized class.
     * 
     * @param groupName Name of the group ("RadiusDynAuthClientScalars")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the metadata class generated for the
     *         "RadiusDynAuthClientScalars" group (RadiusDynAuthClientScalarsMeta)
     * 
     **/
    protected RadiusDynAuthClientScalarsMeta createRadiusDynAuthClientScalarsMetaNode(String groupName,
                String groupOid, ObjectName groupObjname, MBeanServer server)  {
        return new RadiusDynAuthClientScalarsMeta(this, objectserver);
    }


    /**
     * Factory method for "RadiusDynAuthClientScalars" group MBean.
     * 
     * You can redefine this method if you need to replace the default
     * generated MBean class with your own customized class.
     * 
     * @param groupName Name of the group ("RadiusDynAuthClientScalars")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the MBean class generated for the
     *         "RadiusDynAuthClientScalars" group (RadiusDynAuthClientScalars)
     * 
     * Note that when using standard metadata,
     * the returned object must implement the "RadiusDynAuthClientScalarsMBean"
     * interface.
     **/
    protected Object createRadiusDynAuthClientScalarsMBean(String groupName,
                String groupOid,  ObjectName groupObjname, MBeanServer server)  {

        // Note that when using standard metadata,
        // the returned object must implement the "RadiusDynAuthClientScalarsMBean"
        // interface.
        //
        if (server != null) 
            return new RadiusDynAuthClientScalars(this,server);
        else 
            return new RadiusDynAuthClientScalars(this);
    }


    // ------------------------------------------------------------
    // 
    // Implements the "registerTableMeta" method defined in "SnmpMib".
    // See the "SnmpMib" Javadoc API for more details.
    // 
    // ------------------------------------------------------------

    public void registerTableMeta( String name, SnmpMibTable meta) {
        if (metadatas == null) return;
        if (name == null) return;
        metadatas.put(name,meta);
    }


    // ------------------------------------------------------------
    // 
    // Implements the "getRegisteredTableMeta" method defined in "SnmpMib".
    // See the "SnmpMib" Javadoc API for more details.
    // 
    // ------------------------------------------------------------

    public SnmpMibTable getRegisteredTableMeta( String name ) {
        if (metadatas == null) return null;
        if (name == null) return null;
        return (SnmpMibTable) metadatas.get(name);
    }

    public SnmpStandardObjectServer getStandardObjectServer() {
        if (objectserver == null) 
            objectserver = new SnmpStandardObjectServer();
        return objectserver;
    }

    private boolean isInitialized = false;

    protected SnmpStandardObjectServer objectserver;

    protected final Hashtable metadatas = new Hashtable();
}
