package com.elitecore.commons.base;

/**
 * Determines output value based on input value. Function as in function in functional
 * programming.
 * 
 * @param <F> input type
 * @param <T> output type
 * 
 * @author narendra.pathai
 */
public interface Function<F, T> {

	/**
	 * Returns the result of applying the function on {@code input}.
	 * 
	 * @param input value on which function is to be applied
	 * @return the output generated by applying function on {@code input}
	 */
	public T apply(F input);
	
}
