<%@ page errorPage="/jsp/dashboardwidgets/WidgetsErrorHandler.jsp" %>

<LINK REL ="stylesheet" TYPE="text/css" HREF="${pageContext.request.contextPath}/css/dashboard/widjettable.css"/>
<%String authServiceWidgetId = request.getParameter("widgetId");%>
<div id="radAuthService" style="overflow: auto;" class="widget-class">
	<div id="progressDivId<%=authServiceWidgetId%>" style="height: 200px;width: 100%;display: table;background-position: center;vertical-align: middle;text-align:center; " align="center">
 		<div style="display: table-cell;vertical-align: middle;">
 			<img src="<%=request.getContextPath()%>/images/loading1.gif" align="center" style="vertical-align: middle;"/>
 		</div>
	</div>
</div>	
<span id="exportbtn_<%=authServiceWidgetId%>"></span>
<input type="hidden" name="editJsp" value="jsp/dashboardwidgets/aaawidgets/EditAuthServiceTableWidget.jsp?widgetId=<%=authServiceWidgetId%>" id="editJsp">

<script>
var authServiceWidgetId=<%=authServiceWidgetId%>;
var confObj = getWidgetConfiguration(<%=authServiceWidgetId%>);  <%-- Use ConfObj to retrive configuration --%>
var interval = 1;
var aaaServerIds =""; 
var authServerName = "";
if(confObj != null) {
	interval =  confObj.get("REFRESHINTERVAL");
	aaaServerIds = confObj.get("ELITEAAAINSTANCES");
	authServerName= confObj.get("NAME");
}

var parentID = "radAuthService_" + <%=authServiceWidgetId%> + "_" +  new Date().getTime();  //  $('#radAuthService').parent().parent().attr("id");
$('#radAuthService').attr("id", parentID);
var data = {
		header : {
			id : parentID,
			type : "RAD_AUTH_SERV"
		},
		body : {
			interval : interval,
			aaaServerIds:aaaServerIds
		}
};
	
getDashBoardSocket().register($("#"+parentID).createDefaultTableWidget(interval));
getDashBoardSocket().sendRequest(data);


$('#exportbtn_'+<%=authServiceWidgetId%>).click(function(){
	var pageIndex=1;
	var authenticationServerArray = getAuthenticationServiceDataDetails();
	
	//Generate PDF in Landscap mode
	var authServerDoc = new jsPDF('landscape');
	
	//Set Properties to Doc files
	authServerDoc.setProperties({
        title: authServerName,
        subject: 'Widget Type Name : Generated on '+getDateTime(),           
        author: 'AutoGenerated',
        keywords: 'generated, javascript, web 2.0, ajax',
        creator: 'EliteCSM SM'
    });
	
	//create new canvas to display image
    var elitecore_image_obj = new Image();
    var canvas_obj = document.createElement("canvas");
    var context_obj = canvas_obj.getContext('2d');
    elitecore_image_obj.src = $('#elitecore_Image').attr('src');

    //set height and width of canvas object
    canvas_obj.height=77;
    canvas_obj.width=213;
    
    context_obj.drawImage(elitecore_image_obj,0,0,213,77);
    var nextcontent = canvas_obj.toDataURL('image/jpeg');
  
    authServerDoc.addImage(nextcontent, 'JPEG',5 ,1,30.43,11);
	
	authServerDoc.setFontSize(8);
	authServerDoc.setTextColor(0); 
	    
	var pageWidth= authServerDoc.internal.pageSize.width;
	var pageHeight= authServerDoc.internal.pageSize.height;
	    
	authServerDoc.text(pageWidth-50,10, "Generated on : " + getDateTime());
	    
	authServerDoc.setDrawColor(192,192,192); 
	authServerDoc.line(5,12 , pageWidth-5,12);
	     
	authServerDoc.text(pageWidth-20,pageHeight - 5, "Page : "+pageIndex );
    authServerDoc.line(5,pageHeight - 8 , pageWidth-5,pageHeight - 8);

	 authServerDoc.setDrawColor(0);
	 authServerDoc.setFillColor(1,81,152);
	 authServerDoc.rect(5, 25, pageWidth-10, 5, 'F');
	    
	 authServerDoc.setFontSize(8);
	 authServerDoc.setTextColor(255);  
	    
	 authServerDoc.text((pageWidth/2)-20, 28.5, authServerName + " Details");
	 
	 //ESI Name - Rectangle
	 authServerDoc.setDrawColor(217,230,246);
	 authServerDoc.setFillColor(217,230,246);
	 console.log("pagewidth : " +pageWidth);
	 authServerDoc.rect(5, 35, pageWidth-10, 10, 'FD');
	 
	 authServerDoc.setFontSize(7);
	
	 authServerDoc.setFontType("bold");
	 authServerDoc.setTextColor(0); 
	 var splitTitle = authServerDoc.splitTextToSize("Name", 20);
	 authServerDoc.text(11, 39, splitTitle);
	 
	 splitTitle = authServerDoc.splitTextToSize( "Access Request", 15);
	 authServerDoc.text(35, 38.5, splitTitle);
	 
	 splitTitle = authServerDoc.splitTextToSize( "Duplicate Access Request", 25);
	 authServerDoc.text(60, 38.5, splitTitle);
	 
	 splitTitle = authServerDoc.splitTextToSize( "Access Accept", 15);
	 authServerDoc.text(90, 38.5, splitTitle);
	 
	 splitTitle = authServerDoc.splitTextToSize( "Access Rejects", 15);
	 authServerDoc.text(112, 38.5, splitTitle);
	 
	 splitTitle = authServerDoc.splitTextToSize( "Access Challenges", 15);
	 authServerDoc.text(135, 38.5, splitTitle);
	 
	 splitTitle = authServerDoc.splitTextToSize( "Malformed Access Requests", 25);
	 authServerDoc.text(158, 38.5, splitTitle);
	 
	 splitTitle = authServerDoc.splitTextToSize( "Bad Authenticators", 20);
	 authServerDoc.text(192, 38.5, splitTitle);
	 
	 splitTitle = authServerDoc.splitTextToSize( "Packets Dropped", 20);
	 authServerDoc.text(222, 38.5, splitTitle);
	 
	 splitTitle = authServerDoc.splitTextToSize( "Unknown Types", 15);
	 authServerDoc.text(244, 38.5, splitTitle);
	 
	 splitTitle = authServerDoc.splitTextToSize( "Invalid Request", 15);
	 authServerDoc.text(268, 38.5, splitTitle);
	  	 
	 authServerDoc.setTextColor(0);  
	 authServerDoc.setFontType("normal");
	 var flag=1;
	    
	 var yIndex=52;
	 
	 //generate Table
	  $.each(authenticationServerArray,function(key,value){
		  if (yIndex >= pageHeight-10)
	    	{
			    authServerDoc.addPage('a4','l');
		    	yIndex = 10; // Restart height position
	    		pageWidth= authServerDoc.internal.pageSize.width;
	    		pageHeight= authServerDoc.internal.pageSize.height;
	    	    pageIndex++;
	    	    authServerDoc.text(pageWidth-20,pageHeight - 5, "Page : "+pageIndex );
	    	    authServerDoc.line(5,pageHeight - 8 , pageWidth-5,pageHeight - 8);
	    	 
	    	}  
		  
		  authServerDoc.text(11, yIndex-2, value.radiusAuthServIdent);
		  
		  var accessRequestLength = value.totalAccessRequests.toString().length;
		  var charWidth = 1.70;
		  var str = reverse(value.totalAccessRequests.toString());
		  for(var i = accessRequestLength-1 ; i >= 0 ; i--){			  
			  authServerDoc.text(43- charWidth * i, yIndex-2, str[i]);
		  }
		  
		  var dupReqLength = value.totalDupAccessRequests.toString().length;
		  str = reverse(value.totalDupAccessRequests.toString());
		  for(var i = dupReqLength-1 ; i >= 0 ; i--){			  
			  authServerDoc.text(79- charWidth * i, yIndex-2, str[i]);
		  }
		  
		  var totalAccessReqLength = value.totalAccessAccepts.toString().length;
		  str = reverse(value.totalAccessAccepts.toString());
		  for(var i = totalAccessReqLength-1 ; i >= 0 ; i--){			  
			  authServerDoc.text(97- charWidth * i, yIndex-2, str[i]);
		  }
		  
		  var totalAccessRejectsLength = value.totalAccessRejects.toString().length;
		  str = reverse(value.totalAccessRejects.toString());
		  for(var i = totalAccessRejectsLength-1 ; i >= 0 ; i--){			  
			  authServerDoc.text(119- charWidth * i, yIndex-2, str[i]);
		  }
		  
		  var totalChallengeLength = value.totalAccessChallenges.toString().length;
		  str = reverse(value.totalAccessChallenges.toString());
		  for(var i = totalChallengeLength-1 ; i >= 0 ; i--){			  
			  authServerDoc.text(147- charWidth * i, yIndex-2, str[i]);
		  }

		  var totalMalformedAccessRequestsLength = value.totalMalformedAccessRequests.toString().length;
		  str = reverse(value.totalMalformedAccessRequests.toString());
		  for(var i = totalMalformedAccessRequestsLength-1 ; i >= 0 ; i--){			  
			  authServerDoc.text(179- charWidth * i, yIndex-2, str[i]);
		  }
		  
		  var totalBadAuthenticatorsLength = value.totalBadAuthenticators.toString().length;
		  str = reverse(value.totalBadAuthenticators.toString());
		  for(var i = totalBadAuthenticatorsLength-1 ; i >= 0 ; i--){			  
			  authServerDoc.text(208- charWidth * i, yIndex-2, str[i]);
		  }
		  
		  var totalPacketsDroppedLength = value.totalPacketsDropped.toString().length;		  
		  str = reverse(value.totalPacketsDropped.toString());
		  for(var i = totalPacketsDroppedLength-1 ; i >= 0 ; i--){			  
			  authServerDoc.text(231- charWidth * i, yIndex-2, str[i]);
		  }
		  
		  var totalUnknownTypesLength = value.totalUnknownTypes.toString().length;
		  str = reverse(value.totalUnknownTypes.toString());
		  for(var i = totalUnknownTypesLength-1 ; i >= 0 ; i--){			  
			  authServerDoc.text(254- charWidth * i, yIndex-2, str[i]);
		  }

		  var totalInvalidRequestsLength = value.totalInvalidRequests.toString().length;
		  str = reverse(value.totalInvalidRequests.toString());
		  for(var i = totalInvalidRequestsLength-1 ; i >= 0 ; i--){			  
			  authServerDoc.text(276- charWidth * i, yIndex-2, str[i]);
		  }
		  
		  authServerDoc.setDrawColor(192,192,192); 
		  authServerDoc.line(5, yIndex, pageWidth-5, yIndex);
		  yIndex=yIndex+7;
		  
	  });
	 
	 var data = authServerDoc.output();
	 var buffer = new ArrayBuffer(data.length);
	 var array = new Uint8Array(buffer);

	 for (var i = 0; i < data.length; i++) {
	      array[i] = data.charCodeAt(i);
	 }

	 var blob = new Blob(
	       [array],
	       {type: 'application/pdf', encoding: 'raw'}
	 );
	
	 saveAs(blob, authServerName+'.pdf');
});

function reverse(s){
    return s.split("").reverse().join("");
}

function getAuthenticationServiceDataDetails(){
    var jResponseData="";
	$.ajax({
		url:'<%=request.getContextPath()%>/dashboardConfiguration.do?method=getAuthenticationServiceData',
	    type:'GET',
	    async:false,
	    data:{serverIds:aaaServerIds},
	    success: function(esiDataList){
	    	if(esiDataList != null)
	    	 jResponseData=esiDataList;  	
	    }
	}); 
	return jResponseData;
}
function getDateTime() {
    var now     = new Date(); 
    var year    = now.getFullYear();
    var month   = now.getMonth()+1; 
    var day     = now.getDate();
    var hour    = now.getHours();
    var minute  = now.getMinutes();
    var second  = now.getSeconds(); 
    if(month.toString().length == 1) {
        var month = '0'+month;
    }
    if(day.toString().length == 1) {
        var day = '0'+day;
    }   
    if(hour.toString().length == 1) {
        var hour = '0'+hour;
    }
    if(minute.toString().length == 1) {
        var minute = '0'+minute;
    }
    if(second.toString().length == 1) {
        var second = '0'+second;
    }   
    var dateTime = day+'/'+month+'/'+year+' '+hour+':'+minute+':'+second;   
     return dateTime;
}
</script>

