
package com.elitecore.netvertexsm.ws.cxfws.subscriberprovisioning;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import com.elitecore.netvertex.ws.subscriberprovisioningws.SubscriberProvisioningService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-01-09T15:00:10.850+05:30
 * Generated source version: 2.7.1
 * 
 */
public final class SubscriberProvisioningWS_SubscriberProvisioningWS_Client {

    private static final QName SERVICE_NAME = new QName("http://subscriberProvisioningWS.ws.netvertex.elitecore.com/", "SubscriberProvisioningService");

    private SubscriberProvisioningWS_SubscriberProvisioningWS_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SubscriberProvisioningService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SubscriberProvisioningService ss = new SubscriberProvisioningService(wsdlURL, SERVICE_NAME);
        SubscriberProvisioningWS port = ss.getSubscriberProvisioningWS();  
        
        {
        System.out.println("Invoking wsAddSubscriberBulk...");
        java.util.List<com.elitecore.netvertexsm.ws.cxfws.subscriberprovisioning.SubscriberProfile> _wsAddSubscriberBulk_subscriberProfile = null;
        java.lang.String _wsAddSubscriberBulk_parameter1 = "";
        java.lang.String _wsAddSubscriberBulk_parameter2 = "";
        com.elitecore.netvertexsm.ws.cxfws.subscriberprovisioning.SubscriberProvisioningResponse _wsAddSubscriberBulk__return = port.wsAddSubscriberBulk(_wsAddSubscriberBulk_subscriberProfile, _wsAddSubscriberBulk_parameter1, _wsAddSubscriberBulk_parameter2);
        System.out.println("wsAddSubscriberBulk.result=" + _wsAddSubscriberBulk__return);


        }
        {
        System.out.println("Invoking wsGetSubscriberProfileByID...");
        java.lang.String _wsGetSubscriberProfileByID_subscriberID = "";
        java.lang.String _wsGetSubscriberProfileByID_parameter1 = "";
        java.lang.String _wsGetSubscriberProfileByID_parameter2 = "";
        com.elitecore.netvertexsm.ws.cxfws.subscriberprovisioning.SubscriberProvisioningResponse _wsGetSubscriberProfileByID__return = port.wsGetSubscriberProfileByID(_wsGetSubscriberProfileByID_subscriberID, _wsGetSubscriberProfileByID_parameter1, _wsGetSubscriberProfileByID_parameter2);
        System.out.println("wsGetSubscriberProfileByID.result=" + _wsGetSubscriberProfileByID__return);


        }
        {
        System.out.println("Invoking wsDeleteSubscriberProfile...");
        java.lang.String _wsDeleteSubscriberProfile_subscriberID = "";
        java.lang.String _wsDeleteSubscriberProfile_parameter1 = "";
        java.lang.String _wsDeleteSubscriberProfile_parameter2 = "";
        com.elitecore.netvertexsm.ws.cxfws.subscriberprovisioning.SubscriberProvisioningResponse _wsDeleteSubscriberProfile__return = port.wsDeleteSubscriberProfile(_wsDeleteSubscriberProfile_subscriberID, _wsDeleteSubscriberProfile_parameter1, _wsDeleteSubscriberProfile_parameter2);
        System.out.println("wsDeleteSubscriberProfile.result=" + _wsDeleteSubscriberProfile__return);


        }
        {
        System.out.println("Invoking wsUpdateSubscriberProfile...");
        com.elitecore.netvertexsm.ws.cxfws.subscriberprovisioning.WsUpdateSubscriberProfile.SubscriberProfile _wsUpdateSubscriberProfile_subscriberProfile = null;
        java.lang.String _wsUpdateSubscriberProfile_subscriberID = "";
        java.lang.String _wsUpdateSubscriberProfile_parameter1 = "";
        java.lang.String _wsUpdateSubscriberProfile_parameter2 = "";
        com.elitecore.netvertexsm.ws.cxfws.subscriberprovisioning.SubscriberProvisioningResponse _wsUpdateSubscriberProfile__return = port.wsUpdateSubscriberProfile(_wsUpdateSubscriberProfile_subscriberProfile, _wsUpdateSubscriberProfile_subscriberID, _wsUpdateSubscriberProfile_parameter1, _wsUpdateSubscriberProfile_parameter2);
        System.out.println("wsUpdateSubscriberProfile.result=" + _wsUpdateSubscriberProfile__return);


        }
        {
        System.out.println("Invoking wsAddSubscriberProfile...");
        com.elitecore.netvertexsm.ws.cxfws.subscriberprovisioning.WsAddSubscriberProfile.SubscriberProfile _wsAddSubscriberProfile_subscriberProfile = null;
        java.lang.String _wsAddSubscriberProfile_parameter1 = "";
        java.lang.String _wsAddSubscriberProfile_parameter2 = "";
        com.elitecore.netvertexsm.ws.cxfws.subscriberprovisioning.SubscriberProvisioningResponse _wsAddSubscriberProfile__return = port.wsAddSubscriberProfile(_wsAddSubscriberProfile_subscriberProfile, _wsAddSubscriberProfile_parameter1, _wsAddSubscriberProfile_parameter2);
        System.out.println("wsAddSubscriberProfile.result=" + _wsAddSubscriberProfile__return);


        }
        {
        System.out.println("Invoking wsListSubscriberProfiles...");
        com.elitecore.netvertexsm.ws.cxfws.subscriberprovisioning.WsListSubscriberProfiles.SubscriberProfileCriteria _wsListSubscriberProfiles_subscriberProfileCriteria = null;
        java.lang.String _wsListSubscriberProfiles_parameter1 = "";
        java.lang.String _wsListSubscriberProfiles_parameter2 = "";
        com.elitecore.netvertexsm.ws.cxfws.subscriberprovisioning.SubscriberProvisioningResponse _wsListSubscriberProfiles__return = port.wsListSubscriberProfiles(_wsListSubscriberProfiles_subscriberProfileCriteria, _wsListSubscriberProfiles_parameter1, _wsListSubscriberProfiles_parameter2);
        System.out.println("wsListSubscriberProfiles.result=" + _wsListSubscriberProfiles__return);


        }

        System.exit(0);
    }

}
