package com.elitecore.diameterapi.mibs.custom.autogen;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling DIAMETER-STACK-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "AppWiseStatisticsEntry" MBean.
 */
public interface AppWiseStatisticsEntryMBean {

    /**
     * Getter for the "AppwUnknownHbHAnswerDropped" variable.
     */
    public Long getAppwUnknownHbHAnswerDropped() throws SnmpStatusException;

    /**
     * Getter for the "AppwAnswerDr" variable.
     */
    public Long getAppwAnswerDr() throws SnmpStatusException;

    /**
     * Getter for the "AppwCompstIndexValue" variable.
     */
    public String getAppwCompstIndexValue() throws SnmpStatusException;

    /**
     * Getter for the "AppwRequestDr" variable.
     */
    public Long getAppwRequestDr() throws SnmpStatusException;

    /**
     * Getter for the "AppwRequestTimeOut" variable.
     */
    public Long getAppwRequestTimeOut() throws SnmpStatusException;

    /**
     * Getter for the "AppwApplicationName" variable.
     */
    public String getAppwApplicationName() throws SnmpStatusException;

    /**
     * Getter for the "AppwPeerIdentity" variable.
     */
    public String getAppwPeerIdentity() throws SnmpStatusException;

    /**
     * Getter for the "AppwRequestRetransmitted" variable.
     */
    public Long getAppwRequestRetransmitted() throws SnmpStatusException;

    /**
     * Getter for the "AppwAnswerRx" variable.
     */
    public Long getAppwAnswerRx() throws SnmpStatusException;

    /**
     * Getter for the "AppwRequestPn" variable.
     */
    public Long getAppwRequestPn() throws SnmpStatusException;

    /**
     * Getter for the "AppwRequestTx" variable.
     */
    public Long getAppwRequestTx() throws SnmpStatusException;

    /**
     * Getter for the "AppwMalformedPacketRx" variable.
     */
    public Long getAppwMalformedPacketRx() throws SnmpStatusException;

    /**
     * Getter for the "AppwDuplicateEtEAnswer" variable.
     */
    public Long getAppwDuplicateEtEAnswer() throws SnmpStatusException;

    /**
     * Getter for the "AppwAnswerTx" variable.
     */
    public Long getAppwAnswerTx() throws SnmpStatusException;

    /**
     * Getter for the "AppwRequestRx" variable.
     */
    public Long getAppwRequestRx() throws SnmpStatusException;

    /**
     * Getter for the "AppwDuplicateRequest" variable.
     */
    public Long getAppwDuplicateRequest() throws SnmpStatusException;

    /**
     * Getter for the "PeerIndex" variable.
     */
    public Long getPeerIndex() throws SnmpStatusException;

    /**
     * Getter for the "ApplicationID" variable.
     */
    public Long getApplicationID() throws SnmpStatusException;

}
