package com.elitecore.diameterapi.mibs.custom.autogen;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling DIAMETER-STACK-MIB.
//

// java imports
//
import java.io.Serializable;

import javax.management.MBeanServer;

import com.sun.management.snmp.SnmpStatusException;
import com.sun.management.snmp.agent.SnmpMib;
// jmx imports
//
// jdmk imports
//

/**
 * The class is used for implementing the "CommandCodeWiseStatistics" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.21067.5.102.3.2.
 */
public class CommandCodeWiseStatistics implements CommandCodeWiseStatisticsMBean, Serializable {

    /**
     * Variable for storing the value of "CommandCodeStatisticsTable".
     * The variable is identified by: "1.3.6.1.4.1.21067.5.102.3.2.1".
     *
     * " Table represents the commandCode to peer wise
     * statistics"
     *
     */
    protected TableCommandCodeStatisticsTable CommandCodeStatisticsTable;


    public CommandCodeWiseStatistics() {
    }
    /**
     * Constructor for the "CommandCodeWiseStatistics" group.
     * If the group contains a table, the entries created through an SNMP SET will not be registered in Java DMK.
     */
    public CommandCodeWiseStatistics(SnmpMib myMib) {
        CommandCodeStatisticsTable = new TableCommandCodeStatisticsTable (myMib);
    }


    /**
     * Constructor for the "CommandCodeWiseStatistics" group.
     * If the group contains a table, the entries created through an SNMP SET will be AUTOMATICALLY REGISTERED in Java DMK.
     */
    public CommandCodeWiseStatistics(SnmpMib myMib, MBeanServer server) {
        CommandCodeStatisticsTable = new TableCommandCodeStatisticsTable (myMib, server);
    }

    /**
     * Access the "CommandCodeStatisticsTable" variable.
     */
    public TableCommandCodeStatisticsTable accessCommandCodeStatisticsTable() throws SnmpStatusException {
        return CommandCodeStatisticsTable;
    }

    /**
     * Access the "CommandCodeStatisticsTable" variable as a bean indexed property.
     */
    public CommandCodeStatisticsEntryMBean[] getCommandCodeStatisticsTable() throws SnmpStatusException {
        return CommandCodeStatisticsTable.getEntries();
    }

}
