package com.elitecore.core.serverx.snmp.mib.mib2.autogen;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling RFC1213-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "EgpNeighEntry" MBean.
 */
public interface EgpNeighEntryMBean {

    /**
     * Getter for the "EgpNeighOutErrMsgs" variable.
     */
    public Long getEgpNeighOutErrMsgs() throws SnmpStatusException;

    /**
     * Getter for the "EgpNeighInErrMsgs" variable.
     */
    public Long getEgpNeighInErrMsgs() throws SnmpStatusException;

    /**
     * Getter for the "EgpNeighOutErrs" variable.
     */
    public Long getEgpNeighOutErrs() throws SnmpStatusException;

    /**
     * Getter for the "EgpNeighEventTrigger" variable.
     */
    public EnumEgpNeighEventTrigger getEgpNeighEventTrigger() throws SnmpStatusException;

    /**
     * Setter for the "EgpNeighEventTrigger" variable.
     */
    public void setEgpNeighEventTrigger(EnumEgpNeighEventTrigger x) throws SnmpStatusException;

    /**
     * Checker for the "EgpNeighEventTrigger" variable.
     */
    public void checkEgpNeighEventTrigger(EnumEgpNeighEventTrigger x) throws SnmpStatusException;

    /**
     * Getter for the "EgpNeighOutMsgs" variable.
     */
    public Long getEgpNeighOutMsgs() throws SnmpStatusException;

    /**
     * Getter for the "EgpNeighMode" variable.
     */
    public EnumEgpNeighMode getEgpNeighMode() throws SnmpStatusException;

    /**
     * Getter for the "EgpNeighInErrs" variable.
     */
    public Long getEgpNeighInErrs() throws SnmpStatusException;

    /**
     * Getter for the "EgpNeighIntervalPoll" variable.
     */
    public Integer getEgpNeighIntervalPoll() throws SnmpStatusException;

    /**
     * Getter for the "EgpNeighInMsgs" variable.
     */
    public Long getEgpNeighInMsgs() throws SnmpStatusException;

    /**
     * Getter for the "EgpNeighAs" variable.
     */
    public Integer getEgpNeighAs() throws SnmpStatusException;

    /**
     * Getter for the "EgpNeighIntervalHello" variable.
     */
    public Integer getEgpNeighIntervalHello() throws SnmpStatusException;

    /**
     * Getter for the "EgpNeighAddr" variable.
     */
    public String getEgpNeighAddr() throws SnmpStatusException;

    /**
     * Getter for the "EgpNeighStateDowns" variable.
     */
    public Long getEgpNeighStateDowns() throws SnmpStatusException;

    /**
     * Getter for the "EgpNeighStateUps" variable.
     */
    public Long getEgpNeighStateUps() throws SnmpStatusException;

    /**
     * Getter for the "EgpNeighState" variable.
     */
    public EnumEgpNeighState getEgpNeighState() throws SnmpStatusException;

}
