package com.elitecore.core.serverx.snmp.mib.mib2.autogen;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling RFC1213-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "Udp" MBean.
 */
public interface UdpMBean {

    /**
     * Access the "UdpTable" variable.
     */
    public TableUdpTable accessUdpTable() throws SnmpStatusException;

    /**
     * Getter for the "UdpOutDatagrams" variable.
     */
    public Long getUdpOutDatagrams() throws SnmpStatusException;

    /**
     * Getter for the "UdpInErrors" variable.
     */
    public Long getUdpInErrors() throws SnmpStatusException;

    /**
     * Getter for the "UdpNoPorts" variable.
     */
    public Long getUdpNoPorts() throws SnmpStatusException;

    /**
     * Getter for the "UdpInDatagrams" variable.
     */
    public Long getUdpInDatagrams() throws SnmpStatusException;

}
