package com.elitecore.aaa.rm.service.ippool.snmp.autogen;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling IP-POOL-SERVICE-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "IpPoolNASClientEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.21067.1.7.1.102.1.
 */
public class IpPoolNASClientEntry implements IpPoolNASClientEntryMBean, Serializable {

    /**
     * Variable for storing the value of "NasIPAddressOfferResponse".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.7.1.102.1.9".
     *
     * "Total No. of Access Accept sent by IP-Pool service to NAS Client"
     *
     */
    protected Long NasIPAddressOfferResponse = new Long(1);

    /**
     * Variable for storing the value of "NasIPAddressDiscoverRequest".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.7.1.102.1.8".
     *
     * "Total No. of Access Request received by IP-Pool service from NAS Client"
     *
     */
    protected Long NasIPAddressDiscoverRequest = new Long(1);

    /**
     * Variable for storing the value of "NasIPAddressInvalidRequest".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.7.1.102.1.7".
     *
     * "Total No. of invalid Radius request received by IP-Pool service from NAS Client "
     *
     */
    protected Long NasIPAddressInvalidRequest = new Long(1);

    /**
     * Variable for storing the value of "NasIPAddressUnknownPacket".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.7.1.102.1.6".
     *
     * "Total No. of Unknown Radius Packet received by IP-Pool service from NAS Client"
     *
     */
    protected Long NasIPAddressUnknownPacket = new Long(1);

    /**
     * Variable for storing the value of "NasIPAddressRequestDropped".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.7.1.102.1.5".
     *
     * "Total No. of packets dropped by IP-Pool service received from NAS Client"
     *
     */
    protected Long NasIPAddressRequestDropped = new Long(1);

    /**
     * Variable for storing the value of "NasIPAddressUpdateRequest".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.7.1.102.1.13".
     *
     * "Total No. of Accounting Update received by IP-Pool service from NAS Client"
     *
     */
    protected Long NasIPAddressUpdateRequest = new Long(1);

    /**
     * Variable for storing the value of "NasIPAddressResponses".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.7.1.102.1.4".
     *
     * "Total No. of Access Accept response sent by IP-Pool service to NAS Client"
     *
     */
    protected Long NasIPAddressResponses = new Long(1);

    /**
     * Variable for storing the value of "NasIPAddressRequest".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.7.1.102.1.3".
     *
     * "Total No. of Access Request received by IP-Pool service from NAS Client"
     *
     */
    protected Long NasIPAddressRequest = new Long(1);

    /**
     * Variable for storing the value of "NasIPAddressReleaseRequest".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.7.1.102.1.12".
     *
     * "Total No. of Accounting Stop reponse sent by IP-Pool service to NAS Client"
     *
     */
    protected Long NasIPAddressReleaseRequest = new Long(1);

    /**
     * Variable for storing the value of "NasID".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.7.1.102.1.2".
     *
     * "Represent the NAS identifier of NAS Client"
     *
     */
    protected String NasID = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "NasIPAddressAllocationRequest".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.7.1.102.1.11".
     *
     * "Total No. of Accounting Start Request received by IP-Pool service from NAS Client"
     *
     */
    protected Long NasIPAddressAllocationRequest = new Long(1);

    /**
     * Variable for storing the value of "NasIPAddressDeclineResponse".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.7.1.102.1.10".
     *
     * "Total No. of Access Reject Response sent by IP-Pool service to NAS Client"
     *
     */
    protected Long NasIPAddressDeclineResponse = new Long(1);

    /**
     * Variable for storing the value of "IpPoolNASClientIndex".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.7.1.102.1.1".
     *
     * "A number uniquely identifying each NAS Client with which IP-Pool server communicates"
     *
     */
    protected Integer IpPoolNASClientIndex = new Integer(1);

    public IpPoolNASClientEntry() {
		// TODO Auto-generated constructor stub
	}
    /**
     * Constructor for the "IpPoolNASClientEntry" group.
     */
    public IpPoolNASClientEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "NasIPAddressOfferResponse" variable.
     */
    public Long getNasIPAddressOfferResponse() throws SnmpStatusException {
        return NasIPAddressOfferResponse;
    }

    /**
     * Getter for the "NasIPAddressDiscoverRequest" variable.
     */
    public Long getNasIPAddressDiscoverRequest() throws SnmpStatusException {
        return NasIPAddressDiscoverRequest;
    }

    /**
     * Getter for the "NasIPAddressInvalidRequest" variable.
     */
    public Long getNasIPAddressInvalidRequest() throws SnmpStatusException {
        return NasIPAddressInvalidRequest;
    }

    /**
     * Getter for the "NasIPAddressUnknownPacket" variable.
     */
    public Long getNasIPAddressUnknownPacket() throws SnmpStatusException {
        return NasIPAddressUnknownPacket;
    }

    /**
     * Getter for the "NasIPAddressRequestDropped" variable.
     */
    public Long getNasIPAddressRequestDropped() throws SnmpStatusException {
        return NasIPAddressRequestDropped;
    }

    /**
     * Getter for the "NasIPAddressUpdateRequest" variable.
     */
    public Long getNasIPAddressUpdateRequest() throws SnmpStatusException {
        return NasIPAddressUpdateRequest;
    }

    /**
     * Getter for the "NasIPAddressResponses" variable.
     */
    public Long getNasIPAddressResponses() throws SnmpStatusException {
        return NasIPAddressResponses;
    }

    /**
     * Getter for the "NasIPAddressRequest" variable.
     */
    public Long getNasIPAddressRequest() throws SnmpStatusException {
        return NasIPAddressRequest;
    }

    /**
     * Getter for the "NasIPAddressReleaseRequest" variable.
     */
    public Long getNasIPAddressReleaseRequest() throws SnmpStatusException {
        return NasIPAddressReleaseRequest;
    }

    /**
     * Getter for the "NasID" variable.
     */
    public String getNasID() throws SnmpStatusException {
        return NasID;
    }

    /**
     * Getter for the "NasIPAddressAllocationRequest" variable.
     */
    public Long getNasIPAddressAllocationRequest() throws SnmpStatusException {
        return NasIPAddressAllocationRequest;
    }

    /**
     * Getter for the "NasIPAddressDeclineResponse" variable.
     */
    public Long getNasIPAddressDeclineResponse() throws SnmpStatusException {
        return NasIPAddressDeclineResponse;
    }

    /**
     * Getter for the "IpPoolNASClientIndex" variable.
     */
    public Integer getIpPoolNASClientIndex() throws SnmpStatusException {
        return IpPoolNASClientIndex;
    }

}
