package com.elitecore.aaa.mibs.rm.charging.client.snmp.autogen;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling CHARGING-SERVICE-CLIENT-MIB.
//

// java imports
//
import java.io.Serializable;

import com.sun.management.snmp.SnmpStatusException;
import com.sun.management.snmp.agent.SnmpMib;
// jmx imports
//
// jdmk imports
//

/**
 * The class is used for implementing the "ChargingServerEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.21067.1.8.2.2.1.1.
 */
public class ChargingServerEntry implements ChargingServerEntryMBean, Serializable {

    /**
     * Variable for storing the value of "ChargingRequestRetransmission".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.8.2.2.1.1.9".
     *
     * "Total No. of Request Timeout by charging server"
     *
     */
    protected Long ChargingRequestRetransmission = new Long(1);

    /**
     * Variable for storing the value of "ChargingRequestTimeout".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.8.2.2.1.1.8".
     *
     * "Total No. of Request Timeout by charging server"
     *
     */
    protected Long ChargingRequestTimeout = new Long(1);

    /**
     * Variable for storing the value of "ChargingAcctUpdateRequest".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.8.2.2.1.1.17".
     *
     * "Total No. of Accouting update Request received by charging server"
     *
     */
    protected Long ChargingAcctUpdateRequest = new Long(1);

    /**
     * Variable for storing the value of "ChargingUnknownTypes".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.8.2.2.1.1.7".
     *
     * "Total No. of unknown Request received by charging server"
     *
     */
    protected Long ChargingUnknownTypes = new Long(1);

    /**
     * Variable for storing the value of "ChargingAcctStopRequest".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.8.2.2.1.1.16".
     *
     * "Total No. of Accouting stop Request received by charging server"
     *
     */
    protected Long ChargingAcctStopRequest = new Long(1);

    /**
     * Variable for storing the value of "ChargingAcctStartRequest".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.8.2.2.1.1.15".
     *
     * "Total No. of Accouting start Request received by charging server"
     *
     */
    protected Long ChargingAcctStartRequest = new Long(1);

    /**
     * Variable for storing the value of "ChargingPacketsDropped".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.8.2.2.1.1.6".
     *
     * "Total No. of packet Dropped by charging server"
     *
     */
    protected Long ChargingPacketsDropped = new Long(1);

    /**
     * Variable for storing the value of "ChargingResponses".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.8.2.2.1.1.5".
     *
     * "Total No. of Response given by charging server"
     *
     */
    protected Long ChargingResponses = new Long(1);

    /**
     * Variable for storing the value of "ChargingAcctResponse".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.8.2.2.1.1.14".
     *
     * "Total No. of Accouting Response given by charging server"
     *
     */
    protected Long ChargingAcctResponse = new Long(1);

    /**
     * Variable for storing the value of "ChargingAcctRequest".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.8.2.2.1.1.13".
     *
     * "Total No. of Accouting Request received by charging server"
     *
     */
    protected Long ChargingAcctRequest = new Long(1);

    /**
     * Variable for storing the value of "ChargingRequests".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.8.2.2.1.1.4".
     *
     * "Total No. of Request received by charging server"
     *
     */
    protected Long ChargingRequests = new Long(1);

    /**
     * Variable for storing the value of "ChargingAccessReject".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.8.2.2.1.1.12".
     *
     * "Total No. of Access reject given by charging service to Client"
     *
     */
    protected Long ChargingAccessReject = new Long(1);

    /**
     * Variable for storing the value of "ChargingServerAddress".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.8.2.2.1.1.3".
     *
     * "Represent identifier of charging server address"
     *
     */
    protected String ChargingServerAddress = new String("192.9.9.100");

    /**
     * Variable for storing the value of "ChargingAccessAccept".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.8.2.2.1.1.11".
     *
     * "Total No. of Access Accept given by charging service to Client"
     *
     */
    protected Long ChargingAccessAccept = new Long(1);

    /**
     * Variable for storing the value of "ChargingServerName".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.8.2.2.1.1.2".
     *
     * "Represent identifier of charging server Identity"
     *
     */
    protected String ChargingServerName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "ChargingAccessRequest".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.8.2.2.1.1.10".
     *
     * "Total No. of Access Request received by charging server"
     *
     */
    protected Long ChargingAccessRequest = new Long(1);

    /**
     * Variable for storing the value of "ChargingServerIndex".
     * The variable is identified by: "1.3.6.1.4.1.21067.1.8.2.2.1.1.1".
     *
     * "A number uniquely identifying each Charging server"
     *
     */
    protected Integer ChargingServerIndex = new Integer(1);

    public ChargingServerEntry() {
		// TODO Auto-generated constructor stub
	}
    
    /**
     * Constructor for the "ChargingServerEntry" group.
     */
    public ChargingServerEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "ChargingRequestRetransmission" variable.
     */
    public Long getChargingRequestRetransmission() throws SnmpStatusException {
        return ChargingRequestRetransmission;
    }

    /**
     * Getter for the "ChargingRequestTimeout" variable.
     */
    public Long getChargingRequestTimeout() throws SnmpStatusException {
        return ChargingRequestTimeout;
    }

    /**
     * Getter for the "ChargingAcctUpdateRequest" variable.
     */
    public Long getChargingAcctUpdateRequest() throws SnmpStatusException {
        return ChargingAcctUpdateRequest;
    }

    /**
     * Getter for the "ChargingUnknownTypes" variable.
     */
    public Long getChargingUnknownTypes() throws SnmpStatusException {
        return ChargingUnknownTypes;
    }

    /**
     * Getter for the "ChargingAcctStopRequest" variable.
     */
    public Long getChargingAcctStopRequest() throws SnmpStatusException {
        return ChargingAcctStopRequest;
    }

    /**
     * Getter for the "ChargingAcctStartRequest" variable.
     */
    public Long getChargingAcctStartRequest() throws SnmpStatusException {
        return ChargingAcctStartRequest;
    }

    /**
     * Getter for the "ChargingPacketsDropped" variable.
     */
    public Long getChargingPacketsDropped() throws SnmpStatusException {
        return ChargingPacketsDropped;
    }

    /**
     * Getter for the "ChargingResponses" variable.
     */
    public Long getChargingResponses() throws SnmpStatusException {
        return ChargingResponses;
    }

    /**
     * Getter for the "ChargingAcctResponse" variable.
     */
    public Long getChargingAcctResponse() throws SnmpStatusException {
        return ChargingAcctResponse;
    }

    /**
     * Getter for the "ChargingAcctRequest" variable.
     */
    public Long getChargingAcctRequest() throws SnmpStatusException {
        return ChargingAcctRequest;
    }

    /**
     * Getter for the "ChargingRequests" variable.
     */
    public Long getChargingRequests() throws SnmpStatusException {
        return ChargingRequests;
    }

    /**
     * Getter for the "ChargingAccessReject" variable.
     */
    public Long getChargingAccessReject() throws SnmpStatusException {
        return ChargingAccessReject;
    }

    /**
     * Getter for the "ChargingServerAddress" variable.
     */
    public String getChargingServerAddress() throws SnmpStatusException {
        return ChargingServerAddress;
    }

    /**
     * Getter for the "ChargingAccessAccept" variable.
     */
    public Long getChargingAccessAccept() throws SnmpStatusException {
        return ChargingAccessAccept;
    }

    /**
     * Getter for the "ChargingServerName" variable.
     */
    public String getChargingServerName() throws SnmpStatusException {
        return ChargingServerName;
    }

    /**
     * Getter for the "ChargingAccessRequest" variable.
     */
    public Long getChargingAccessRequest() throws SnmpStatusException {
        return ChargingAccessRequest;
    }

    /**
     * Getter for the "ChargingServerIndex" variable.
     */
    public Integer getChargingServerIndex() throws SnmpStatusException {
        return ChargingServerIndex;
    }

}
