package com.elitecore.nvsmx.snmp.mib.webservice.extended.resetws;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling NETVERTEX-PCRF-MIB.
//

// java imports
//
import com.elitecore.nvsmx.snmp.mib.webservice.autogencode.ResetUsageWSMethodWiseEntry;
import com.elitecore.nvsmx.ws.interceptor.WebServiceStatistics;
import com.sun.management.snmp.SnmpStatusException;
 
public class ResetUsageWSMethodWiseEntryImpl extends ResetUsageWSMethodWiseEntry{

	private static final long serialVersionUID = 1L;
	private WebServiceStatistics webServiceStatistics;
	private Integer methodIndex;
	private String methodName;
	
    public ResetUsageWSMethodWiseEntryImpl(Integer methodIndex, String methodName, WebServiceStatistics webServiceStatistics) {
    	this.methodIndex = methodIndex;
    	this.methodName = methodName;
    	this.webServiceStatistics = webServiceStatistics;
    }

    @Override
    public Long getResetUsageWSMethodAvgTPS() throws SnmpStatusException {
        return webServiceStatistics.getTPS();
    }

    @Override
    public Long getResetUsageWSMethodLastMinuteTotalRequests() throws SnmpStatusException {
    	return webServiceStatistics.getLastMinutesTotalRequest();
    }
    
    @Override
    public Long getResetUsageWSMethodTotalResponses() throws SnmpStatusException {
    	return webServiceStatistics.getTotalRequestCounter();
    }

    @Override
    public Long getResetUsageWSMethodTotalRequests() throws SnmpStatusException {
    	return webServiceStatistics.getTotalRequestCounter();
    }

    @Override
    public String getResetUsageWSMethodName() throws SnmpStatusException {
    	return methodName;
    }

    @Override
    public Integer getResetUsageWSMethodIndex() throws SnmpStatusException {
    	return methodIndex;
    }

}
