package com.elitecore.nvsmx.snmp.mib.webservice.extended.subscriptionws;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling NETVERTEX-PCRF-MIB.
//

// java imports
//
import com.elitecore.nvsmx.snmp.mib.webservice.autogencode.SubscriptionWSMethodWiseEntry;
import com.elitecore.nvsmx.ws.interceptor.WebServiceStatistics;
import com.sun.management.snmp.SnmpStatusException;

public class SubscriptionWSMethodWiseEntryImpl extends SubscriptionWSMethodWiseEntry{

	private static final long serialVersionUID = 1L;

	private WebServiceStatistics webServiceStatistics;
	private Integer methodIndex;
	private String methodName;
	
    public SubscriptionWSMethodWiseEntryImpl(Integer methodIndex, String methodName, WebServiceStatistics webServiceStatistics) {
    	this.methodIndex = methodIndex;
		this.methodName = methodName;
		this.webServiceStatistics = webServiceStatistics;
    }

    @Override
    public Long getSubscriptionWSMethodAvgTPS() throws SnmpStatusException {
        return webServiceStatistics.getTPS();
    }

    @Override
    public Long getSubscriptionWSMethodLastMinuteTotalRequests() throws SnmpStatusException {
    	return webServiceStatistics.getLastMinutesTotalRequest();
    }

    @Override
    public Long getSubscriptionWSMethodTotalResponses() throws SnmpStatusException {
    	return webServiceStatistics.getTotalResponseCounter();
    }

    @Override
    public Long getSubscriptionWSMethodTotalRequests() throws SnmpStatusException {
    	return webServiceStatistics.getTotalRequestCounter();
    }

    @Override
    public String getSubscriptionWSMethodName() throws SnmpStatusException {
        return methodName;
    }

    @Override
    public Integer getSubscriptionWSMethodIndex() throws SnmpStatusException {
        return methodIndex;
    }

}
