package com.elitecore.nvsmx.snmp.mib.webservice.extended.sessionws;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling NETVERTEX-PCRF-MIB.
//

// java imports
//
import com.elitecore.nvsmx.snmp.mib.webservice.autogencode.SessionManagementWSMethodWiseEntry;
import com.elitecore.nvsmx.ws.interceptor.WebServiceStatistics;
import com.sun.management.snmp.SnmpStatusException;
 
public class SessionManagementWSMethodWiseEntryImpl extends SessionManagementWSMethodWiseEntry{
 
	private static final long serialVersionUID = 1L;

	private WebServiceStatistics webServiceStatistics;
	private Integer methodIndex;
	private String methodName;
	
	public SessionManagementWSMethodWiseEntryImpl(Integer methodIndex, String methodName, WebServiceStatistics webServiceStatistics) {
		this.methodIndex = methodIndex;
		this.methodName = methodName;
		this.webServiceStatistics = webServiceStatistics;
    }

	@Override
    public Long getSessionWSMethodAvgTPS() throws SnmpStatusException {
        return webServiceStatistics.getTPS();
    }

	@Override
    public Long getSessionWSMethodLastMinuteTotalRequests() throws SnmpStatusException {
    	return webServiceStatistics.getLastMinutesTotalRequest();
    }

	@Override
    public Long getSessionWSMethodTotalResponses() throws SnmpStatusException {
    	return webServiceStatistics.getTotalResponseCounter();
    }

	@Override
    public Long getSessionWSMethodTotalRequests() throws SnmpStatusException {
    	return webServiceStatistics.getTotalRequestCounter();
    }

	@Override
    public String getSessionWSMethodName() throws SnmpStatusException {
    	return methodName;
    }

	@Override
    public Integer getSessionWSMethodIndex() throws SnmpStatusException {
        return methodIndex;
    }

}
