package com.elitecore.core.serverx.snmp.mib.jvm.autogen;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling JVM-MANAGEMENT-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "JvmMemMgrPoolRelEntry" MBean.
 */
public interface JvmMemMgrPoolRelEntryMBean {

    /**
     * Getter for the "JvmMemMgrRelPoolName" variable.
     */
    public Byte[] getJvmMemMgrRelPoolName() throws SnmpStatusException;

    /**
     * Getter for the "JvmMemMgrRelManagerName" variable.
     */
    public Byte[] getJvmMemMgrRelManagerName() throws SnmpStatusException;

    /**
     * Getter for the "JvmMemManagerIndex" variable.
     */
    public Integer getJvmMemManagerIndex() throws SnmpStatusException;

    /**
     * Getter for the "JvmMemPoolIndex" variable.
     */
    public Integer getJvmMemPoolIndex() throws SnmpStatusException;

}
