package com.elitecore.netvertex.core.snmp.mib.netvertexpcrf.autogencode;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling NETVERTEX-PCRF-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "ResetUsageWSResetBillingCycleResultCodeEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.21067.4.1.3.12.7.1.
 */
public class ResetUsageWSResetBillingCycleResultCodeEntry implements ResetUsageWSResetBillingCycleResultCodeEntryMBean, Serializable {

    /**
     * Variable for storing the value of "ResetUsageWSResetBillingCycleResultCodeCounters".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.12.7.1.3".
     *
     * "ResetUsageWS method wsResetBillingCycle ResultCode Specific statistics."
     *
     */
    protected Long ResetUsageWSResetBillingCycleResultCodeCounters = new Long(1);

    /**
     * Variable for storing the value of "ResetUsageWSResetBillingCycleResultCodeName".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.12.7.1.2".
     *
     * "ResetUsageWS method wsResetBillingCycle ResultCode Name."
     *
     */
    protected String ResetUsageWSResetBillingCycleResultCodeName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "ResetUsageWSResetBillingCycleResultCode".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.12.7.1.1".
     *
     * "ResetUsageWS method wsResetBillingCycle ResultCode."
     *
     */
    protected Integer ResetUsageWSResetBillingCycleResultCode = new Integer(1);


    /**
     * Constructor for the "ResetUsageWSResetBillingCycleResultCodeEntry" group.
     */
    public ResetUsageWSResetBillingCycleResultCodeEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "ResetUsageWSResetBillingCycleResultCodeCounters" variable.
     */
    public Long getResetUsageWSResetBillingCycleResultCodeCounters() throws SnmpStatusException {
        return ResetUsageWSResetBillingCycleResultCodeCounters;
    }

    /**
     * Getter for the "ResetUsageWSResetBillingCycleResultCodeName" variable.
     */
    public String getResetUsageWSResetBillingCycleResultCodeName() throws SnmpStatusException {
        return ResetUsageWSResetBillingCycleResultCodeName;
    }

    /**
     * Getter for the "ResetUsageWSResetBillingCycleResultCode" variable.
     */
    public Integer getResetUsageWSResetBillingCycleResultCode() throws SnmpStatusException {
        return ResetUsageWSResetBillingCycleResultCode;
    }

}
