package com.elitecore.netvertex.core.snmp.mib.netvertexpcrf.autogencode;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling NETVERTEX-PCRF-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "ResetUsageWSMethodWiseEntry" MBean.
 */
public interface ResetUsageWSMethodWiseEntryMBean {

    /**
     * Getter for the "ResetUsageWSMethodAvgTPS" variable.
     */
    public Long getResetUsageWSMethodAvgTPS() throws SnmpStatusException;

    /**
     * Getter for the "ResetUsageWSMethodLastMinuteTotalRequests" variable.
     */
    public Long getResetUsageWSMethodLastMinuteTotalRequests() throws SnmpStatusException;

    /**
     * Getter for the "ResetUsageWSMethodTotalResponses" variable.
     */
    public Long getResetUsageWSMethodTotalResponses() throws SnmpStatusException;

    /**
     * Getter for the "ResetUsageWSMethodTotalRequests" variable.
     */
    public Long getResetUsageWSMethodTotalRequests() throws SnmpStatusException;

    /**
     * Getter for the "ResetUsageWSMethodName" variable.
     */
    public String getResetUsageWSMethodName() throws SnmpStatusException;

    /**
     * Getter for the "ResetUsageWSMethodIndex" variable.
     */
    public Integer getResetUsageWSMethodIndex() throws SnmpStatusException;

}
