package com.elitecore.netvertex.core.snmp.mib.netvertexpcrf.autogencode;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling NETVERTEX-PCRF-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SubscriberWSPurgeAllSubscriberEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.21067.4.1.3.10.16.1.
 */
public class SubscriberWSPurgeAllSubscriberEntry implements SubscriberWSPurgeAllSubscriberEntryMBean, Serializable {

    /**
     * Variable for storing the value of "PurgeAllSubscriberResultCodeCounters".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.10.16.1.3".
     *
     * "SubscriberProvisioningWS method wsPurgeAllSubscriber ResultCode Specific statistics."
     *
     */
    protected Long PurgeAllSubscriberResultCodeCounters = new Long(1);

    /**
     * Variable for storing the value of "PurgeAllSubscriberResultCodeName".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.10.16.1.2".
     *
     * "SubscriberProvisioningWS method wsPurgeAllSubscriber ResultCode Name."
     *
     */
    protected String PurgeAllSubscriberResultCodeName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "PurgeAllSubscriberResultCode".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.10.16.1.1".
     *
     * "SubscriberProvisioningWS method wsPurgeAllSubscriber ResultCode."
     *
     */
    protected Integer PurgeAllSubscriberResultCode = new Integer(1);


    /**
     * Constructor for the "SubscriberWSPurgeAllSubscriberEntry" group.
     */
    public SubscriberWSPurgeAllSubscriberEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "PurgeAllSubscriberResultCodeCounters" variable.
     */
    public Long getPurgeAllSubscriberResultCodeCounters() throws SnmpStatusException {
        return PurgeAllSubscriberResultCodeCounters;
    }

    /**
     * Getter for the "PurgeAllSubscriberResultCodeName" variable.
     */
    public String getPurgeAllSubscriberResultCodeName() throws SnmpStatusException {
        return PurgeAllSubscriberResultCodeName;
    }

    /**
     * Getter for the "PurgeAllSubscriberResultCode" variable.
     */
    public Integer getPurgeAllSubscriberResultCode() throws SnmpStatusException {
        return PurgeAllSubscriberResultCode;
    }

}
