package com.elitecore.netvertex.core.snmp.mib.netvertexpcrf.autogencode;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling NETVERTEX-PCRF-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SubscriptionWSListBoDPackagesEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.21067.4.1.3.9.30.1.
 */
public class SubscriptionWSListBoDPackagesEntry implements SubscriptionWSListBoDPackagesEntryMBean, Serializable {

    /**
     * Variable for storing the value of "ListBoDPackagesResultCodeCounters".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.9.30.1.3".
     *
     * "SubscriptionWS method wsListBoDPackages resultCode specific Counters."
     *
     */
    protected Long ListBoDPackagesResultCodeCounters = new Long(1);

    /**
     * Variable for storing the value of "ListBoDPackagesResultCodeName".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.9.30.1.2".
     *
     * "subscriptionWS wsListBoDPackages ResultCode Name."
     *
     */
    protected String ListBoDPackagesResultCodeName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "ListBoDPackagesResultCode".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.9.30.1.1".
     *
     * "SubscriptionWS method wsListBoDPackages ResultCode"
     *
     */
    protected Integer ListBoDPackagesResultCode = new Integer(1);


    /**
     * Constructor for the "SubscriptionWSListBoDPackagesEntry" group.
     */
    public SubscriptionWSListBoDPackagesEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "ListBoDPackagesResultCodeCounters" variable.
     */
    public Long getListBoDPackagesResultCodeCounters() throws SnmpStatusException {
        return ListBoDPackagesResultCodeCounters;
    }

    /**
     * Getter for the "ListBoDPackagesResultCodeName" variable.
     */
    public String getListBoDPackagesResultCodeName() throws SnmpStatusException {
        return ListBoDPackagesResultCodeName;
    }

    /**
     * Getter for the "ListBoDPackagesResultCode" variable.
     */
    public Integer getListBoDPackagesResultCode() throws SnmpStatusException {
        return ListBoDPackagesResultCode;
    }

}
