package com.elitecore.netvertex.core.snmp.mib.netvertexpcrf.autogencode;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling NETVERTEX-PCRF-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SubscriptionWSSubscribeTopUpEntry" MBean.
 */
public interface SubscriptionWSSubscribeTopUpEntryMBean {

    /**
     * Getter for the "SubscribeTopUpResultCodeCounters" variable.
     */
    public Long getSubscribeTopUpResultCodeCounters() throws SnmpStatusException;

    /**
     * Getter for the "SubscribeTopUpResultCodeName" variable.
     */
    public String getSubscribeTopUpResultCodeName() throws SnmpStatusException;

    /**
     * Getter for the "SubscribeTopUpResultCode" variable.
     */
    public Integer getSubscribeTopUpResultCode() throws SnmpStatusException;

}
