package com.elitecore.netvertex.core.snmp.mib.netvertexpcrf.autogencode;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling NETVERTEX-PCRF-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SubscriberWSRestoreSubscribersEntry" MBean.
 */
public interface SubscriberWSRestoreSubscribersEntryMBean {

    /**
     * Getter for the "RestoreSubscribersResultCodeCounters" variable.
     */
    public Long getRestoreSubscribersResultCodeCounters() throws SnmpStatusException;

    /**
     * Getter for the "RestoreSubscribersResultCodeName" variable.
     */
    public String getRestoreSubscribersResultCodeName() throws SnmpStatusException;

    /**
     * Getter for the "RestoreSubscribersResultCode" variable.
     */
    public Integer getRestoreSubscribersResultCode() throws SnmpStatusException;

}
