INSERT INTO TBLMVERSION (SERIALNO,VERSION,SETUPMODE,COMPONENT,EXECUTED_ON) VALUES (SEQ_TBLMVERSION.nextval,'6.6.2.6','upgrade-csm-to-6.6.2.6','AAASMX',CURRENT_TIMESTAMP);
commit;

--Search Subscriber Routing Table and move IMSI, MSISDN into Subscriber Routing Table
Insert into TBLMACTION (ACTIONID,NAME,ALIAS,DESCRIPTION,ACTIONTYPEID,PARENTACTIONID,ACTIONLEVEL,SYSTEMGENERATED,SCREENID,STATUS,FREEZEPROFILE) 
values ('ACN00438','Search Subscriber Routing Table','SEARCH_SUBSCRIBER_ROUTING_TABLE','Search Subscriber Routing Table','ACT00','ACN00001',1,'N','SCR001','E','E');

UPDATE TBLMBISMODULE SET ALIAS='SUBSCRIBER_ROUTING_TABLE',NAME='Subscriber Routing Table',DESCRIPTION='Subscriber Routing Table' WHERE BUSINESSMODULEID='BMO00046';

INSERT INTO TBLMSUBBISMODULE (SUBBUSINESSMODULEID,ALIAS,NAME,SYSTEMGENERATED,STATUS,SUBBISMODULETYPEID,DESCRIPTION,FREEZEPROFILE) 
VALUES ('SBM00118','SEARCH_SUBSCRIBER_ROUTING_TABLE','Search Subscriber Routing Table','N','E','STY00001','Search Subscriber Routing Table','E');

UPDATE TBLTBISMODULESUBBISMODULEREL SET BUSINESSMODULEID='BMO00046' WHERE BUSINESSMODULEID='BMO00047' AND SUBBUSINESSMODULEID='SBM00110';

DELETE FROM TBLMBISMODULE WHERE BUSINESSMODULEID='BMO00047';

Insert into TBLTBISMODULESUBBISMODULEREL (BUSINESSMODULEID,SUBBUSINESSMODULEID,STATUS) values ('BMO00046','SBM00111','E');

Insert into TBLTSUBBISMODULEACTIONREL (ACTIONID,SUBBUSINESSMODULEID,STATUS) values ('ACN00438','SBM00118','E');

DELETE FROM TBLTBISMODELMODULEREL WHERE BUSINESSMODELID='BM000010' AND BUSINESSMODULEID='BMO00047';
DELETE FROM TBLTBISMODULESUBBISMODULEREL WHERE BUSINESSMODULEID='BMO00046' AND SUBBUSINESSMODULEID='SBM00112';

COMMIT;

