INSERT INTO TBLMVERSION (SERIALNO,VERSION,SETUPMODE,COMPONENT,EXECUTED_ON) VALUES (SEQ_TBLMVERSION.nextval,'6.6.2.1','upgrade-csm-to-6.6.2.1','AAASMX',CURRENT_TIMESTAMP);
commit;

--adding PROTOCOLTYPE column in TBLMDIAMETERSESSIONDATA and TBLMCONCURRENTUSERS
ALTER TABLE TBLMDIAMETERSESSIONDATA ADD (PROTOCOLTYPE varchar2(30));
ALTER TABLE TBLMCONCURRENTUSERS ADD (PROTOCOLTYPE varchar2(30));
COMMIT;

--Add viewablecolumns in diametersessionmanager
ALTER TABLE TBLMDIAMETERSESSIONMANAGER ADD VIEWABLECOLUMNS VARCHAR(300);
commit;

Insert into TBLMSYSTEMPARAMETER (PARAMETERID,NAME,ALIAS,VALUE,SYSTEMGENERATED,DESCRIPTION) values (25,'Concurrent Login Limit','CONCURRENT_LOGIN_LIMIT','1','N','total number of concurrent user to access server manager GUI');
Insert into TBLMSYSTEMPARAMETER (PARAMETERID,NAME,ALIAS,VALUE,SYSTEMGENERATED,DESCRIPTION) values (26,'Session Idle Time','SESSION_IDLE_TIME','300','N','Specify idle time of session, after this time session will automatically destroy(In Second)');
COMMIT;
