INSERT INTO TBLMVERSION (SERIALNO,VERSION,SETUPMODE,COMPONENT,EXECUTED_ON) VALUES (SEQ_TBLMVERSION.nextval,'6.6.0.5','upgrade-csm-to-6.6.0.5','AAASMX',CURRENT_TIMESTAMP);
COMMIT;

--Add Pre & Post Plugin in CC Policy
ALTER TABLE TBLMCCPOLICY ADD  PREPLUGINS  VARCHAR(300);
ALTER TABLE TBLMCCPOLICY ADD  POSTPLUGINS VARCHAR(300);

--Add Pre & Post Plugin in EAP Policy
ALTER TABLE TBLMEAPPOLICY ADD  PREPLUGINS  VARCHAR(300);
ALTER TABLE TBLMEAPPOLICY ADD  POSTPLUGINS VARCHAR(300);

ALTER TABLE TBLMPLUGINTYPE ADD PLUGINFLOWTYPE NUMERIC(2);

--Remove all default plugin
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011356';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011358';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011481';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011317';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011319';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011454';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011456';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011458';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011460';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011462';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011464';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011514';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011516';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011574';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011576';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011578';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011580';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011582';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011584';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011636';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011638';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011466';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011468';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011355';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011357';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011480';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011310';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID='VPL000011308';

COMMIT;

-- Add Radius Groovy Plugin
Insert into TBLMPLUGINTYPE(PLUGINTYPEID,NETSERVERTYPEID,NAME,ALIAS,DESCRIPTION,SYSTEMGENERATED,ENABLED,PROCESSINGTYPE,PLUGINVERSION,PLUGINFLOWTYPE)
Values ('PGT0009','SRV0001','Radius Groovy Plugin','RADIUS_GROOVY_PLUGIN','Radius Groovy Plugin','N','Y',3,'${plugin.version}',4);

Insert into TBLMNETCONFIGURATION(NETCONFIGID, SERIALNO, NAME, DISPLAYNAME, FILENAME, ALIAS, CONFIGVERSION)
Values ('PGC0009', 9 ,'Radius Groovy Plugin' , 'Radius Groovy Plugin' , 'radius-groovy-plugin' , 'RADIUS_GROOVY_PLUGIN' , '1.0');

Insert into TBLMPLUGINCONFIGMAP (PLUGINTYPEID,NETCONFIGID) values ('PGT0009','PGC0009');

--Add Diameter Groovy Plugin
Insert into TBLMPLUGINTYPE(PLUGINTYPEID,NETSERVERTYPEID,NAME,ALIAS,DESCRIPTION,SYSTEMGENERATED,ENABLED,PROCESSINGTYPE,PLUGINVERSION)
Values ('PGT0010','SRV0001','Diameter Groovy Plugin','DIAMETER_GROOVY_PLUGIN','Diameter Groovy Plugin','N','Y',6,'${plugin.version}');

Insert into TBLMNETCONFIGURATION(NETCONFIGID, SERIALNO, NAME, DISPLAYNAME, FILENAME, ALIAS, CONFIGVERSION)
Values ('PGC0010', 10 ,'Diameter Groovy Plugin' , 'Diameter Groovy Plugin' , 'diameter-groovy-plugin' , 'DIAMETER_GROOVY_PLUGIN' , '1.0');

Insert into TBLMPLUGINCONFIGMAP (PLUGINTYPEID,NETCONFIGID) values ('PGT0010','PGC0010');

--Add Diameter Groovy Plugin for RM
Insert into TBLMPLUGINTYPE(PLUGINTYPEID,NETSERVERTYPEID,NAME,ALIAS,DESCRIPTION,SYSTEMGENERATED,ENABLED,PROCESSINGTYPE,PLUGINVERSION)
Values ('PGT0011','SRV0002','Diameter Groovy Plugin','DIAMETER_GROOVY_PLUGIN','Diameter Groovy Plugin','N','Y',6,'${plugin.version}');

Insert into TBLMNETCONFIGURATION(NETCONFIGID, SERIALNO, NAME, DISPLAYNAME, FILENAME, ALIAS, CONFIGVERSION)
Values ('PGC0011', 11 ,'Diameter Groovy Plugin' , 'Diameter Groovy Plugin' , 'diameter-groovy-plugin' , 'DIAMETER_GROOVY_PLUGIN' , '1.0');

Insert into TBLMPLUGINCONFIGMAP (PLUGINTYPEID,NETCONFIGID) values ('PGT0011','PGC0011');


Insert into TBLMNETCONFIGPARAMVALUEPOOL(PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values('VPL000011308', 'APM000195', 'UNIVERSAL_AUTH_PLUGIN', 'UNIVERSAL_AUTH_PLUGIN', 'CNF0002'); 
   
Insert into TBLMNETCONFIGPARAMVALUEPOOL(PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values('VPL000011310', 'APM000197', 'UNIVERSAL_ACCT_PLUGIN', 'UNIVERSAL_ACCT_PLUGIN', 'CNF0003'); 
   
Insert into TBLMNETCONFIGPARAMVALUEPOOL(PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values('VPL000011317', 'APM000196', 'UNIVERSAL_AUTH_PLUGIN', 'UNIVERSAL_AUTH_PLUGIN', 'CNF0002');
   
Insert into TBLMNETCONFIGPARAMVALUEPOOL(PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values('VPL000011319', 'APM000198', 'UNIVERSAL_ACCT_PLUGIN', 'UNIVERSAL_ACCT_PLUGIN', 'CNF0003'); 

COMMIT;

ALTER TABLE TBLMPEERGROUPREL ADD ORDERNUMBER NUMERIC(20);
COMMIT;

update TBLMACTION set STATUS='E' where ACTIONID='ACN00016';
update TBLMACTION set STATUS='E' where ACTIONID='ACN00145';
update TBLMACTION set STATUS='E' where ACTIONID='ACN00158';
update TBLMACTION set STATUS='E' where ACTIONID='ACN00006';
update TBLMACTION set STATUS='E' where ACTIONID='ACN00143';

COMMIT;

Insert into TBLMSYSTEMPARAMETER (PARAMETERID,NAME,ALIAS,VALUE,SYSTEMGENERATED,DESCRIPTION) values (25,'Concurrent Login Limit','CONCURRENT_LOGIN_LIMIT','1','N','total number of concurrent user to access server manager GUI');
Insert into TBLMSYSTEMPARAMETER (PARAMETERID,NAME,ALIAS,VALUE,SYSTEMGENERATED,DESCRIPTION) values (26,'Session Idle Time','SESSION_IDLE_TIME','300','N','Specify idle time of session, after this time session will automatically destroy(In Second)');
COMMIT;

--Rename diameter related driver (NAS to Diameter)
UPDATE TBLSDRIVERTYPE SET NAME='Diameter DB Acct Driver',DISPLAYNAME='Diameter DB Acct Driver',ALIAS='DIAMETER_DB_ACCT_DRIVER' where DRIVERTYPEID=10;
UPDATE TBLSDRIVERTYPE SET NAME='Diameter DB Auth Driver',DISPLAYNAME='Diameter DB Auth Driver',ALIAS='DIAMETER_DB_AUTH_DRIVER' where DRIVERTYPEID=7;
UPDATE TBLSDRIVERTYPE SET NAME='Diameter Http Auth Driver',DISPLAYNAME='Diameter Http Auth Driver',ALIAS='DIAMETER_HTTP_AUTH_DRIVER' where DRIVERTYPEID=28;
UPDATE TBLSDRIVERTYPE SET NAME='Diameter LDAP Auth Driver',DISPLAYNAME='Diameter LDAP Auth Driver',ALIAS='DIAMETER_LDAP_AUTH_DRIVER' where DRIVERTYPEID=8;
UPDATE TBLSDRIVERTYPE SET NAME='Diameter User File Auth Driver',DISPLAYNAME='Diameter User File Auth Driver',ALIAS='DIAMETER_USERFILE_AUTH_DRIVER' where DRIVERTYPEID=9;
UPDATE TBLSDRIVERTYPE SET NAME='Diameter Classic CSV Acct Driver',DISPLAYNAME='Diameter Classic CSV Acct Driver',ALIAS='DIAMETER_CLASSIC_CSV_ACCT_DRIVER' where DRIVERTYPEID=11;
UPDATE TBLSDRIVERTYPE SET NAME='Diameter Detail Local Acct Driver',DISPLAYNAME='Diameter Detail Local Acct Driver',ALIAS='DIAMETER_DETAIL_LOCAL_ACCT_DRIVER' where DRIVERTYPEID=12;
UPDATE TBLSDRIVERTYPE SET NAME='Diameter MAP Gateway Auth Driver',DISPLAYNAME='Diameter MAP Gateway Auth Driver',ALIAS='DIAMETER_MAP_GATEWAY_AUTH_DRIVER' where DRIVERTYPEID=27;

--Rename title of diameter service drivers
UPDATE tblsservicetype SET name='Diameter Authentication Service',displayname='Diameter Authentication Service',alias='DIAMETER_AUTHENTICATION_SERVICE',description='Diameter Authentication Service' where servicetypeid=3;
UPDATE tblsservicetype SET name='Diameter Accounting Service',displayname='Diameter Accounting Service',alias='DIAMETER_ACCOUNTING_SERVICE',description='Diameter Accounting Service' where servicetypeid=4;
commit;

--Add column ACCT_RECORD_TYPE in TBLDIAMETERCDR
ALTER TABLE TBLDIAMETERCDR ADD  ACCT_RECORD_TYPE  VARCHAR(253);
COMMIT;

--ADD column ACCT_RECORD_TYPE in TBLDIAMETERINTERIMCDR
ALTER TABLE TBLDIAMETERINTERIMCDR ADD  ACCT_RECORD_TYPE  VARCHAR(253);
COMMIT;

-- Adding rows for Diameter Peer High Response Time and Diameter Stack Hight Response Time Alerts
Insert into TBLSALERTTYPE (ALERTTYPEID,PARENTID,NAME,ALIAS,ENABLED,TYPE) values('AT000077','AT000055','Diameter Stack High Response Time','DIA STACK HIGH RESPONSE TIME','Y','L');
Insert into TBLSALERTTYPE (ALERTTYPEID,PARENTID,NAME,ALIAS,ENABLED,TYPE) values('AT000078','AT000055','Diameter Peer High Response Time','DIA PEER HIGH RESPONSE TIME','Y','L');
commit;

--Restructure IMSI and MSISDN Routing table
UPDATE TBLMBISMODULE SET ALIAS='SUBSCRIBER_ROUTING_TABLE',NAME='Subscriber Routing Table',DESCRIPTION='Subscriber Routing Table' WHERE BUSINESSMODULEID='BMO00046';
UPDATE TBLTBISMODULESUBBISMODULEREL SET BUSINESSMODULEID='BMO00046',SUBBUSINESSMODULEID='SBM00110' WHERE BUSINESSMODULEID='BMO00047' AND SUBBUSINESSMODULEID='SBM00110';
DELETE FROM TBLTBISMODELMODULEREL WHERE BUSINESSMODELID='BM000010' AND BUSINESSMODULEID='BMO00047';
DELETE FROM TBLMBISMODULE WHERE BUSINESSMODULEID='BMO00047';
Insert into TBLTBISMODULESUBBISMODULEREL (BUSINESSMODULEID,SUBBUSINESSMODULEID,STATUS) values ('BMO00046','SBM00111','E');
commit;

--Insert Search Subscriber Routing Table in ACL
INSERT INTO TBLMSUBBISMODULE (SUBBUSINESSMODULEID,ALIAS,NAME,SYSTEMGENERATED,STATUS,SUBBISMODULETYPEID,DESCRIPTION,FREEZEPROFILE) 
VALUES ('SBM00112','SEARCH_SUBSCRIBER_ROUTING_TABLE','Search Subscriber Routing Table','N','E','STY00001','Search Subscriber Routing Table','E');

Insert into TBLTBISMODULESUBBISMODULEREL (BUSINESSMODULEID,SUBBUSINESSMODULEID,STATUS) values ('BMO00046','SBM00112','E');

Insert into TBLMACTION (ACTIONID,NAME,ALIAS,DESCRIPTION,ACTIONTYPEID,PARENTACTIONID,ACTIONLEVEL,SYSTEMGENERATED,SCREENID,STATUS,FREEZEPROFILE) 
values ('ACN00422','Search Subscriber Routing Table','SEARCH_SUBSCRIBER_ROUTING_TABLE','Search Subscriber Routing Table','ACT00','ACN00001',1,'N','SCR001','E','E');

Insert into TBLMGROUPACTIONREL (ACTIONID,GROUPID) values ('ACN00422',1);

Insert into TBLTSUBBISMODULEACTIONREL (ACTIONID,SUBBUSINESSMODULEID,STATUS) values ('ACN00422','SBM00112','E');
COMMIT;