INSERT INTO TBLMVERSION (SERIALNO,VERSION,SETUPMODE,COMPONENT,EXECUTED_ON) VALUES (SEQ_TBLMVERSION.nextval,'6.6.2.2','upgrade-csm-to-6.6.2.2','AAASMX',CURRENT_TIMESTAMP);
commit;


CREATE TABLE TBLMHAKEYS (
HAIPADDRESS VARCHAR2(30),
LIFETIME NUMBER(30),
SPI NUMBER(30),
GENERATIONTIME NUMBER(30),
KEY VARCHAR2(3000));

COMMIT;
