INSERT INTO TBLMVERSION (SERIALNO,VERSION,SETUPMODE,COMPONENT,EXECUTED_ON) VALUES (SEQ_TBLMVERSION.nextval,'6.6.2.11','upgrade-csm-to-6.6.2.11','AAASMX',CURRENT_TIMESTAMP);
commit;

-- Added Accounting Response Attributes in Radius Service Policy and Rename Response Attribute to Auth Response Attribute
ALTER TABLE TBLMRADIUSSERVICEPOLICY RENAME COLUMN RESPONSEATTRIBUTES TO AUTHRESPONSEATTRIBUTES;
ALTER TABLE TBLMRADIUSSERVICEPOLICY ADD ACCTRESPONSEATTRIBUTES VARCHAR2(2000);

COMMIT;