INSERT INTO TBLMVERSION (SERIALNO,VERSION,SETUPMODE,COMPONENT,EXECUTED_ON) VALUES (SEQ_TBLMVERSION.nextval,'6.6.0.2','upgrade-csm-to-6.6.0.2','AAASMX',CURRENT_TIMESTAMP);
Commit;

Insert into TBLMGROUPACTIONREL (ACTIONID,GROUPID) values ('ACN00127',1);
Commit;

--Changes Regarding Adding Immediate Flush in Logging into EliteAAA Server
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=7 where PARAMETERID='APM000592';

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('APM000980' , 'CNF0001' , 6 , 'Immediate Flush' , 'Immediate Flush' ,
	'immediate-flush' , '@logging.immediateflush' , 'L' , 'regexp' , 1 , 'N' ,
	'APM000008' , 'false' , 10 , 'Y' ,
	'SMS0164' , 'Y' , 'N');
	
Insert into TBLMNETCONFIGPARAMVALUEPOOL
   (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
 Values
   ('VPL000011641', 'APM000980', 'True', 'true', 'CNF0001');
Insert into TBLMNETCONFIGPARAMVALUEPOOL
   (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
 Values
   ('VPL000011642', 'APM000980', 'False', 'false', 'CNF0001'); 
COMMIT;

--Changes Regarding Adding Immediate Flush in Logging into RM Diameter Stack
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=8 where PARAMETERID='APM000946';
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=9 where PARAMETERID='APM000947';

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('APM000981' , 'CNF0035' , 7, 'Immediate Flush' , 'Immediate Flush' ,
	'immediate-flush' , '@logging.immediateflush' , 'L' , 'regexp' , 1 , 'N' ,
	'APM000939' , 'false' , 10 , 'Y' ,
	'SMS0164' , 'Y' , 'N');
	
Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011643', 'APM000981', 'True', 'true', 'CNF0035');

Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011644', 'APM000981', 'False', 'false', 'CNF0035'); 

COMMIT;

--Changes Regarding Adding Immediate Flush in Logging into AAA Diameter Stack
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=8 where PARAMETERID='APM000813';
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=9 where PARAMETERID='APM000814';

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('APM000982' , 'CNF0031' , 7 , 'Immediate Flush' , 'Immediate Flush' ,
	'immediate-flush' , '@logging.immediateflush' , 'L' , 'regexp' , 1 , 'N' ,
	'APM000806' , 'false' , 10 , 'Y' ,
	'SMS0164' , 'Y' , 'N');
	
Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011645', 'APM000982', 'True', 'true', 'CNF0031');

Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011646', 'APM000982', 'False', 'false', 'CNF0031'); 
Commit;

--Changes Regarding Adding Immediate Flush in Logging into Rad Auth
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=8 where PARAMETERID='APM000541';
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=9 where PARAMETERID='APM000595';

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('APM000983' , 'CNF0002' , 7 , 'Immediate Flush' , 'Immediate Flush' ,
	'immediate-flush' , '@logging.immediateflush' , 'L' , 'regexp' , 1 , 'N' ,
	'APM000071' , 'false' , 10 , 'Y' ,
	'SMS0164' , 'Y' , 'N');	
	
Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011647', 'APM000983', 'True', 'true', 'CNF0002');

Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011648', 'APM000983', 'False', 'false', 'CNF0002'); 

COMMIT;

--Changes Regarding Adding Immediate Flush in Logging into Rad Acct
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=8 where PARAMETERID='APM000542';
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=9 where PARAMETERID='APM000598';

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('APM000984' , 'CNF0003' , 7 , 'Immediate Flush' , 'Immediate Flush' ,
	'immediate-flush' , '@logging.immediateflush' , 'L' , 'regexp' , 1 , 'N' ,
	'APM000100' , 'false' , 10 , 'Y' ,
	'SMS0164' , 'Y' , 'N');
	
Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011649', 'APM000984', 'True', 'true', 'CNF0003');

Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011650', 'APM000984', 'False', 'false', 'CNF0003'); 

COMMIT;

--Changes Regarding Adding Immediate Flush in Logging into DynaAuth Service
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=8 where PARAMETERID='APM000544';
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=9 where PARAMETERID='APM000601';

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('APM000985' , 'CNF0013' , 7 , 'Immediate Flush' , 'Immediate Flush' ,
	'immediate-flush' , '@logging.immediateflush' , 'L' , 'regexp' , 1 , 'N' ,
	'APM000283' , 'false' , 10 , 'Y' ,
	'SMS0164' , 'Y' , 'N');
	
Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011651', 'APM000985', 'True', 'true', 'CNF0013');

Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011652', 'APM000985', 'False', 'false', 'CNF0013');

COMMIT;

--Changes Regarding Adding Immediate Flush in Logging into Diameter EAP
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=8 where PARAMETERID='APM000844';
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=9 where PARAMETERID='APM000845';

Insert into TBLMNETCONFIGURATIONPARAMETER (PARAMETERID,CONFIGID,SERIALNO,NAME,DISPLAYNAME,ALIAS,DESCRIPTION,TYPE,REGEXP,MAXINSTANCES,MULTIPLEINSTANCES,PARENTPARAMETERID,DEFAULTVALUE,MAXLENGTH,EDITABLE,STARTUPMODE,STATUS,ISNOTNULL) 
values ('APM000986','CNF0032',7,'Immediate Flush','Immediate Flush','immediate-flush','@logging.immediateflush','L','regexp',1,'N','APM000837','false',10,'Y','SMS0164','Y','N');

Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011653', 'APM000986', 'True', 'true', 'CNF0032');

Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011654', 'APM000986', 'False', 'false', 'CNF0032');   

Commit;

--Changes Regarding Adding Immediate Flush in Logging into Diameter NAS
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=8 where PARAMETERID='APM000863';
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=9 where PARAMETERID='APM000864';

Insert into TBLMNETCONFIGURATIONPARAMETER (PARAMETERID,CONFIGID,SERIALNO,NAME,DISPLAYNAME,ALIAS,DESCRIPTION,TYPE,REGEXP,MAXINSTANCES,MULTIPLEINSTANCES,PARENTPARAMETERID,DEFAULTVALUE,MAXLENGTH,EDITABLE,STARTUPMODE,STATUS,ISNOTNULL) 
values ('APM000987','CNF0033',7,'Immediate Flush','Immediate Flush','immediate-flush','@logging.immediateflush','L','regexp',1,'N','APM000856','false',10,'Y','SMS0164','Y','N');

Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011655', 'APM000987', 'True', 'true', 'CNF0033');

Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011656', 'APM000987', 'False', 'false', 'CNF0033'); 

COMMIT;

--Changes Regarding Adding Immediate Flush in Logging into Diameter CC
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=8 where PARAMETERID='APM000882';
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=9 where PARAMETERID='APM000883';

Insert into TBLMNETCONFIGURATIONPARAMETER (PARAMETERID,CONFIGID,SERIALNO,NAME,DISPLAYNAME,ALIAS,DESCRIPTION,TYPE,REGEXP,MAXINSTANCES,MULTIPLEINSTANCES,PARENTPARAMETERID,DEFAULTVALUE,MAXLENGTH,EDITABLE,STARTUPMODE,STATUS,ISNOTNULL) 
values ('APM000988','CNF0034',7,'Immediate Flush','Immediate Flush','immediate-flush','@logging.immediateflush','L','regexp',1,'N','APM000875','false',10,'Y','SMS0164','Y','N');

Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011657', 'APM000988', 'True', 'true', 'CNF0034');

Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011658', 'APM000988', 'False', 'false', 'CNF0034'); 

COMMIT;

--Changes Regarding Adding Immediate Flush in Logging into RM Server
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=7 where PARAMETERID='APM000604';

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('APM000989' , 'CNF0018' , 6 , 'Immediate Flush' , 'Immediate Flush' ,
	'immediate-flush' , '@logging.immediateflush' , 'L' , 'regexp' , 1 , 'N' ,
	'APM000434' , 'false' , 10 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011659', 'APM000989', 'True', 'true', 'CNF0018');

Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011660', 'APM000989', 'False', 'false', 'CNF0018'); 

COMMIT;

--Changes Regarding Adding Immediate Flush in Logging into Rm Concurrent Login Service
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=8 where PARAMETERID='APM000543';
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=9 where PARAMETERID='APM000613';

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('APM000990' , 'CNF0012' , 7 , 'Immediate Flush' , 'Immediate Flush' ,
	'immediate-flush' , '@logging.immediateflush' , 'L' , 'regexp' , 1 , 'N' ,
	'APM000259' , 'false' , 10 , 'Y' ,
	'SMS0164' , 'Y' , 'N');
	
Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011661', 'APM000990', 'True', 'true', 'CNF0012');

Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011662', 'APM000990', 'False', 'false', 'CNF0012'); 

COMMIT;

--Changes Regarding Adding Immediate Flush in Logging into RM IP-Pool Service
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=8 where PARAMETERID='APM000545';
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=9 where PARAMETERID='APM000616';

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('APM000991','CNF0014',7,'Immediate Flush','Immediate Flush',
	'immediate-flush','@logging.immediateflush','L','regexp',1,'N',
	'APM000317','false',10,'Y',
	'SMS0164','Y','N');
	
Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011663', 'APM000991', 'True', 'true', 'CNF0014');

Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011664', 'APM000991', 'False', 'false', 'CNF0014');

COMMIT;

--Chnages Regarding Adding Immediate Flush in Logging into Rm Prepaid Charging Service
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=8 where PARAMETERID='APM000546';
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=9 where PARAMETERID='APM000619';

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('APM000992' , 'CNF0015' , 7 , 'Immediate Flush' , 'Immediate Flush' ,
	'immediate-flush' , '@logging.immediateflush' , 'L' , 'regexp' , 1 , 'N' ,
	'APM000349' , 'false' , 10 , 'Y' ,
	'SMS0164' , 'Y' , 'N');
	
Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011665', 'APM000992', 'True', 'true', 'CNF0015');

Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011666', 'APM000992', 'False', 'false', 'CNF0015');

COMMIT;

--Chnages Regarding Adding Immediate Flush in Logging into GTP Prime
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=8 where PARAMETERID='APM000547';
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=9 where PARAMETERID='APM000607';

INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('APM000993' , 'CNF0022' , 7 , 'Immediate Flush' , 'Immediate Flush' ,
	'immediate-flush' , '@logging.immediateflush' , 'L' , 'regexp' , 1 , 'N' ,
	'APM000507' , 'false' , 10 , 'Y' ,
	'SMS0164' , 'Y' , 'N');
	
Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011667', 'APM000993', 'True', 'true', 'CNF0022');

Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011668', 'APM000993', 'False', 'false', 'CNF0022');

COMMIT;

--Chnages Regarding Adding Immediate Flush in Logging into  RM Charging Service
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=8 where PARAMETERID='APM000565';
UPDATE TBLMNETCONFIGURATIONPARAMETER set SERIALNO=9 where PARAMETERID='APM000610';


INSERT INTO TBLMNETCONFIGURATIONPARAMETER
	(PARAMETERID, CONFIGID, SERIALNO, NAME, DISPLAYNAME, 
	ALIAS, DESCRIPTION, TYPE, REGEXP, MAXINSTANCES,MULTIPLEINSTANCES, 
	PARENTPARAMETERID, DEFAULTVALUE, MAXLENGTH, EDITABLE,
	STARTUPMODE, STATUS, ISNOTNULL )
VALUES
	('APM000994' , 'CNF0023' , 7 , 'Immediate Flush' , 'Immediate Flush' ,
	'immediate-flush' , '@logging.immediateflush' , 'L' , 'regexp' , 1 , 'N' ,
	'APM000558' , 'false' , 10 , 'Y' ,
	'SMS0164' , 'Y' , 'N');

Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011669', 'APM000994', 'True', 'true', 'CNF0023');

Insert into TBLMNETCONFIGPARAMVALUEPOOL (PARAMPOOLID, PARAMETERID, NAME, VALUE, NETCONFIGID)
Values ('VPL000011670', 'APM000994', 'False', 'false', 'CNF0023');

COMMIT;

--New Concept "EliteCSM" changes in SM
UPDATE TBLMNETSERVERTYPE SET NAME='EliteCSM Server',ALIAS='EliteCSM Server',DESCRIPTION='Description :EliteCSM Server' WHERE NETSERVERTYPEID='SRV0001';

--Changed AAA Service Policy to Service Policy
UPDATE TBLMBISMODEL SET NAME='Service Policy',DESCRIPTION='Service Policy' WHERE BUSINESSMODELID='BM000006';

--Changed Certificate to SSL Certificate
UPDATE TBLMBISMODULE SET NAME='SSL Certificate',DESCRIPTION='SSL Certificate' WHERE BUSINESSMODULEID='BMO00041';

--Changed Diameter Policy to Auhtorization policies
UPDATE TBLMBISMODULE SET NAME='Authorization Policies',DESCRIPTION='Authorization Policies',ALIAS='AUTHORIZATION_POLICY' WHERE BUSINESSMODULEID='BMO00034';

UPDATE TBLMSUBBISMODULE SET NAME='Create Authorization Policy',DESCRIPTION='Create Authorization Policy',ALIAS='CREATE_AUTHORIZATION_POLICY' where SUBBUSINESSMODULEID='SBM00072';
UPDATE TBLMSUBBISMODULE SET NAME='Search Authorization Policy',DESCRIPTION='Search Authorization Policy',ALIAS='SEARCH_AUTHORIZATION_POLICY' where SUBBUSINESSMODULEID='SBM00073';

UPDATE TBLMACTION SET NAME='Create Authorization Policy',ALIAS='CREATE_AUTHORIZATION_POLICY',DESCRIPTION='Create Authorization Policy' WHERE ACTIONID='ACN00300';
UPDATE TBLMACTION SET NAME='Search Authorization Policy',ALIAS='SEARCH_AUTHORIZATION_POLICY',DESCRIPTION='Search Authorization Policy' WHERE ACTIONID='ACN00301';
UPDATE TBLMACTION SET NAME='Update Authorization Policy Basic Detail',ALIAS='UPDATE_AUTHORIZATION_POLICY_BASIC_DETAIL',DESCRIPTION='Update Authorization Policy Basic Detail' WHERE ACTIONID='ACN00302';
UPDATE TBLMACTION SET NAME='Update Authorization Policy Status',ALIAS='UPDATE_AUTHORIZATION_POLICY_STATUS',DESCRIPTION='Update Authorization Policy Status' WHERE ACTIONID='ACN00303';
UPDATE TBLMACTION SET NAME='Delete Authorization Policy',ALIAS='DELETE_AUTHORIZATION_POLICY',DESCRIPTION='Delete Authorization Policy' WHERE ACTIONID='ACN00304';
UPDATE TBLMACTION SET NAME='View Authorization Policy',ALIAS='VIEW_AUTHORIZATION_POLICY',DESCRIPTION='View Authorization Policy' WHERE ACTIONID='ACN00305';

--Chnaged Radius to RADIUS
UPDATE TBLMBISMODEL SET NAME='RADIUS',DESCRIPTION='RADIUS' WHERE BUSINESSMODELID='BM000001';

--CHNAGED Radius Test to RADIUS Test
UPDATE TBLMBISMODULE SET NAME='RADIUS Test',DESCRIPTION='RADIUS Test' WHERE BUSINESSMODULEID='BMO00013';

--CHANGED Extended Radius TO Extended RADIUS
UPDATE TBLMBISMODULE SET NAME='Extended RADIUS',DESCRIPTION='Extended RADIUS' WHERE BUSINESSMODULEID='BMO00025';

--CHANGED SERVER TO SERVER INSTANCE
UPDATE TBLMBISMODULE SET NAME='Server Instance',DESCRIPTION='Server Instance' WHERE BUSINESSMODULEID='BMO00006';
COMMIT;

