INSERT INTO TBLMVERSION (SERIALNO,VERSION,SETUPMODE,COMPONENT,EXECUTED_ON) VALUES (SEQ_TBLMVERSION.nextval,'6.6.0.6','upgrade-csm-to-6.6.0.6','AAASMX',CURRENT_TIMESTAMP);
COMMIT;

DELETE FROM TBLTSUBBISMODULEACTIONREL WHERE ACTIONID='ACN00422' AND SUBBUSINESSMODULEID='SBM00112';
DELETE FROM TBLMGROUPACTIONREL WHERE ACTIONID='ACN00422' AND GROUPID=1;
DELETE FROM TBLMACTION WHERE ACTIONID='ACN00422';
DELETE FROM TBLTBISMODULESUBBISMODULEREL WHERE BUSINESSMODULEID='BMO00046' AND SUBBUSINESSMODULEID='SBM00112';
DELETE FROM TBLMSUBBISMODULE WHERE SUBBUSINESSMODULEID='SBM00112';

COMMIT;

--Insert Search Subscriber Routing Table in ACL
INSERT INTO TBLMSUBBISMODULE (SUBBUSINESSMODULEID,ALIAS,NAME,SYSTEMGENERATED,STATUS,SUBBISMODULETYPEID,DESCRIPTION,FREEZEPROFILE) 
VALUES ('SBM00118','SEARCH_SUBSCRIBER_ROUTING_TABLE','Search Subscriber Routing Table','N','E','STY00001','Search Subscriber Routing Table','E');

Insert into TBLTBISMODULESUBBISMODULEREL (BUSINESSMODULEID,SUBBUSINESSMODULEID,STATUS) values ('BMO00046','SBM00118','E');

Insert into TBLMACTION (ACTIONID,NAME,ALIAS,DESCRIPTION,ACTIONTYPEID,PARENTACTIONID,ACTIONLEVEL,SYSTEMGENERATED,SCREENID,STATUS,FREEZEPROFILE) 
values ('ACN00438','Search Subscriber Routing Table','SEARCH_SUBSCRIBER_ROUTING_TABLE','Search Subscriber Routing Table','ACT00','ACN00001',1,'N','SCR001','E','E');

Insert into TBLMGROUPACTIONREL (ACTIONID,GROUPID) values ('ACN00438',1);

Insert into TBLTSUBBISMODULEACTIONREL (ACTIONID,SUBBUSINESSMODULEID,STATUS) values ('ACN00438','SBM00118','E');
COMMIT;

