INSERT INTO TBLMVERSION (SERIALNO,VERSION,SETUPMODE,COMPONENT,EXECUTED_ON) VALUES (SEQ_TBLMVERSION.nextval,'6.8.0.4','upgrade-csm-to-6.8.0.4','AAASMX',CURRENT_TIMESTAMP);
commit;

-- Removed Immediate flush from AAA Server Configuration --
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011641';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011642';
DELETE FROM TBLMNETCONFIGURATIONVALUES WHERE PARAMETERID = 'APM000980';
DELETE FROM TBLMNETCONFIGURATIONPARAMETER WHERE PARAMETERID = 'APM000980';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 6 WHERE PARAMETERID = 'APM000592' AND CONFIGID = 'CNF0001';

-- Removed Immediate flush from Diameter Stack Configuration --
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011645';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011646';
DELETE FROM TBLMNETCONFIGURATIONVALUES WHERE PARAMETERID = 'APM000982';
DELETE FROM TBLMNETCONFIGURATIONPARAMETER WHERE PARAMETERID = 'APM000982';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 7 WHERE PARAMETERID = 'APM000813' AND CONFIGID = 'CNF0031';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 8 WHERE PARAMETERID = 'APM000814' AND CONFIGID = 'CNF0031';

-- Removed Immediate flush from Rad Auth Configuration --
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011647';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011648';
DELETE FROM TBLMNETCONFIGURATIONVALUES WHERE PARAMETERID = 'APM000983';
DELETE FROM TBLMNETCONFIGURATIONPARAMETER WHERE PARAMETERID = 'APM000983';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 7 WHERE PARAMETERID = 'APM000541' AND CONFIGID = 'CNF0002';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 8 WHERE PARAMETERID = 'APM000595' AND CONFIGID = 'CNF0002';

-- Removed Immediate flush from Rad Acct Configuration --
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011649';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011650';
DELETE FROM TBLMNETCONFIGURATIONVALUES WHERE PARAMETERID = 'APM000984';
DELETE FROM TBLMNETCONFIGURATIONPARAMETER WHERE PARAMETERID = 'APM000984';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 7 WHERE PARAMETERID = 'APM000542' AND CONFIGID = 'CNF0003';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 8 WHERE PARAMETERID = 'APM000598' AND CONFIGID = 'CNF0003';

-- Removed Immediate flush from Rad Dynauth Configuration --
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011651';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011652';
DELETE FROM TBLMNETCONFIGURATIONVALUES WHERE PARAMETERID = 'APM000985';
DELETE FROM TBLMNETCONFIGURATIONPARAMETER WHERE PARAMETERID = 'APM000985';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 7 WHERE PARAMETERID = 'APM000544' AND CONFIGID = 'CNF0013';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 8 WHERE PARAMETERID = 'APM000601' AND CONFIGID = 'CNF0013';

-- Removed Immediate flush from 3GPP Application Configuration --
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011710';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011711';
DELETE FROM TBLMNETCONFIGURATIONVALUES WHERE PARAMETERID = 'APM001125';
DELETE FROM TBLMNETCONFIGURATIONPARAMETER WHERE PARAMETERID = 'APM001125';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 7 WHERE PARAMETERID = 'APM001126' AND CONFIGID = 'CNF0036';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 8 WHERE PARAMETERID = 'APM001127' AND CONFIGID = 'CNF0036';

-- Removed Immediate flush from EAP Configuration --
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011653';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011654';
DELETE FROM TBLMNETCONFIGURATIONVALUES WHERE PARAMETERID = 'APM000986';
DELETE FROM TBLMNETCONFIGURATIONPARAMETER WHERE PARAMETERID = 'APM000986';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 7 WHERE PARAMETERID = 'APM000844' AND CONFIGID = 'CNF0032';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 8 WHERE PARAMETERID = 'APM000845' AND CONFIGID = 'CNF0032';

-- Removed Immediate flush from NAS Configuration --
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011655';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011656';
DELETE FROM TBLMNETCONFIGURATIONVALUES WHERE PARAMETERID = 'APM000987';
DELETE FROM TBLMNETCONFIGURATIONPARAMETER WHERE PARAMETERID = 'APM000987';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 7 WHERE PARAMETERID = 'APM000863' AND CONFIGID = 'CNF0033';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 8 WHERE PARAMETERID = 'APM000864' AND CONFIGID = 'CNF0033';

-- Removed Immediate flush from CC Configuration --
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011657';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011658';
DELETE FROM TBLMNETCONFIGURATIONVALUES WHERE PARAMETERID = 'APM000988';
DELETE FROM TBLMNETCONFIGURATIONPARAMETER WHERE PARAMETERID = 'APM000988';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 7 WHERE PARAMETERID = 'APM000882' AND CONFIGID = 'CNF0034';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 8 WHERE PARAMETERID = 'APM000883' AND CONFIGID = 'CNF0034';

-- Removed Immediate flush from Elite AAA RM Server Configuration --
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011659';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011660';
DELETE FROM TBLMNETCONFIGURATIONVALUES WHERE PARAMETERID = 'APM000989';
DELETE FROM TBLMNETCONFIGURATIONPARAMETER WHERE PARAMETERID = 'APM000989';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 6 WHERE PARAMETERID = 'APM000604' AND CONFIGID = 'CNF0018';

-- Removed Immediate flush from RM Diameter Stack Configuration --
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011643';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011644';
DELETE FROM TBLMNETCONFIGURATIONVALUES WHERE PARAMETERID = 'APM000981';
DELETE FROM TBLMNETCONFIGURATIONPARAMETER WHERE PARAMETERID = 'APM000981';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 7 WHERE PARAMETERID = 'APM000946' AND CONFIGID = 'CNF0035';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 8 WHERE PARAMETERID = 'APM000947' AND CONFIGID = 'CNF0035';

-- Removed Immediate flush from RM Concurrent Login Service Configuration --
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011661';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011662';
DELETE FROM TBLMNETCONFIGURATIONVALUES WHERE PARAMETERID = 'APM000990';
DELETE FROM TBLMNETCONFIGURATIONPARAMETER WHERE PARAMETERID = 'APM000990';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 7 WHERE PARAMETERID = 'APM000543' AND CONFIGID = 'CNF0012';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 8 WHERE PARAMETERID = 'APM000613' AND CONFIGID = 'CNF0012';

-- Removed Immediate flush from RM IP Pool Configuration --
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011663';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011664';
DELETE FROM TBLMNETCONFIGURATIONVALUES WHERE PARAMETERID = 'APM000991';
DELETE FROM TBLMNETCONFIGURATIONPARAMETER WHERE PARAMETERID = 'APM000991';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 7 WHERE PARAMETERID = 'APM000545' AND CONFIGID = 'CNF0014';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 8 WHERE PARAMETERID = 'APM000616' AND CONFIGID = 'CNF0014';

-- Removed Immediate flush from RM Prepaid Charging Service Configuration --
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011665';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011666';
DELETE FROM TBLMNETCONFIGURATIONVALUES WHERE PARAMETERID = 'APM000992';
DELETE FROM TBLMNETCONFIGURATIONPARAMETER WHERE PARAMETERID = 'APM000992';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 7 WHERE PARAMETERID = 'APM000546' AND CONFIGID = 'CNF0015';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 8 WHERE PARAMETERID = 'APM000619' AND CONFIGID = 'CNF0015';

-- Removed Immediate flush from GTP Prime Service Configuration --
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011667';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011668';
DELETE FROM TBLMNETCONFIGURATIONVALUES WHERE PARAMETERID = 'APM000993';
DELETE FROM TBLMNETCONFIGURATIONPARAMETER WHERE PARAMETERID = 'APM000993';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 7 WHERE PARAMETERID = 'APM000547' AND CONFIGID = 'CNF0022';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 8 WHERE PARAMETERID = 'APM000607' AND CONFIGID = 'CNF0022';

-- Removed Immediate flush from RM Charging Service Configuration --
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011669';
DELETE FROM TBLMNETCONFIGPARAMVALUEPOOL WHERE PARAMPOOLID = 'VPL000011670';
DELETE FROM TBLMNETCONFIGURATIONVALUES WHERE PARAMETERID = 'APM000994';
DELETE FROM TBLMNETCONFIGURATIONPARAMETER WHERE PARAMETERID = 'APM000994';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 7 WHERE PARAMETERID = 'APM000565' AND CONFIGID = 'CNF0023';
UPDATE TBLMNETCONFIGURATIONPARAMETER SET SERIALNO = 8 WHERE PARAMETERID = 'APM000610' AND CONFIGID = 'CNF0023';

COMMIT;

-- Added Accounting Response Attributes in Radius Service Policy and Rename Response Attribute to Auth Response Attribute
ALTER TABLE TBLMRADIUSSERVICEPOLICY RENAME COLUMN RESPONSEATTRIBUTES TO AUTHRESPONSEATTRIBUTES;
ALTER TABLE TBLMRADIUSSERVICEPOLICY ADD ACCTRESPONSEATTRIBUTES VARCHAR2(2000);

COMMIT;

--Added Session Management in TGPP AAA Service Policy
ALTER TABLE TBLMTGPPAAASERVICEPOLICY ADD  SESSIONMANAGEMENT VARCHAR2(10);
ALTER TABLE TBLMTGPPAAASERVICEPOLICY DROP COLUMN  SESSIONMANAGERID;
COMMIT;

--Increased the size of Log File in Transaction Logger
ALTER TABLE TBLMTRANSACTIONLOGGER MODIFY LOGFILE VARCHAR(1024);
COMMIT;

--Removed column COMMANDCODEWISERESATTRIBUTE and moved it to XML
ALTER TABLE TBLMTGPPAAASERVICEPOLICY DROP COLUMN COMMANDCODEWISERESATTRIBUTE;

--ELITEAAA-3201, added column HOTLINEPOLICY to provide Universal Hotline support in Peer Profile
ALTER TABLE TBLMPEERPROFILE ADD HOTLINEPOLICY VARCHAR2(255);

--User Statistic Post Auth Plugin Insert Query
INSERT INTO TBLSPLUGINTYPE 
	(PLUGINTYPEID,PLUGINSERVICETYPEID,NAME,DISPLAYNAME,SERIALNO,ALIAS,DESCRIPTION,STATUS)
values
	(9, 1, 'User Statistic Post Auth Plugin', 'User Statistic Post Auth Plugin',1, 'USER_STATISTIC_POST_AUTH_PLUGIN', 'User Statistic Post Auth Plugin','Y');
	
--Added table TBLMUSERSTATPOSTAUTHPLUGIN to provide User Statistic Post Auth Plugin Support
CREATE TABLE TBLMUSERSTATPOSTAUTHPLUGIN(
  PLUGINID               NUMERIC(10),
  PLUGINDATA             BLOB,
  PLUGININSTANCEID       NUMERIC(20),
  CONSTRAINT PK_MUSERSTATPOSTAUTHPLUGIN PRIMARY KEY (PLUGINID),
  CONSTRAINT FK1_MUSERSTATPOSTAUTHPLUGIN  FOREIGN KEY (PLUGININSTANCEID) REFERENCES TBLMPLUGININSTANCEDATA (PLUGININSTANCEID)
);

--Added sequence SEQ_MUSERSTATPOSTAUTHPLUGIN to provide User Statistic Post Auth Plugin Support
CREATE SEQUENCE SEQ_MUSERSTATPOSTAUTHPLUGIN
    INCREMENT BY 1
    START WITH 20
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    CACHE 20
    NOORDER;
    
commit;

--Added SEQ_USERSTATISTICS required for User Statistic Post Auth Plugin
CREATE SEQUENCE SEQ_USERSTATISTICS 
    INCREMENT BY 1
    START WITH 20
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    CACHE 20
    NOORDER;

--Added TBLUSERSTATISTICS table required for User Statistic Post Auth Plugin
CREATE TABLE TBLUSERSTATISTICS(
  USERSTATISTICSID          NUMERIC,
  CREATE_DATE               TIMESTAMP,
  USER_NAME                 VARCHAR(253),
  REPLY_MESSAGE             VARCHAR(253),
  NAS_IP_ADDRESS            VARCHAR(20),
  NAS_PORT                  NUMERIC(10),
  SERVICE_TYPE              VARCHAR(50),
  FRAMED_PROTOCOL           VARCHAR(50),
  FRAMED_IP_ADDRESS         VARCHAR(20),
  FRAMED_IP_NETMASK         VARCHAR(20),
  FRAMED_ROUTING            VARCHAR(50),
  FILTER_ID                 VARCHAR(50),
  FRAMED_MTU                NUMERIC(10),
  CALLBACK_NUMBER           VARCHAR(50),
  CALLBACK_ID               VARCHAR(50),
  FRAMED_ROUTE              VARCHAR(50),
  SESSION_TIMEOUT           NUMERIC(10),
  IDLE_TIMEOUT              NUMERIC(10),
  TERMINATION_ACTION        VARCHAR(50),
  CALLED_STATION_ID         VARCHAR(253),
  CALLING_STATION_ID        VARCHAR(253),
  NAS_IDENTIFIER            VARCHAR(50),
  PROXY_STATE               NUMERIC(10),
  NAS_PORT_TYPE             VARCHAR(50),
  PORT_LIMIT                NUMERIC(10),
  EVENT_TIMESTAMP           NUMERIC(14),
  NAS_PORT_ID               VARCHAR(50),
  CONNECT_INFO              VARCHAR(253),
  PARAM_STR0                VARCHAR(253),
  PARAM_STR1                VARCHAR(253),
  PARAM_STR2                VARCHAR(253),
  PARAM_STR3                VARCHAR(253),
  PARAM_STR4                VARCHAR(253),
  PARAM_STR5                VARCHAR(253),
  PARAM_STR6                VARCHAR(253),
  PARAM_STR7                VARCHAR(253),
  PARAM_STR8                VARCHAR(253),
  PARAM_STR9                VARCHAR(253),
  PARAM_INT0                NUMERIC,
  PARAM_INT1                NUMERIC,
  PARAM_INT2                NUMERIC,
  PARAM_INT3                NUMERIC,
  PARAM_INT4                NUMERIC,
  PARAM_DATE0               TIMESTAMP,
  PARAM_DATE1               TIMESTAMP,
  PARAM_DATE2               TIMESTAMP,
  GROUPNAME                 VARCHAR(60),
  USER_IDENTITY             VARCHAR(100),
  ESN_MEID 				  	VARCHAR(16),
  CUI 	 				  	VARCHAR(64),
  HA_IP					  	VARCHAR(64),
  BS_ID					  	VARCHAR(64),
  PCF_SGSN_AGW 				VARCHAR(64),
  NAP_OPERATOR_CARRIER 		VARCHAR(64),
  LOCATION			        VARCHAR(255)
);

COMMIT;