INSERT INTO TBLMVERSION (SERIALNO,VERSION,SETUPMODE,COMPONENT,EXECUTED_ON) VALUES (SEQ_TBLMVERSION.nextval,'6.8.0.3','upgrade-csm-to-6.8.0.3','AAASMX',CURRENT_TIMESTAMP);
commit;

-- Added Secondary peer field in TBLMPEER
ALTER TABLE TBLMPEER ADD SECONDARYPEER VARCHAR(60);
COMMIT;