INSERT INTO TBLMVERSION (SERIALNO,VERSION,SETUPMODE,COMPONENT,EXECUTED_ON) VALUES (SEQ_TBLMVERSION.nextval,'6.8.0.5','upgrade-csm-to-6.8.0.5','AAASMX',CURRENT_TIMESTAMP);
COMMIT;

--ELITEAAA-3263, added column DEFAULTRESPONSEBEHAVIORTYPE and DEFAULTRESPONSEBEHAVIORPARAM to provide support of Default Response Behavior
ALTER TABLE TBLMCCPOLICY ADD DEFAULTRESPONSEBEHAVIORTYPE VARCHAR2(20);
ALTER TABLE TBLMCCPOLICY ADD DEFAULTRESPONSEBEHAVIORPARAM VARCHAR2(1000);

ALTER TABLE TBLMEAPPOLICY ADD DEFAULTRESPONSEBEHAVIORTYPE VARCHAR2(20);
ALTER TABLE TBLMEAPPOLICY ADD DEFAULTRESPONSEBEHAVIORPARAM VARCHAR2(1000);

ALTER TABLE TBLMNASPOLICY ADD DEFAULTRESPONSEBEHAVIORTYPE VARCHAR2(20);
ALTER TABLE TBLMNASPOLICY ADD DEFAULTRESPONSEBEHAVIORPARAM VARCHAR2(1000);

ALTER TABLE TBLMTGPPAAASERVICEPOLICY ADD DEFAULTRESPONSEBEHAVIORTYPE VARCHAR2(20);
ALTER TABLE TBLMTGPPAAASERVICEPOLICY ADD DEFAULTRESPONSEBEHAVIORPARAM VARCHAR2(1000);

COMMIT;

--ELITEAAA-3296, added column DBFAILUREACTION to provide DB failure action when Database failure happen in Diameter session manager
ALTER TABLE TBLMDIAMETERSESSIONMANAGER ADD DBFAILUREACTION	VARCHAR2(10) DEFAULT 'IGNORE';

--ELITEAAA-3325, updated all table of diameter service policy for set default existed value of defaultresponsebehaviortype and defaultresponsebehaviorparam column.
UPDATE TBLMNASPOLICY SET DEFAULTRESPONSEBEHAVIORTYPE='Reject';
UPDATE TBLMNASPOLICY SET DEFAULTRESPONSEBEHAVIORPARAM='5012';

UPDATE TBLMCCPOLICY SET DEFAULTRESPONSEBEHAVIORTYPE='Reject';
UPDATE TBLMCCPOLICY SET DEFAULTRESPONSEBEHAVIORPARAM='5012';

UPDATE TBLMEAPPOLICY SET DEFAULTRESPONSEBEHAVIORTYPE='Reject';
UPDATE TBLMEAPPOLICY SET DEFAULTRESPONSEBEHAVIORPARAM='5012';

UPDATE TBLMTGPPAAASERVICEPOLICY SET DEFAULTRESPONSEBEHAVIORTYPE='Reject';
UPDATE TBLMTGPPAAASERVICEPOLICY SET DEFAULTRESPONSEBEHAVIORPARAM='5012';

COMMIT;

CREATE SEQUENCE SEQ_MQUOTAMGTPLUGIN
    INCREMENT BY 1
    START WITH 20
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    CACHE 20
    NOORDER;

CREATE TABLE TBLMQUOTAMGTPLUGIN(
  PLUGINID               NUMERIC(10),
  PLUGINDATA             BLOB,
  PLUGININSTANCEID       NUMERIC(20),
  CONSTRAINT PK_MQUOTAMGTPLUGIN PRIMARY KEY (PLUGINID),
  CONSTRAINT FK1_MQUOTAMGTPLUGIN  FOREIGN KEY (PLUGININSTANCEID) REFERENCES TBLMPLUGININSTANCEDATA (PLUGININSTANCEID)
);

INSERT INTO TBLSPLUGINTYPE 
	(PLUGINTYPEID,PLUGINSERVICETYPEID,NAME,DISPLAYNAME,SERIALNO,ALIAS,DESCRIPTION,STATUS)
values
	(8, 1, 'Quota Management Plugin', 'Quota Management Plugin',1, 'QUOTA_MANAGEMENT_PLUGIN', 'Quota Management Plugin','Y');
	
COMMIT;