/*
 * Open API Goibibo API Program
 * Open API Spec of Goibibo APIs. You can find more about Open API Spec here (https://openapis.org/)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@goibibo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.brs.searchservice.models.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * DroppingPointsList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-25T08:25:14.822+05:30")
public class DroppingPointsList {
  @JsonProperty("DPTime")
  private String dpTime = null;

  @JsonProperty("BPContactNumber")
  private String bpContactNumber = null;

  @JsonProperty("DPName")
  private String dpName = null;

  @JsonProperty("DPAddress")
  private String dpAddress = null;

  @JsonProperty("DPLandmark")
  private String dpLandmark = null;

  @JsonProperty("DPId")
  private String dpId = null;

  @JsonProperty("DPContactNumber")
  private String dpContactNumber = null;

  @JsonProperty("BPLandmark")
  private String bpLandmark = null;

  @JsonProperty("DPCoordinates")
  private String dpCoordinates = null;

  @JsonProperty("BPAddress")
  private String bpAddress = null;

  @JsonProperty("DPLocation")
  private String dpLocation = null;

  public DroppingPointsList dpTime(String dpTime) {
    this.dpTime = dpTime;
    return this;
  }

   /**
   * Get dpTime
   * @return dpTime
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDpTime() {
    return dpTime;
  }

  public void setDpTime(String dpTime) {
    this.dpTime = dpTime;
  }

  public DroppingPointsList bpContactNumber(String bpContactNumber) {
    this.bpContactNumber = bpContactNumber;
    return this;
  }

   /**
   * Get bpContactNumber
   * @return bpContactNumber
  **/
  @ApiModelProperty(required = true, value = "")
  public String getBpContactNumber() {
    return bpContactNumber;
  }

  public void setBpContactNumber(String bpContactNumber) {
    this.bpContactNumber = bpContactNumber;
  }

  public DroppingPointsList dpName(String dpName) {
    this.dpName = dpName;
    return this;
  }

   /**
   * Get dpName
   * @return dpName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDpName() {
    return dpName;
  }

  public void setDpName(String dpName) {
    this.dpName = dpName;
  }

  public DroppingPointsList dpAddress(String dpAddress) {
    this.dpAddress = dpAddress;
    return this;
  }

   /**
   * Get dpAddress
   * @return dpAddress
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDpAddress() {
    return dpAddress;
  }

  public void setDpAddress(String dpAddress) {
    this.dpAddress = dpAddress;
  }

  public DroppingPointsList dpLandmark(String dpLandmark) {
    this.dpLandmark = dpLandmark;
    return this;
  }

   /**
   * Get dpLandmark
   * @return dpLandmark
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDpLandmark() {
    return dpLandmark;
  }

  public void setDpLandmark(String dpLandmark) {
    this.dpLandmark = dpLandmark;
  }

  public DroppingPointsList dpId(String dpId) {
    this.dpId = dpId;
    return this;
  }

   /**
   * Get dpId
   * @return dpId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDpId() {
    return dpId;
  }

  public void setDpId(String dpId) {
    this.dpId = dpId;
  }

  public DroppingPointsList dpContactNumber(String dpContactNumber) {
    this.dpContactNumber = dpContactNumber;
    return this;
  }

   /**
   * Get dpContactNumber
   * @return dpContactNumber
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDpContactNumber() {
    return dpContactNumber;
  }

  public void setDpContactNumber(String dpContactNumber) {
    this.dpContactNumber = dpContactNumber;
  }

  public DroppingPointsList bpLandmark(String bpLandmark) {
    this.bpLandmark = bpLandmark;
    return this;
  }

   /**
   * Get bpLandmark
   * @return bpLandmark
  **/
  @ApiModelProperty(required = true, value = "")
  public String getBpLandmark() {
    return bpLandmark;
  }

  public void setBpLandmark(String bpLandmark) {
    this.bpLandmark = bpLandmark;
  }

  public DroppingPointsList dpCoordinates(String dpCoordinates) {
    this.dpCoordinates = dpCoordinates;
    return this;
  }

   /**
   * Get dpCoordinates
   * @return dpCoordinates
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDpCoordinates() {
    return dpCoordinates;
  }

  public void setDpCoordinates(String dpCoordinates) {
    this.dpCoordinates = dpCoordinates;
  }

  public DroppingPointsList bpAddress(String bpAddress) {
    this.bpAddress = bpAddress;
    return this;
  }

   /**
   * Get bpAddress
   * @return bpAddress
  **/
  @ApiModelProperty(required = true, value = "")
  public String getBpAddress() {
    return bpAddress;
  }

  public void setBpAddress(String bpAddress) {
    this.bpAddress = bpAddress;
  }

  public DroppingPointsList dpLocation(String dpLocation) {
    this.dpLocation = dpLocation;
    return this;
  }

   /**
   * Get dpLocation
   * @return dpLocation
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDpLocation() {
    return dpLocation;
  }

  public void setDpLocation(String dpLocation) {
    this.dpLocation = dpLocation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DroppingPointsList droppingPointsList = (DroppingPointsList) o;
    return Objects.equals(this.dpTime, droppingPointsList.dpTime) &&
        Objects.equals(this.bpContactNumber, droppingPointsList.bpContactNumber) &&
        Objects.equals(this.dpName, droppingPointsList.dpName) &&
        Objects.equals(this.dpAddress, droppingPointsList.dpAddress) &&
        Objects.equals(this.dpLandmark, droppingPointsList.dpLandmark) &&
        Objects.equals(this.dpId, droppingPointsList.dpId) &&
        Objects.equals(this.dpContactNumber, droppingPointsList.dpContactNumber) &&
        Objects.equals(this.bpLandmark, droppingPointsList.bpLandmark) &&
        Objects.equals(this.dpCoordinates, droppingPointsList.dpCoordinates) &&
        Objects.equals(this.bpAddress, droppingPointsList.bpAddress) &&
        Objects.equals(this.dpLocation, droppingPointsList.dpLocation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dpTime, bpContactNumber, dpName, dpAddress, dpLandmark, dpId, dpContactNumber, bpLandmark, dpCoordinates, bpAddress, dpLocation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DroppingPointsList {\n");
    
    sb.append("    dpTime: ").append(toIndentedString(dpTime)).append("\n");
    sb.append("    bpContactNumber: ").append(toIndentedString(bpContactNumber)).append("\n");
    sb.append("    dpName: ").append(toIndentedString(dpName)).append("\n");
    sb.append("    dpAddress: ").append(toIndentedString(dpAddress)).append("\n");
    sb.append("    dpLandmark: ").append(toIndentedString(dpLandmark)).append("\n");
    sb.append("    dpId: ").append(toIndentedString(dpId)).append("\n");
    sb.append("    dpContactNumber: ").append(toIndentedString(dpContactNumber)).append("\n");
    sb.append("    bpLandmark: ").append(toIndentedString(bpLandmark)).append("\n");
    sb.append("    dpCoordinates: ").append(toIndentedString(dpCoordinates)).append("\n");
    sb.append("    bpAddress: ").append(toIndentedString(bpAddress)).append("\n");
    sb.append("    dpLocation: ").append(toIndentedString(dpLocation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

