package com.elitecore.nvsmx.snmp.mib.webservice.autogencode;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling NETVERTEX-PCRF-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "ResetUsageWSResultCodeWiseEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.21067.4.1.3.12.6.1.
 */
public class ResetUsageWSResultCodeWiseEntry implements ResetUsageWSResultCodeWiseEntryMBean, Serializable {

	public ResetUsageWSResultCodeWiseEntry() {
		// TODO Auto-generated constructor stub
	}
    /**
     * Variable for storing the value of "ResetUsageWSResultCodeCounters".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.12.6.1.3".
     *
     * "ResetUsageWS ResultCode statistics."
     *
     */
    protected Long ResetUsageWSResultCodeCounters = new Long(1);

    /**
     * Variable for storing the value of "ResetUsageWSResultCodeName".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.12.6.1.2".
     *
     * "ResetUsageWS ResultCode Name."
     *
     */
    protected String ResetUsageWSResultCodeName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "ResetUsageWSResultCode".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.12.6.1.1".
     *
     * "ResetUsageWS ResultCode."
     *
     */
    protected Integer ResetUsageWSResultCode = new Integer(1);


    /**
     * Constructor for the "ResetUsageWSResultCodeWiseEntry" group.
     */
    public ResetUsageWSResultCodeWiseEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "ResetUsageWSResultCodeCounters" variable.
     */
    public Long getResetUsageWSResultCodeCounters() throws SnmpStatusException {
        return ResetUsageWSResultCodeCounters;
    }

    /**
     * Getter for the "ResetUsageWSResultCodeName" variable.
     */
    public String getResetUsageWSResultCodeName() throws SnmpStatusException {
        return ResetUsageWSResultCodeName;
    }

    /**
     * Getter for the "ResetUsageWSResultCode" variable.
     */
    public Integer getResetUsageWSResultCode() throws SnmpStatusException {
        return ResetUsageWSResultCode;
    }

}
