package com.elitecore.nvsmx.snmp.mib.webservice.autogencode;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling NETVERTEX-PCRF-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SessionManagementWSMethodWiseEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.21067.4.1.3.11.5.1.
 */
public class SessionManagementWSMethodWiseEntry implements SessionManagementWSMethodWiseEntryMBean, Serializable {

	public SessionManagementWSMethodWiseEntry() {
		// TODO Auto-generated constructor stub
	}
    /**
     * Variable for storing the value of "SessionWSMethodAvgTPS".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.11.5.1.6".
     *
     * "Method's average TPS in SessionManagementWS for last one minute."
     *
     */
    protected Long SessionWSMethodAvgTPS = new Long(1);

    /**
     * Variable for storing the value of "SessionWSMethodLastMinuteTotalRequests".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.11.5.1.5".
     *
     * "Total number of SessionManagementWS method wise Requests received in Last Minute by Policy Designer."
     *
     */
    protected Long SessionWSMethodLastMinuteTotalRequests = new Long(1);

    /**
     * Variable for storing the value of "SessionWSMethodTotalResponses".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.11.5.1.4".
     *
     * "Total number of SessionManagementWS method wise Responses given by Policy Designer."
     *
     */
    protected Long SessionWSMethodTotalResponses = new Long(1);

    /**
     * Variable for storing the value of "SessionWSMethodTotalRequests".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.11.5.1.3".
     *
     * "Total number of SessionManagementWS method wise Requests received by Policy Designer."
     *
     */
    protected Long SessionWSMethodTotalRequests = new Long(1);

    /**
     * Variable for storing the value of "SessionWSMethodName".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.11.5.1.2".
     *
     * "SessionManagementWS method's Name"
     *
     */
    protected String SessionWSMethodName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SessionWSMethodIndex".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.11.5.1.1".
     *
     * " SessionManagementWS method's Index"
     *
     */
    protected Integer SessionWSMethodIndex = new Integer(1);


    /**
     * Constructor for the "SessionManagementWSMethodWiseEntry" group.
     */
    public SessionManagementWSMethodWiseEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "SessionWSMethodAvgTPS" variable.
     */
    public Long getSessionWSMethodAvgTPS() throws SnmpStatusException {
        return SessionWSMethodAvgTPS;
    }

    /**
     * Getter for the "SessionWSMethodLastMinuteTotalRequests" variable.
     */
    public Long getSessionWSMethodLastMinuteTotalRequests() throws SnmpStatusException {
        return SessionWSMethodLastMinuteTotalRequests;
    }

    /**
     * Getter for the "SessionWSMethodTotalResponses" variable.
     */
    public Long getSessionWSMethodTotalResponses() throws SnmpStatusException {
        return SessionWSMethodTotalResponses;
    }

    /**
     * Getter for the "SessionWSMethodTotalRequests" variable.
     */
    public Long getSessionWSMethodTotalRequests() throws SnmpStatusException {
        return SessionWSMethodTotalRequests;
    }

    /**
     * Getter for the "SessionWSMethodName" variable.
     */
    public String getSessionWSMethodName() throws SnmpStatusException {
        return SessionWSMethodName;
    }

    /**
     * Getter for the "SessionWSMethodIndex" variable.
     */
    public Integer getSessionWSMethodIndex() throws SnmpStatusException {
        return SessionWSMethodIndex;
    }

}
