package com.elitecore.nvsmx.snmp.mib.webservice.autogencode;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling NETVERTEX-PCRF-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SubscriptionWSChangeBillDayEntry" MBean.
 */
public interface SubscriptionWSChangeBillDayEntryMBean {

    /**
     * Getter for the "ChangeBillDayResultCodeCounters" variable.
     */
    public Long getChangeBillDayResultCodeCounters() throws SnmpStatusException;

    /**
     * Getter for the "ChangeBillDayResultCodeName" variable.
     */
    public String getChangeBillDayResultCodeName() throws SnmpStatusException;

    /**
     * Getter for the "ChangeBillDayResultCode" variable.
     */
    public Integer getChangeBillDayResultCode() throws SnmpStatusException;

}
