package com.elitecore.nvsmx.snmp.mib.webservice.autogencode;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling NETVERTEX-PCRF-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SubscriberWSUpdateSubscriberProfileEntry" MBean.
 */
public interface SubscriberWSUpdateSubscriberProfileEntryMBean {

    /**
     * Getter for the "UpdateSubscriberProfileResultCodeCounters" variable.
     */
    public Long getUpdateSubscriberProfileResultCodeCounters() throws SnmpStatusException;

    /**
     * Getter for the "UpdateSubscriberProfileResultCodeName" variable.
     */
    public String getUpdateSubscriberProfileResultCodeName() throws SnmpStatusException;

    /**
     * Getter for the "UpdateSubscriberProfileResultCode" variable.
     */
    public Integer getUpdateSubscriberProfileResultCode() throws SnmpStatusException;

}
