package com.elitecore.nvsmx.snmp.mib.webservice.autogencode;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling NETVERTEX-PCRF-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "SubscriptionWSListPackagesEntry" MBean.
 */
public interface SubscriptionWSListPackagesEntryMBean {

    /**
     * Getter for the "ListPackagesResultCodeCounters" variable.
     */
    public Long getListPackagesResultCodeCounters() throws SnmpStatusException;

    /**
     * Getter for the "ListPackagesResultCodeName" variable.
     */
    public String getListPackagesResultCodeName() throws SnmpStatusException;

    /**
     * Getter for the "ListPackagesResultCode" variable.
     */
    public Integer getListPackagesResultCode() throws SnmpStatusException;

}
