package com.elitecore.nvsmx.snmp.mib.webservice.autogencode;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling NETVERTEX-PCRF-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "SubscriberProvisioningWSMethodWiseEntry" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.21067.4.1.3.10.5.1.
 */
public class SubscriberProvisioningWSMethodWiseEntry implements SubscriberProvisioningWSMethodWiseEntryMBean, Serializable {

	public SubscriberProvisioningWSMethodWiseEntry() {
		// TODO Auto-generated constructor stub
	}
    /**
     * Variable for storing the value of "SubscriberWSMethodAvgTPS".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.10.5.1.6".
     *
     * "Method's average TPS in SubscriberProvisioningWS for last one minute."
     *
     */
    protected Long SubscriberWSMethodAvgTPS = new Long(1);

    /**
     * Variable for storing the value of "SubscriberWSMethodLastMinuteTotalRequests".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.10.5.1.5".
     *
     * "Total number of SubscriberProvisioningWS method wise Requests received in Last Minute by Policy Designer."
     *
     */
    protected Long SubscriberWSMethodLastMinuteTotalRequests = new Long(1);

    /**
     * Variable for storing the value of "SubscriberWSMethodTotalResponses".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.10.5.1.4".
     *
     * "Total number of SubscriberProvisioningWS method wise Responses given by Policy Designer."
     *
     */
    protected Long SubscriberWSMethodTotalResponses = new Long(1);

    /**
     * Variable for storing the value of "SubscriberWSMethodTotalRequests".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.10.5.1.3".
     *
     * "Total number of SubscriberProvisioningWS method wise Requests received by Policy Designer."
     *
     */
    protected Long SubscriberWSMethodTotalRequests = new Long(1);

    /**
     * Variable for storing the value of "SubscriberWSMethodName".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.10.5.1.2".
     *
     * "SubscriberProvisioningWS method's Name"
     *
     */
    protected String SubscriberWSMethodName = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "SubscriberWSMethodIndex".
     * The variable is identified by: "1.3.6.1.4.1.21067.4.1.3.10.5.1.1".
     *
     * "SubscriberProvisioningWS method's Index."
     *
     */
    protected Integer SubscriberWSMethodIndex = new Integer(1);


    /**
     * Constructor for the "SubscriberProvisioningWSMethodWiseEntry" group.
     */
    public SubscriberProvisioningWSMethodWiseEntry(SnmpMib myMib) {
    }

    /**
     * Getter for the "SubscriberWSMethodAvgTPS" variable.
     */
    public Long getSubscriberWSMethodAvgTPS() throws SnmpStatusException {
        return SubscriberWSMethodAvgTPS;
    }

    /**
     * Getter for the "SubscriberWSMethodLastMinuteTotalRequests" variable.
     */
    public Long getSubscriberWSMethodLastMinuteTotalRequests() throws SnmpStatusException {
        return SubscriberWSMethodLastMinuteTotalRequests;
    }

    /**
     * Getter for the "SubscriberWSMethodTotalResponses" variable.
     */
    public Long getSubscriberWSMethodTotalResponses() throws SnmpStatusException {
        return SubscriberWSMethodTotalResponses;
    }

    /**
     * Getter for the "SubscriberWSMethodTotalRequests" variable.
     */
    public Long getSubscriberWSMethodTotalRequests() throws SnmpStatusException {
        return SubscriberWSMethodTotalRequests;
    }

    /**
     * Getter for the "SubscriberWSMethodName" variable.
     */
    public String getSubscriberWSMethodName() throws SnmpStatusException {
        return SubscriberWSMethodName;
    }

    /**
     * Getter for the "SubscriberWSMethodIndex" variable.
     */
    public Integer getSubscriberWSMethodIndex() throws SnmpStatusException {
        return SubscriberWSMethodIndex;
    }

}
